/**
 * weights-to-ts: serialize a WeightsBundle to a TypeScript source file.
 *
 * The output is a single `.ts` file with an embedded WeightsBundle literal.
 * Load it at runtime via:
 *   import { TEM_WEIGHTS_BUNDLE } from "./generated/weights";
 *   const weights = loadWeightsFromBundle(TEM_WEIGHTS_BUNDLE);
 */

import type { WeightsBundle } from "../core/weights";

/**
 * Validate that all tensor arrays in a bundle have the expected shapes.
 * Throws a descriptive error on the first mismatch found.
 */
export function validateBundleShapes(bundle: WeightsBundle): void {
  const { config, weights: w } = bundle;
  const { nG, nX, nActions } = config;
  const nModules = nG.length;
  const sumG = nG.reduce((a, b) => a + b, 0);
  const sumP = nG.reduce((a, b) => a + b * 3, 0);

  if (w.rnn.length !== nActions) {
    throw new Error(`rnn: expected ${nActions} action entries, got ${w.rnn.length}`);
  }

  for (let a = 0; a < nActions; a++) {
    if (w.rnn[a].length !== nModules) {
      throw new Error(`rnn[${a}]: expected ${nModules} modules, got ${w.rnn[a].length}`);
    }
    for (let f = 0; f < nModules; f++) {
      const m = w.rnn[a][f];
      const { hiddenSize, inputSize } = m;
      const expectedWih = hiddenSize * inputSize;
      const expectedWhh = hiddenSize * hiddenSize;

      if (m.W_ih.length !== expectedWih) {
        throw new Error(
          `rnn[${a}][${f}].W_ih: expected ${expectedWih} elements, got ${m.W_ih.length}`,
        );
      }
      if (m.W_hh.length !== expectedWhh) {
        throw new Error(
          `rnn[${a}][${f}].W_hh: expected ${expectedWhh} elements, got ${m.W_hh.length}`,
        );
      }
    }
  }

  const expectedWtile = sumP * sumG;
  const expectedWrepeat = sumP * nX;

  if (w.conjunction.W_tile.length !== expectedWtile) {
    throw new Error(
      `conjunction.W_tile: expected ${expectedWtile} elements, got ${w.conjunction.W_tile.length}`,
    );
  }
  if (w.conjunction.W_repeat.length !== expectedWrepeat) {
    throw new Error(
      `conjunction.W_repeat: expected ${expectedWrepeat} elements, got ${w.conjunction.W_repeat.length}`,
    );
  }
}

/**
 * Serialize a WeightsBundle to a TypeScript source string.
 *
 * The generated file exports a single `TEM_WEIGHTS_BUNDLE` constant
 * typed as `WeightsBundle`. Pass it to `loadWeightsFromBundle()` to
 * get inference-ready `TEMWeights`.
 */
export function bundleToTypeScript(bundle: WeightsBundle): string {
  validateBundleShapes(bundle);

  const json = JSON.stringify(bundle, null, 2);

  return `/**
 * AUTO-GENERATED by tem-codegen — do not edit manually.
 * Source: ${bundle.sourceCommit ?? "unknown"}
 * Version: ${bundle.version}
 *
 * Usage:
 *   import { TEM_WEIGHTS_BUNDLE } from "./generated/weights";
 *   import { loadWeightsFromBundle } from "../core/weights";
 *   const weights = loadWeightsFromBundle(TEM_WEIGHTS_BUNDLE);
 */

import type { WeightsBundle } from "../core/weights";

export const TEM_WEIGHTS_BUNDLE: WeightsBundle = ${json} satisfies WeightsBundle;
`;
}
