pub(crate) fn tools_anthropic() -> serde_json::Value {
    serde_json::json!([
        {"name":"read_file","description":"Read the contents of a file at an absolute path.",
         "input_schema":{"type":"object","properties":{"path":{"type":"string","description":"Absolute path"}},"required":["path"]}},
        {"name":"write_file","description":"Write UTF-8 content to a file atomically.",
         "input_schema":{"type":"object","properties":{"path":{"type":"string"},"content":{"type":"string"}},"required":["path","content"]}},
        {"name":"edit_file","description":"Apply one or more targeted string replacements to a file. Each edit replaces old_str with new_str; fails if old_str is not found or appears more than once.",
         "input_schema":{"type":"object","properties":{"path":{"type":"string","description":"Absolute path to the file"},"edits":{"type":"array","items":{"type":"object","properties":{"old_str":{"type":"string"},"new_str":{"type":"string"}},"required":["old_str","new_str"]},"description":"Ordered list of replacements to apply"}},"required":["path","edits"]}},
        {"name":"list_dir","description":"List files and directories at a path.",
         "input_schema":{"type":"object","properties":{"path":{"type":"string","description":"Absolute path to directory"}},"required":["path"]}},
        {"name":"search_files","description":"Search for a pattern in files (grep). Returns matching lines with file:line prefix.",
         "input_schema":{"type":"object","properties":{"pattern":{"type":"string","description":"Regular expression to search for"},"path":{"type":"string","description":"Absolute path to search in"},"glob":{"type":"string","description":"Optional filename glob filter, e.g. *.rs"}},"required":["pattern","path"]}},
        {"name":"bash","description":"Run a command via structured argv (argv[0] is the binary, no shell expansion).",
         "input_schema":{"type":"object","properties":{"argv":{"type":"array","items":{"type":"string"}},"cwd":{"type":"string"},"timeout_ms":{"type":"integer"}},"required":["argv"]}},
        {"name":"read_structured","description":"Parse a structured file (JSON, TOML, YAML) and return its content with automatic pagination for large files. Use page_size to control how many items/keys to return. Returns a metadata header followed by content.",
         "input_schema":{"type":"object","properties":{"path":{"type":"string","description":"Absolute path to the file"},"format":{"type":"string","enum":["json","toml","yaml"],"description":"File format (auto-detected from extension if omitted)"},"page_size":{"type":"integer","description":"Max items/keys to return (default 50; 0 = return all)"},"page_offset":{"type":"integer","description":"Skip this many items/keys before returning (default 0)"}},"required":["path"]}},
        {"name":"write_structured","description":"Validate and write structured content (JSON, TOML, YAML) to a file atomically. Validates syntax before writing — invalid content returns an error without touching the file.",
         "input_schema":{"type":"object","properties":{"path":{"type":"string","description":"Absolute path to write"},"content":{"type":"string","description":"The structured content to write"},"format":{"type":"string","enum":["json","toml","yaml"],"description":"Format for validation (auto-detected from extension if omitted)"}},"required":["path","content"]}},
        {"name":"list_sessions","description":"List all conversation sessions stored in the CRDT. Shows id, name, leaf_entry_id, and which session is currently active.",
         "input_schema":{"type":"object","properties":{}}},
        {"name":"current_session","description":"Return metadata about the currently active conversation session, including its id and current leaf_entry_id (tip of the conversation tree).",
         "input_schema":{"type":"object","properties":{}}},
        {"name":"navigate","description":"Move the active session's conversation pointer to a specific entry in the tree. Use this to resume from an earlier point (e.g., before trying a different approach).",
         "input_schema":{"type":"object","properties":{"session_id":{"type":"string","description":"Session to navigate"},"entry_id":{"type":"string","description":"Target entry to set as new leaf"}},"required":["session_id","entry_id"]}},
        {"name":"fork","description":"Create a new session branching from a specific entry of an existing session. The original session is unchanged. Use before exploring a risky approach.",
         "input_schema":{"type":"object","properties":{"session_id":{"type":"string"},"entry_id":{"type":"string"},"name":{"type":"string","description":"Optional name for the new fork"}},"required":["session_id","entry_id"]}},
        {"name":"find_references","description":"Find all references to a symbol at a given location in source code. Requires a language server (LSP) to be connected to the project.",
         "input_schema":{"type":"object","properties":{"file":{"type":"string","description":"Absolute path to the source file"},"line":{"type":"integer","description":"0-based line number"},"column":{"type":"integer","description":"0-based column number"}},"required":["file","line","column"]}},
        {"name":"rename_symbol","description":"Rename a symbol at a given location across the entire project. Requires a language server (LSP). Returns files changed and edit count.",
         "input_schema":{"type":"object","properties":{"file":{"type":"string"},"line":{"type":"integer"},"column":{"type":"integer"},"new_name":{"type":"string","description":"New name for the symbol"}},"required":["file","line","column","new_name"]}}
    ])
}

pub(crate) fn tools_openai() -> serde_json::Value {
    serde_json::json!([
        {"type":"function","function":{"name":"read_file","description":"Read file at absolute path.",
         "parameters":{"type":"object","properties":{"path":{"type":"string"}},"required":["path"]}}},
        {"type":"function","function":{"name":"write_file","description":"Write UTF-8 content to file atomically.",
         "parameters":{"type":"object","properties":{"path":{"type":"string"},"content":{"type":"string"}},"required":["path","content"]}}},
        {"type":"function","function":{"name":"edit_file","description":"Apply one or more targeted string replacements to a file. Each edit replaces old_str with new_str; fails if old_str is not found or appears more than once.",
         "parameters":{"type":"object","properties":{"path":{"type":"string"},"edits":{"type":"array","items":{"type":"object","properties":{"old_str":{"type":"string"},"new_str":{"type":"string"}},"required":["old_str","new_str"]}}},"required":["path","edits"]}}},
        {"type":"function","function":{"name":"list_dir","description":"List files and directories at a path.",
         "parameters":{"type":"object","properties":{"path":{"type":"string"}},"required":["path"]}}},
        {"type":"function","function":{"name":"search_files","description":"Search for a pattern in files (grep). Returns matching lines with file:line prefix.",
         "parameters":{"type":"object","properties":{"pattern":{"type":"string"},"path":{"type":"string"},"glob":{"type":"string"}},"required":["pattern","path"]}}},
        {"type":"function","function":{"name":"bash","description":"Run command via structured argv (no shell expansion).",
         "parameters":{"type":"object","properties":{"argv":{"type":"array","items":{"type":"string"}},"cwd":{"type":"string"},"timeout_ms":{"type":"integer"}},"required":["argv"]}}},
        {"type":"function","function":{"name":"read_structured","description":"Parse a structured file (JSON, TOML, YAML) with automatic pagination.",
         "parameters":{"type":"object","properties":{"path":{"type":"string"},"format":{"type":"string","enum":["json","toml","yaml"]},"page_size":{"type":"integer"},"page_offset":{"type":"integer"}},"required":["path"]}}},
        {"type":"function","function":{"name":"write_structured","description":"Validate and write structured content (JSON, TOML, YAML) atomically. Rejects invalid syntax before touching the file.",
         "parameters":{"type":"object","properties":{"path":{"type":"string"},"content":{"type":"string"},"format":{"type":"string","enum":["json","toml","yaml"]}},"required":["path","content"]}}},
        {"type":"function","function":{"name":"list_sessions","description":"List all conversation sessions stored in the CRDT.",
         "parameters":{"type":"object","properties":{}}}},
        {"type":"function","function":{"name":"current_session","description":"Return metadata about the currently active conversation session.",
         "parameters":{"type":"object","properties":{}}}},
        {"type":"function","function":{"name":"navigate","description":"Move the active session's conversation pointer to a specific entry in the tree.",
         "parameters":{"type":"object","properties":{"session_id":{"type":"string"},"entry_id":{"type":"string"}},"required":["session_id","entry_id"]}}},
        {"type":"function","function":{"name":"fork","description":"Create a new session branching from a specific entry of an existing session.",
         "parameters":{"type":"object","properties":{"session_id":{"type":"string"},"entry_id":{"type":"string"},"name":{"type":"string"}},"required":["session_id","entry_id"]}}},
        {"type":"function","function":{"name":"find_references","description":"Find all references to a symbol at a given source location. Requires LSP.",
         "parameters":{"type":"object","properties":{"file":{"type":"string"},"line":{"type":"integer"},"column":{"type":"integer"}},"required":["file","line","column"]}}},
        {"type":"function","function":{"name":"rename_symbol","description":"Rename a symbol across the entire project. Requires LSP. Returns files changed and edit count.",
         "parameters":{"type":"object","properties":{"file":{"type":"string"},"line":{"type":"integer"},"column":{"type":"integer"},"new_name":{"type":"string"}},"required":["file","line","column","new_name"]}}}
    ])
}
