packages:
  - "packages/*"
  - "apps/*"
  - "validations/*"
  - "validations/*/host"
  - "validations/*/browser"
  - "validations/*/hello-world"
  - "templates/*"
allowBuilds:
  esbuild: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
  workerd: true
auditConfig:
  ignoreGhsas:
    - GHSA-48c2-rrv3-qjmp
