// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod refarm {
        pub mod dispatch_surface {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod dispatch_surface_control {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// Supported transport kinds.
                #[derive(Clone)]
                pub enum DispatchTransport {
                    File,
                    Http,
                    Channel(_rt::String),
                }
                impl ::core::fmt::Debug for DispatchTransport {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            DispatchTransport::File => {
                                f.debug_tuple("DispatchTransport::File").finish()
                            }
                            DispatchTransport::Http => {
                                f.debug_tuple("DispatchTransport::Http").finish()
                            }
                            DispatchTransport::Channel(e) => {
                                f.debug_tuple("DispatchTransport::Channel")
                                    .field(e)
                                    .finish()
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_parse_task_transport_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::parse_task_transport(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            match e {
                                DispatchTransport::File => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                                DispatchTransport::Http => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                }
                                DispatchTransport::Channel(e) => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (2i32) as u8;
                                    let vec3 = (e.into_bytes()).into_boxed_slice();
                                    let ptr3 = vec3.as_ptr().cast::<u8>();
                                    let len3 = vec3.len();
                                    ::core::mem::forget(vec3);
                                    *ptr2
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len3;
                                    *ptr2
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr3.cast_mut();
                                }
                            }
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_parse_task_transport<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = i32::from(
                                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                            );
                            match l1 {
                                0 => {}
                                1 => {}
                                _ => {
                                    let l2 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l3 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l2, l3, 1);
                                }
                            }
                        }
                        _ => {
                            let l4 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_resolve_channel_from_transport_cabi<T: Guest>(
                    arg0: i32,
                    arg1: *mut u8,
                    arg2: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let v1 = match arg0 {
                        0 => DispatchTransport::File,
                        1 => DispatchTransport::Http,
                        n => {
                            debug_assert_eq!(n, 2, "invalid enum discriminant");
                            let e1 = {
                                let len0 = arg2;
                                let bytes0 = _rt::Vec::from_raw_parts(
                                    arg1.cast(),
                                    len0,
                                    len0,
                                );
                                _rt::string_lift(bytes0)
                            };
                            DispatchTransport::Channel(e1)
                        }
                    };
                    let result2 = T::resolve_channel_from_transport(v1);
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Some(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                        None => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_resolve_channel_from_transport<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_is_channel_effort_payload_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::is_channel_effort_payload(_rt::string_lift(bytes0));
                    match result1 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_normalize_channel_source_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i32,
                    arg3: *mut u8,
                    arg4: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result2 = T::normalize_channel_source(
                        _rt::string_lift(bytes0),
                        match arg2 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len1 = arg4;
                                    let bytes1 = _rt::Vec::from_raw_parts(
                                        arg3.cast(),
                                        len1,
                                        len1,
                                    );
                                    _rt::string_lift(bytes1)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec4 = (result2.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr3.add(0).cast::<*mut u8>() = ptr4.cast_mut();
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_normalize_channel_source<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_normalize_channel_context_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: i32,
                    arg5: *mut u8,
                    arg6: usize,
                    arg7: i32,
                    arg8: *mut u8,
                    arg9: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let result4 = T::normalize_channel_context(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                        match arg4 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len2 = arg6;
                                    let bytes2 = _rt::Vec::from_raw_parts(
                                        arg5.cast(),
                                        len2,
                                        len2,
                                    );
                                    _rt::string_lift(bytes2)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        match arg7 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len3 = arg9;
                                    let bytes3 = _rt::Vec::from_raw_parts(
                                        arg8.cast(),
                                        len3,
                                        len3,
                                    );
                                    _rt::string_lift(bytes3)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    );
                    let ptr5 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec6 = (result4.into_bytes()).into_boxed_slice();
                    let ptr6 = vec6.as_ptr().cast::<u8>();
                    let len6 = vec6.len();
                    ::core::mem::forget(vec6);
                    *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                    *ptr5.add(0).cast::<*mut u8>() = ptr6.cast_mut();
                    ptr5
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_normalize_channel_context<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_build_channel_effort_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let result2 = T::build_channel_effort(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec5 = (e.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_build_channel_effort<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_encode_channel_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::encode_channel(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = (result1.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_encode_channel<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_decode_channel_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::decode_channel(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = (result1.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_decode_channel<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_build_channel_efforts_path_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let result2 = T::build_channel_efforts_path(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec4 = (result2.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr3.add(0).cast::<*mut u8>() = ptr4.cast_mut();
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_build_channel_efforts_path<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_build_channel_effort_path_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: i32,
                    arg7: *mut u8,
                    arg8: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let len2 = arg5;
                    let bytes2 = _rt::Vec::from_raw_parts(arg4.cast(), len2, len2);
                    let result4 = T::build_channel_effort_path(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                        _rt::string_lift(bytes2),
                        match arg6 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len3 = arg8;
                                    let bytes3 = _rt::Vec::from_raw_parts(
                                        arg7.cast(),
                                        len3,
                                        len3,
                                    );
                                    _rt::string_lift(bytes3)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    );
                    let ptr5 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec6 = (result4.into_bytes()).into_boxed_slice();
                    let ptr6 = vec6.as_ptr().cast::<u8>();
                    let len6 = vec6.len();
                    ::core::mem::forget(vec6);
                    *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                    *ptr5.add(0).cast::<*mut u8>() = ptr6.cast_mut();
                    ptr5
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_build_channel_effort_path<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                pub trait Guest {
                    /// Parse and validate transport strings.
                    fn parse_task_transport(
                        transport: _rt::String,
                    ) -> Result<DispatchTransport, _rt::String>;
                    /// Resolve channel name from a parsed transport, if any.
                    fn resolve_channel_from_transport(
                        transport: DispatchTransport,
                    ) -> Option<_rt::String>;
                    /// Validate effort payload shape (`direction` + `tasks: array`).
                    fn is_channel_effort_payload(payload_json: _rt::String) -> bool;
                    /// Normalize source fallback to `channel:<name>` when absent.
                    fn normalize_channel_source(
                        channel: _rt::String,
                        source: Option<_rt::String>,
                    ) -> _rt::String;
                    /// Normalize channel metadata and merge into context.
                    fn normalize_channel_context(
                        context_json: _rt::String,
                        channel: _rt::String,
                        reply_to: Option<_rt::String>,
                        trace_ids_json: Option<_rt::String>,
                    ) -> _rt::String;
                    /// Build canonical channel effort JSON.
                    fn build_channel_effort(
                        payload_json: _rt::String,
                        channel: _rt::String,
                    ) -> Result<_rt::String, _rt::String>;
                    /// Escape/unescape channel identifiers in routes.
                    fn encode_channel(channel: _rt::String) -> _rt::String;
                    fn decode_channel(channel: _rt::String) -> _rt::String;
                    /// Build route helpers.
                    fn build_channel_efforts_path(
                        base_url: _rt::String,
                        channel: _rt::String,
                    ) -> _rt::String;
                    fn build_channel_effort_path(
                        base_url: _rt::String,
                        channel: _rt::String,
                        effort_id: _rt::String,
                        segment: Option<_rt::String>,
                    ) -> _rt::String;
                }
                #[doc(hidden)]
                macro_rules! __export_refarm_dispatch_surface_dispatch_surface_control_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "refarm:dispatch-surface/dispatch-surface-control@0.1.0#parse-task-transport")]
                        unsafe extern "C" fn export_parse_task_transport(arg0 : * mut u8,
                        arg1 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_parse_task_transport_cabi::<$ty > (arg0, arg1) } }
                        #[unsafe (export_name =
                        "cabi_post_refarm:dispatch-surface/dispatch-surface-control@0.1.0#parse-task-transport")]
                        unsafe extern "C" fn _post_return_parse_task_transport(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_parse_task_transport::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "refarm:dispatch-surface/dispatch-surface-control@0.1.0#resolve-channel-from-transport")]
                        unsafe extern "C" fn export_resolve_channel_from_transport(arg0 :
                        i32, arg1 : * mut u8, arg2 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*::
                        _export_resolve_channel_from_transport_cabi::<$ty > (arg0, arg1,
                        arg2) } } #[unsafe (export_name =
                        "cabi_post_refarm:dispatch-surface/dispatch-surface-control@0.1.0#resolve-channel-from-transport")]
                        unsafe extern "C" fn
                        _post_return_resolve_channel_from_transport(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_resolve_channel_from_transport::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "refarm:dispatch-surface/dispatch-surface-control@0.1.0#is-channel-effort-payload")]
                        unsafe extern "C" fn export_is_channel_effort_payload(arg0 : *
                        mut u8, arg1 : usize,) -> i32 { unsafe { $($path_to_types)*::
                        _export_is_channel_effort_payload_cabi::<$ty > (arg0, arg1) } }
                        #[unsafe (export_name =
                        "refarm:dispatch-surface/dispatch-surface-control@0.1.0#normalize-channel-source")]
                        unsafe extern "C" fn export_normalize_channel_source(arg0 : * mut
                        u8, arg1 : usize, arg2 : i32, arg3 : * mut u8, arg4 : usize,) ->
                        * mut u8 { unsafe { $($path_to_types)*::
                        _export_normalize_channel_source_cabi::<$ty > (arg0, arg1, arg2,
                        arg3, arg4) } } #[unsafe (export_name =
                        "cabi_post_refarm:dispatch-surface/dispatch-surface-control@0.1.0#normalize-channel-source")]
                        unsafe extern "C" fn _post_return_normalize_channel_source(arg0 :
                        * mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_normalize_channel_source::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "refarm:dispatch-surface/dispatch-surface-control@0.1.0#normalize-channel-context")]
                        unsafe extern "C" fn export_normalize_channel_context(arg0 : *
                        mut u8, arg1 : usize, arg2 : * mut u8, arg3 : usize, arg4 : i32,
                        arg5 : * mut u8, arg6 : usize, arg7 : i32, arg8 : * mut u8, arg9
                        : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_normalize_channel_context_cabi::<$ty > (arg0, arg1, arg2,
                        arg3, arg4, arg5, arg6, arg7, arg8, arg9) } } #[unsafe
                        (export_name =
                        "cabi_post_refarm:dispatch-surface/dispatch-surface-control@0.1.0#normalize-channel-context")]
                        unsafe extern "C" fn _post_return_normalize_channel_context(arg0
                        : * mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_normalize_channel_context::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "refarm:dispatch-surface/dispatch-surface-control@0.1.0#build-channel-effort")]
                        unsafe extern "C" fn export_build_channel_effort(arg0 : * mut u8,
                        arg1 : usize, arg2 : * mut u8, arg3 : usize,) -> * mut u8 {
                        unsafe { $($path_to_types)*::
                        _export_build_channel_effort_cabi::<$ty > (arg0, arg1, arg2,
                        arg3) } } #[unsafe (export_name =
                        "cabi_post_refarm:dispatch-surface/dispatch-surface-control@0.1.0#build-channel-effort")]
                        unsafe extern "C" fn _post_return_build_channel_effort(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_build_channel_effort::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "refarm:dispatch-surface/dispatch-surface-control@0.1.0#encode-channel")]
                        unsafe extern "C" fn export_encode_channel(arg0 : * mut u8, arg1
                        : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_encode_channel_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_refarm:dispatch-surface/dispatch-surface-control@0.1.0#encode-channel")]
                        unsafe extern "C" fn _post_return_encode_channel(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_encode_channel::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "refarm:dispatch-surface/dispatch-surface-control@0.1.0#decode-channel")]
                        unsafe extern "C" fn export_decode_channel(arg0 : * mut u8, arg1
                        : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_decode_channel_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_refarm:dispatch-surface/dispatch-surface-control@0.1.0#decode-channel")]
                        unsafe extern "C" fn _post_return_decode_channel(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_decode_channel::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "refarm:dispatch-surface/dispatch-surface-control@0.1.0#build-channel-efforts-path")]
                        unsafe extern "C" fn export_build_channel_efforts_path(arg0 : *
                        mut u8, arg1 : usize, arg2 : * mut u8, arg3 : usize,) -> * mut u8
                        { unsafe { $($path_to_types)*::
                        _export_build_channel_efforts_path_cabi::<$ty > (arg0, arg1,
                        arg2, arg3) } } #[unsafe (export_name =
                        "cabi_post_refarm:dispatch-surface/dispatch-surface-control@0.1.0#build-channel-efforts-path")]
                        unsafe extern "C" fn _post_return_build_channel_efforts_path(arg0
                        : * mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_build_channel_efforts_path::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "refarm:dispatch-surface/dispatch-surface-control@0.1.0#build-channel-effort-path")]
                        unsafe extern "C" fn export_build_channel_effort_path(arg0 : *
                        mut u8, arg1 : usize, arg2 : * mut u8, arg3 : usize, arg4 : * mut
                        u8, arg5 : usize, arg6 : i32, arg7 : * mut u8, arg8 : usize,) ->
                        * mut u8 { unsafe { $($path_to_types)*::
                        _export_build_channel_effort_path_cabi::<$ty > (arg0, arg1, arg2,
                        arg3, arg4, arg5, arg6, arg7, arg8) } } #[unsafe (export_name =
                        "cabi_post_refarm:dispatch-surface/dispatch-surface-control@0.1.0#build-channel-effort-path")]
                        unsafe extern "C" fn _post_return_build_channel_effort_path(arg0
                        : * mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_build_channel_effort_path::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_refarm_dispatch_surface_dispatch_surface_control_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_dispatch_surface_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::refarm::dispatch_surface::dispatch_surface_control::__export_refarm_dispatch_surface_dispatch_surface_control_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::refarm::dispatch_surface::dispatch_surface_control);
    };
}
#[doc(inline)]
pub(crate) use __export_dispatch_surface_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:refarm:dispatch-surface@0.1.0:dispatch-surface:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 831] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xb8\x05\x01A\x02\x01\
A\x02\x01B\x18\x01q\x03\x04file\0\0\x04http\0\0\x07channel\x01s\0\x04\0\x12dispa\
tch-transport\x03\0\0\x01j\x01\x01\x01s\x01@\x01\x09transports\0\x02\x04\0\x14pa\
rse-task-transport\x01\x03\x01ks\x01@\x01\x09transport\x01\0\x04\x04\0\x1eresolv\
e-channel-from-transport\x01\x05\x01@\x01\x0cpayload-jsons\0\x7f\x04\0\x19is-cha\
nnel-effort-payload\x01\x06\x01@\x02\x07channels\x06source\x04\0s\x04\0\x18norma\
lize-channel-source\x01\x07\x01@\x04\x0ccontext-jsons\x07channels\x08reply-to\x04\
\x0etrace-ids-json\x04\0s\x04\0\x19normalize-channel-context\x01\x08\x01j\x01s\x01\
s\x01@\x02\x0cpayload-jsons\x07channels\0\x09\x04\0\x14build-channel-effort\x01\x0a\
\x01@\x01\x07channels\0s\x04\0\x0eencode-channel\x01\x0b\x04\0\x0edecode-channel\
\x01\x0b\x01@\x02\x08base-urls\x07channels\0s\x04\0\x1abuild-channel-efforts-pat\
h\x01\x0c\x01@\x04\x08base-urls\x07channels\x09effort-ids\x07segment\x04\0s\x04\0\
\x19build-channel-effort-path\x01\x0d\x04\06refarm:dispatch-surface/dispatch-sur\
face-control@0.1.0\x05\0\x04\0.refarm:dispatch-surface/dispatch-surface@0.1.0\x04\
\0\x0b\x16\x01\0\x10dispatch-surface\x03\0\0\0G\x09producers\x01\x0cprocessed-by\
\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
