// TractorNativeBindings — host-side implementation of `tractor-bridge` WIT interface.
//
// Mirrors `WasiImports` from packages/tractor/src/lib/wasi-imports.ts.
//
// Implements traits generated by `wasmtime::component::bindgen!` in `plugin_host.rs`:
//   - `plugin::host::types::Host`          — empty (shared types interface, no methods)
//   - `plugin::host::tractor_bridge::Host` — CRDT/storage/telemetry host functions
//   - `plugin::host::model_bridge::Host`    — host-proxied HTTP completion boundary
//
// Return types use the WIT `result<T, plugin-error>` directly — no outer wasmtime::Result.

use crate::host::plugin_host::plugin::host::{
    model_bridge::{Host as ModelBridgeHost, StreamResponseMetadata, StreamResponseResult},
    tractor_bridge::{Host as TractorBridgeHost, NodePage},
    types::{Host as TypesHost, IdentityInfo, PluginError},
};
use crate::host::plugin_registry::PluginRegistry;
use crate::sync::NativeSync;
use crate::telemetry::TelemetryBus;
use std::io::Read as _;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ModelRoute {
    provider: String,
    base_url: String,
    path: String,
}

/// The handles a plugin's host-call needs to reach OTHER loaded plugins: the shared
/// capability registry (who is loaded + what they serve) and the event router (how a
/// dispatch reaches them). Cloned into every `TractorNativeBindings` at load, exactly
/// like `effect_policy` / `model_route` — so the cross-plugin host path reads `&self`,
/// never a global. All fields are `Arc`-backed clones sharing the runtime's live state.
///
/// This is the seam that unblocks two host features that both needed "reach another
/// loaded plugin" and were stalled on the same missing registry: the agent leg (#6,
/// `capability-tools` list/invoke) and `get_plugin_api` (was a STUB).
/// A SELF-DISPATCH spawner: given a plugin id + a `respond` payload JSON, load a FRESH
/// instance of that plugin and run its `respond` on that instance's own store/session,
/// returning the response JSON. This is the re-entrancy escape hatch for the deadlock a
/// plugin would hit dispatching a verb to ITSELF: its single runner thread is parked in
/// `await_dispatch_result`, so it can't also drain its own `<key>:dispatch` event. A
/// fresh instance sidesteps the busy runner entirely (the compiled Component is cached
/// by hash, so this is a cache-hit cold-init, not a recompile).
///
/// The actual load + respond hold a `!Send` wasmtime store, so the implementation runs
/// them via `spawn_local` on the caller's own current-thread runner runtime; the future
/// RETURNED here only awaits a `oneshot` for the result, so it IS `Send`. That keeps this
/// callable from the `Send`-required WIT host methods (`invoke_tool`/`call_plugin`) while
/// the `!Send` work stays on the local executor. `Send + Sync` on the boxed Fn: the
/// closure captures only Send+Sync state (`Weak<PluginHost>`, the `plugin_paths` Arc, the
/// sync handle), so `CrossPluginAccess` stays `Send + Sync` and clones into every binding.
pub type SelfRespondSpawner = std::sync::Arc<
    dyn Fn(
            String,
            String,
        ) -> std::pin::Pin<
            Box<dyn std::future::Future<Output = anyhow::Result<String>> + Send>,
        > + Send
        + Sync,
>;

#[derive(Clone)]
pub struct CrossPluginAccess {
    /// Who is loaded + what each declares (`provides`/`subscribes`). Source of truth
    /// for tool eligibility; a revoked plugin never loads → never here → not listable.
    pub registry: PluginRegistry,
    /// event-name → subscriber-ids, for enumerating + routing a `<key>:dispatch`.
    pub event_router: crate::EventRouter,
    /// plugin-id → runner channel, the sinks `deliver_via_router` sends to.
    pub plugin_channels: crate::PluginChannels,
    /// The self-dispatch spawner (see [`SelfRespondSpawner`]). Wrapped in a shared
    /// `OnceLock` because it is populated AFTER the `PluginHost` exists (it captures a
    /// `Weak` to it), while `CrossPluginAccess` itself is built BEFORE the host and
    /// cloned into it. Sharing the same `Arc<OnceLock>` means filling it once, post-boot,
    /// makes it visible to every plugin's already-cloned bindings. `None`/unset (test
    /// hosts, or a host wired without a runtime) → self-dispatch reports honestly instead
    /// of re-entering, i.e. the pre-existing deadlock-prone path is simply never taken.
    pub self_respond: std::sync::Arc<std::sync::OnceLock<SelfRespondSpawner>>,
}

/// Resolve the base URL a liveness probe should ping for `provider`, reusing the
/// SAME canonical resolution the completion path uses (`ModelRoute::for_provider`
/// — known-provider map, anthropic/openai families, MODEL_BASE_URL override, and
/// the localhost floor). This is the sidecar's single seam onto the provider→URL
/// map; the raw `known_provider_base_url` stays private so there is one source of
/// truth for "where is my provider" across completion and liveness.
pub(crate) fn provider_base_url_for_liveness(provider: &str) -> String {
    ModelRoute::for_provider(provider.trim().to_ascii_lowercase()).base_url
}

/// Host-side implementation of the `tractor-bridge` WIT interface.
///
/// Holds references to NativeSync (storage) and TelemetryBus so plugin
/// calls are forwarded to the actual Tractor infrastructure.
pub struct TractorNativeBindings {
    pub plugin_id: String,
    pub sync: NativeSync,
    pub telemetry: TelemetryBus,
    /// Effect-dispatch policy (shell allowlist + fs root) resolved from env ONCE
    /// at PluginHost boot and cloned in here at load, so the per-call effect path
    /// reads &self, never std::env::var.
    pub(crate) effect_policy: crate::host::host_effects_bridge::HostEffectPolicy,
    /// The provider THIS INVOCATION declared, narrowing the allowlist for its duration.
    ///
    /// ISS-140 tier B. The three route sets below are resolved once at plugin load, so they bound
    /// what the NODE may reach and nothing bounded what a single task may. A workspace bound to one
    /// account could therefore have its work sent to another, and the budget record would name the
    /// account the CLI intended rather than the one the host actually spent.
    ///
    /// NARROWING IS MONOTONICALLY SAFE, which is what makes reading the task's own declaration
    /// sound here: this can only INTERSECT with the boot allowlist, never widen it. A task that
    /// lies about its provider restricts itself and reaches nothing new — so the authorization
    /// still comes from the node's declaration, and only the SELECTION comes from the task.
    ///
    /// `None` is the un-narrowed state: a dispatch that declared no provider, or a host wired
    /// without the runner that sets this, behaves exactly as it did before.
    ///
    /// Single-threaded by construction rather than by lock: a plugin's invocations are served by
    /// one task that owns the handle and calls the guest one at a time.
    pub(crate) task_provider: Option<String>,
    /// The ACCOUNT this invocation declared, by opaque credential id (ISS-145).
    ///
    /// `task_provider` bounds WHERE a task may send; this bounds WHICH SEAT pays. They are
    /// different questions and one provider can hold two seats — the operator's Copilot pair have
    /// different endpoints and different entitlements, and a workspace binding that named one
    /// could not be honoured while the host read a single env var per provider.
    pub(crate) task_credential_id: Option<String>,
    /// The expected model ROUTE (provider + base-url + path) guardrail, resolved
    /// from the routing env vars (MODEL_PROVIDER / MODEL_BASE_URL)
    /// ONCE at boot. Read per model POST to validate the guest's requested route —
    /// no per-request env read. NOTE: only routing config lives here; the
    /// per-request API-key SECRETS stay in env (12-factor), read at send time
    /// keyed off the provider.
    pub(crate) model_route: ModelRoute,
    /// The OPTIONAL fallback route, resolved from MODEL_FALLBACK_PROVIDER once at
    /// boot (None when unset). When set, the model-POST guardrail accepts a request
    /// matching EITHER the primary route or this one — the host-side half of the
    /// guest's documented MODEL_FALLBACK_PROVIDER retry. None → single-route
    /// behavior, byte-identical to before this field existed.
    pub(crate) fallback_route: Option<ModelRoute>,
    /// ADR-012: the routes the guest may reach BY PROFILE — one per provider the
    /// operator configured (`MODEL_CONFIGURED_PROVIDERS`), resolved ONCE at load with
    /// the SAME per-provider logic as the primary/fallback route. The model-POST
    /// guardrail accepts a request matching the primary, the fallback, OR any of these.
    /// This keeps the boundary intact — the guest can only reach providers the operator
    /// configured — while letting a routing profile pick AMONG them. Empty when the
    /// list is unset (byte-identical to primary+fallback-only behavior).
    pub(crate) configured_routes: Vec<ModelRoute>,
    /// The plugin's capability grant: the permissions it DECLARED in its manifest
    /// plus the host security mode. `request_permission` consults this to answer
    /// honestly ("did this plugin declare this capability?") instead of always
    /// granting. Resolved at load from the manifest.
    pub(crate) permission_grant: PermissionGrant,
    /// The sovereign trusted-plugins allowlist resolved ONCE per load (fs ∩ node,
    /// deny-dominates — B) and cloned in, so the per-spawn host-shell gate reads
    /// `&self` instead of a live `.refarm/config.json` read on every spawn. The SAME
    /// set the load gate (`trusted_to_load`) used, so load and shell can never disagree
    /// — one source of truth, node-aware for free. None = permissive (not configured);
    /// Some(set): `*` = all, empty = deny-all.
    pub(crate) trusted_plugins: Option<std::collections::HashSet<String>>,
    /// The shared registry of LOADED plugins' capability profiles + a router handle,
    /// so a host-call from THIS plugin can list/invoke OTHER loaded plugins' verbs
    /// (the agent leg #6 `capability-tools`) and resolve a named API (`get_plugin_api`).
    /// `None` for test-constructed bindings / hosts wired without a registry — those
    /// paths keep the pre-registry behavior (empty tool list, `get_plugin_api` NotFound).
    pub(crate) cross_plugin: Option<crate::host::wasi_bridge::CrossPluginAccess>,
    /// The SHARED connection registry — ONE per host process, never one per plugin
    /// instance. A connection (e.g. `serpro-vpn`) is a resource several plugins
    /// legitimately want at once, and each establish is a phone-approval push for
    /// the operator; sharing is the entire point (see `host-connection` in
    /// `packages/plugin-wit/wit/host.wit`). `PluginHost` owns the single
    /// `Arc<ConnectionRegistry>` (beside `engine`/`linker`) and clones this SAME
    /// `Arc` into every `TractorNativeBindings` at load — constructing a fresh
    /// registry here instead would silently give each plugin its own "shared"
    /// connection, one login apiece.
    pub(crate) connection_registry:
        std::sync::Arc<crate::host::host_effects_bridge::ConnectionRegistry>,
}

/// A plugin's capability grant for the `request-permission` host export.
///
/// This is the honest minimal grant the architecture already implies: the
/// manifest DECLARES the permissions a plugin needs, so a request for a declared
/// permission is granted and an undeclared one is denied. Gated by `SecurityMode`:
/// in `None`/`Permissive` (dev) it grants regardless (mirroring the effect
/// bridge's permissive-when-unconfigured default); in `Strict` it enforces the
/// manifest declaration. NOTE: the WIT calls this a "user-facing permission
/// prompt", but the host has no prompt UI — the honest behavior is a static
/// manifest-declared allow/deny, which this documents.
#[derive(Debug, Clone)]
pub(crate) struct PermissionGrant {
    declared: std::collections::HashSet<String>,
    security_mode: crate::trust::SecurityMode,
}

impl PermissionGrant {
    pub(crate) fn new(
        declared: std::collections::HashSet<String>,
        security_mode: crate::trust::SecurityMode,
    ) -> Self {
        Self { declared, security_mode }
    }

    /// Permissive default (no declared permissions, dev security mode) — grants
    /// everything, matching the pre-wiring behavior. Used by test-constructed
    /// bindings and the host-effects load path.
    pub(crate) fn permissive() -> Self {
        Self {
            declared: std::collections::HashSet::new(),
            security_mode: crate::trust::SecurityMode::None,
        }
    }

    /// Decide whether `capability` is granted. Only `Strict` enforces the
    /// manifest declaration; dev modes grant regardless. Consulted both by
    /// request_permission (guest-cooperative advisory) and, for interfaces the
    /// host can gate at the Linker, by the load path to pick a capability-scoped
    /// linker — turning the advisory into a real enforcement boundary.
    pub(crate) fn grants(&self, capability: &str) -> bool {
        match self.security_mode {
            crate::trust::SecurityMode::Strict => self.declared.contains(capability),
            crate::trust::SecurityMode::Permissive | crate::trust::SecurityMode::None => true,
        }
    }

    /// Typed grant check over the canonical vocabulary. Callers that know the
    /// capability at compile time (the host-fs/host-shell/linker gates) use this
    /// so the permission string can never be a typo — the enum is the single
    /// source of truth. Delegates to `grants` on the wire string.
    pub(crate) fn grants_permission(&self, permission: crate::host::permission::Permission) -> bool {
        self.grants(permission.as_str())
    }

    /// Test constructor: a Strict grant declaring exactly `caps`.
    #[cfg(test)]
    pub(crate) fn strict_declaring(caps: &[&str]) -> Self {
        Self {
            declared: caps.iter().map(|c| c.to_string()).collect(),
            security_mode: crate::trust::SecurityMode::Strict,
        }
    }
}

#[cfg(test)]
mod permission_grant_tests {
    use super::PermissionGrant;

    #[test]
    fn strict_grants_only_declared_capabilities() {
        let grant = PermissionGrant::strict_declaring(&["fs:read", "shell:spawn"]);
        assert!(grant.grants("fs:read"), "declared capability is granted");
        assert!(grant.grants("shell:spawn"), "declared capability is granted");
        assert!(
            !grant.grants("network:outbound"),
            "an UNdeclared capability must be denied in Strict mode"
        );
        assert!(!grant.grants("fs:write"), "undeclared capability denied");
    }

    #[test]
    fn dev_modes_grant_regardless_of_declaration() {
        // Permissive default (no declarations, dev mode) grants everything —
        // matching the pre-wiring behavior so dev/test isn't broken.
        let grant = PermissionGrant::permissive();
        assert!(grant.grants("anything"));
        assert!(grant.grants("network:outbound"));
    }
}

#[cfg(test)]
mod get_identity_tests {
    use super::{guest_identity, identity_from_whoami};

    #[test]
    fn guest_is_the_least_privileged_fallback() {
        let g = guest_identity();
        assert_eq!(g.identity_type, "guest");
        assert_eq!(g.storage_tier, "ephemeral");
        assert_eq!(g.identifier, "");
    }

    #[test]
    fn whoami_result_maps_to_identity_info() {
        // The provider's DispatchResult node, shape as identity-provider-ref builds it.
        let node = r#"{"@type":"DispatchResult","replyRef":"r-1","result":{
            "identity_type":"sovereign","storage_tier":"persistent",
            "identifier":"did:refarm-wasm:abcd"}}"#;
        let info = identity_from_whoami(node).expect("maps");
        assert_eq!(info.identity_type, "sovereign");
        assert_eq!(info.storage_tier, "persistent");
        assert_eq!(info.identifier, "did:refarm-wasm:abcd");
    }

    #[test]
    fn error_result_yields_none_so_caller_falls_back_to_guest() {
        let node = r#"{"@type":"DispatchResult","replyRef":"r","result":{"error":"unknown verb"}}"#;
        assert!(identity_from_whoami(node).is_none());
    }

    #[test]
    fn malformed_or_incomplete_replies_yield_none() {
        assert!(identity_from_whoami("not json").is_none());
        assert!(identity_from_whoami(r#"{"noResult":true}"#).is_none());
        // Missing a required field (storage_tier) → None, never a fabricated identity.
        let partial = r#"{"result":{"identity_type":"sovereign"}}"#;
        assert!(identity_from_whoami(partial).is_none());
    }
}

impl TractorNativeBindings {
    /// The credential this invocation declared, read fresh from the env map.
    ///
    /// Resolved per call rather than cached: the CLI rewrites the map when a credential is renewed,
    /// and a cached copy would keep spending a token the node has already replaced.
    fn task_account(&self) -> Option<AccountCredential> {
        account_credential_from_env(self.task_credential_id.as_deref()?)
    }
}

impl TractorNativeBindings {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        plugin_id: impl Into<String>,
        sync: NativeSync,
        telemetry: TelemetryBus,
        effect_policy: crate::host::host_effects_bridge::HostEffectPolicy,
        model_route: ModelRoute,
        fallback_route: Option<ModelRoute>,
        permission_grant: PermissionGrant,
        trusted_plugins: Option<std::collections::HashSet<String>>,
        cross_plugin: Option<CrossPluginAccess>,
        connection_registry: std::sync::Arc<crate::host::host_effects_bridge::ConnectionRegistry>,
    ) -> Self {
        Self {
            plugin_id: plugin_id.into(),
            sync,
            telemetry,
            effect_policy,
            model_route,
            fallback_route,
            // Resolved once here at load (not per-request) from the same env the guest's
            // profile resolver reads, so host and guest agree on the configured set.
            configured_routes: ModelRoute::configured_routes_from_env(),
            // Nothing is running yet, so nothing is narrowed yet.
            task_provider: None,
            task_credential_id: None,
            permission_grant,
            trusted_plugins,
            cross_plugin,
            connection_registry,
        }
    }
}

// ── types::Host ───────────────────────────────────────────────────────────────
//
// The `types` interface defines shared types (plugin-error, identity-info, etc.)
// but contains no functions. The generated `Host` trait has no methods.
impl TypesHost for TractorNativeBindings {}

// ── tractor_bridge::Host ──────────────────────────────────────────────────────
//
// Each method corresponds to one WIT function in `tractor-bridge`.
// Return type is `Result<T, PluginError>` — the WIT result directly.

#[wasmtime::component::__internal::async_trait]
impl TractorBridgeHost for TractorNativeBindings {
    /// Store (upsert) a JSON-LD node into the sovereign graph.
    async fn store_node(&mut self, node_json: String) -> Result<String, PluginError> {
        let value: serde_json::Value = match serde_json::from_str(&node_json) {
            Ok(v) => v,
            Err(e) => return Err(PluginError::InvalidSchema(e.to_string())),
        };

        let id = value["@id"]
            .as_str()
            .or_else(|| value["id"].as_str())
            .unwrap_or("urn:unknown")
            .to_string();

        let type_ = value["@type"]
            .as_str()
            .or_else(|| value["type"].as_str())
            .unwrap_or("Unknown")
            .to_string();

        self.sync
            .store_node(&id, &type_, None, &node_json, Some(&self.plugin_id))
            .map_err(|e| PluginError::Internal(e.to_string()))?;

        self.telemetry.emit_named(
            "plugin:store_node",
            Some(self.plugin_id.clone()),
            Some(serde_json::json!({ "nodeId": id, "type": type_ })),
        );

        Ok(id)
    }

    /// Retrieve a previously stored node by ID.
    async fn get_node(&mut self, id: String) -> Result<String, PluginError> {
        match self.sync.get_node(&id) {
            Ok(Some(payload)) => Ok(payload),
            Ok(None) => Err(PluginError::NotFound(id)),
            Err(e) => Err(PluginError::Internal(e.to_string())),
        }
    }

    /// Query nodes by @type, returning up to `limit` results, NEWEST FIRST, plus the
    /// facts a guest needs to know whether that was everything.
    ///
    /// The limit is applied in SQL rather than by slicing here. Before 2026-08-06 this
    /// loaded every row of the type and dropped all but `limit`, which was affordable at
    /// 29 records and is not at 29,000. The ordering guarantee it relies on is documented
    /// in `docs/SOVEREIGN_RECORD_ORDERING.md`.
    ///
    /// `stored` (via `count_nodes`, a `SELECT COUNT(*)` that never materialises the rows
    /// it counts) is the true total of this `@type`, independent of `limit`. `truncated`
    /// is derived from `stored` versus how many rows `nodes` actually carries — NOT from
    /// `limit` — so a caller passing a limit larger than the total still gets
    /// `truncated: false`. Before 2026-08-06 the WIT signature returned a bare
    /// `list<json-ld-node>`, so a guest receiving exactly `limit` rows had no way to tell
    /// a complete answer from a cut one.
    async fn query_nodes(
        &mut self,
        node_type: String,
        limit: u32,
    ) -> Result<NodePage, PluginError> {
        let rows = self
            .sync
            .query_nodes_limited(&node_type, limit as usize)
            .map_err(|e| PluginError::Internal(e.to_string()))?;
        let stored = self
            .sync
            .count_nodes(&node_type)
            .map_err(|e| PluginError::Internal(e.to_string()))?;
        let nodes: Vec<String> = rows.into_iter().map(|r| r.payload).collect();
        let truncated = stored > nodes.len();
        Ok(NodePage {
            nodes,
            stored: stored as u32,
            truncated,
        })
    }

    /// Decide whether the plugin may use `capability`. The WIT names this a
    /// "user-facing permission prompt", but the host has no prompt UI — the honest
    /// behavior is a static grant from the plugin's manifest-declared permissions
    /// (see PermissionGrant): in Strict mode a declared capability is granted and
    /// an undeclared one denied; dev modes grant regardless. A denial is emitted
    /// as telemetry (a security-relevant event) rather than silently returned.
    async fn request_permission(&mut self, capability: String, reason: String) -> bool {
        let granted = self.permission_grant.grants(&capability);
        if !granted {
            self.telemetry.emit_named(
                "permission:denied",
                Some(self.plugin_id.clone()),
                Some(serde_json::json!({ "capability": capability, "reason": reason })),
            );
        }
        granted
    }

    /// Return the current user's identity information.
    ///
    /// Resolves an `identity:v1` provider via the SPI (`plugin_providing_api`, the same
    /// discovery `get_plugin_api` uses) and dispatches `identity:whoami` to it (the same
    /// dispatch `call_plugin` uses). When a provider is loaded, the identity it reports
    /// (type/tier/identifier, e.g. the DID of a sovereign key) is returned; otherwise —
    /// no registry, no provider, or ANY failure — this falls back to the anonymous guest.
    ///
    /// ADVISORY, not authoritative. The value is sourced from another untrusted plugin
    /// (whichever registered `api:identity:v1` first), so a caller must NOT gate a
    /// capability on it — capability gating stays with the manifest-backed permission
    /// system (`request_permission`). Fail-closed: any error yields the LEAST-privileged
    /// guest/ephemeral, never a fabricated elevated tier.
    async fn get_identity(&mut self) -> Result<IdentityInfo, PluginError> {
        let Some(cross) = self.cross_plugin.as_ref() else {
            return Ok(guest_identity());
        };
        let Some(provider_id) = cross.registry.plugin_providing_api("identity:v1") else {
            return Ok(guest_identity());
        };
        // Dispatch identity:whoami to the resolved provider — the same seam as call_plugin.
        let plugin_key = provider_id.rsplit('/').next().unwrap_or(&provider_id).to_string();
        let reply = crate::host::host_effects_bridge::dispatch_to_plugin(
            cross,
            &self.sync,
            &self.telemetry,
            crate::host::host_effects_bridge::DispatchTarget {
                caller_id: &self.plugin_id,
                plugin_id: &provider_id,
                plugin_key: &plugin_key,
                verb: "whoami",
            },
            serde_json::json!({}),
        )
        .await;
        // Any failure — dispatch error, malformed result, missing fields, an {error}
        // result — resolves to the guest. get_identity must never fail a caller.
        Ok(match reply {
            Ok(json) => identity_from_whoami(&json).unwrap_or_else(guest_identity),
            Err(_) => guest_identity(),
        })
    }

    /// Discover a plugin that provides a named API (SPI pattern).
    ///
    /// Resolves against the shared plugin registry (the same one that powers the
    /// agent leg's `capability-tools`): a loaded plugin that declares `api:<name>`
    /// in its `provides` is returned by id. Before the registry existed this was a
    /// STUB that always returned `NotFound`; that fallback remains when no registry
    /// is wired (test bindings), so behavior only ever GAINS resolution, never loses
    /// it. Only LOADED plugins resolve — a revoked/unloaded provider is invisible.
    async fn get_plugin_api(&mut self, api_name: String) -> Result<String, PluginError> {
        if let Some(cross) = self.cross_plugin.as_ref() {
            if let Some(plugin_id) = cross.registry.plugin_providing_api(&api_name) {
                return Ok(plugin_id);
            }
        }
        Err(PluginError::NotFound(format!(
            "no plugin provides api: {api_name}"
        )))
    }

    /// Call a verb on another loaded plugin, by its id (the SPI call leg, pairs with
    /// `get_plugin_api` discovery). Routes through the SAME shared dispatch the agent
    /// leg's tool-call uses (`dispatch_to_plugin`) — one protocol, addressed by verb,
    /// no duplication. The callee runs under ITS OWN grant; a revoked/unloaded target
    /// is absent from the registry so the dispatch finds no channel and fails honestly.
    async fn call_plugin(
        &mut self,
        plugin_id: String,
        verb: String,
        input_json: String,
    ) -> Result<String, PluginError> {
        let Some(cross) = self.cross_plugin.as_ref() else {
            return Err(PluginError::NotFound(
                "cross-plugin unavailable: no registry wired".to_string(),
            ));
        };
        let input = if input_json.trim().is_empty() {
            serde_json::json!({})
        } else {
            serde_json::from_str(&input_json).map_err(|e| PluginError::InvalidSchema(e.to_string()))?
        };
        // PARITY with the agent leg (invoke_tool): validate the caller's input against the target verb's
        // DECLARED schema before dispatch, so a plugin→plugin call with bad args is rejected up front —
        // not spread into the callee's payload. A verb with no declared schema has nothing to enforce.
        let verbs = cross.registry.dispatchable_verbs();
        if let Some(schema) =
            crate::host::host_effects_bridge::resolve_verb_schema(&verbs, &plugin_id, &verb)
        {
            crate::host::host_effects_bridge::validate_tool_input(schema, &input)
                .map_err(PluginError::InvalidSchema)?;
        }
        // A plugin_id carries no routing key; derive it the sidecar's canonical way
        // (last path segment): `@refarm.dev/quality` → `quality` for `quality:dispatch`.
        let plugin_key = plugin_id.rsplit('/').next().unwrap_or(&plugin_id).to_string();
        crate::host::host_effects_bridge::dispatch_to_plugin(
            cross,
            &self.sync,
            &self.telemetry,
            crate::host::host_effects_bridge::DispatchTarget {
                caller_id: &self.plugin_id,
                plugin_id: &plugin_id,
                plugin_key: &plugin_key,
                verb: &verb,
            },
            input,
        )
        .await
        .map_err(PluginError::Internal)
    }

    /// Emit a telemetry event from the plugin.
    async fn emit_telemetry(&mut self, event: String, payload: Option<String>) {
        let payload_val = payload.and_then(|p| serde_json::from_str(&p).ok());
        self.telemetry
            .emit_named(event, Some(self.plugin_id.clone()), payload_val);
    }
}

// ── model_bridge::Host ───────────────────────────────────────────────────────

#[wasmtime::component::__internal::async_trait]
impl ModelBridgeHost for TractorNativeBindings {
    async fn complete_http(
        &mut self,
        provider: String,
        base_url: String,
        path: String,
        headers: Vec<(String, String)>,
        body: Vec<u8>,
    ) -> Result<Vec<u8>, String> {
        model_complete_http(
            &provider,
            &base_url,
            &path,
            &headers,
            &body,
            self.task_provider.as_deref(),
            self.task_account().as_ref(),
            &self.model_route,
            self.fallback_route.as_ref(),
            &self.configured_routes,
        )
    }

    /// Streaming contract compatibility path.
    ///
    /// This preserves the new WIT boundary while final response semantics are
    /// still under design. It reads response bytes through the generic SSE
    /// reader seam and persists text chunks as complete SSE frames arrive.
    async fn complete_http_stream(
        &mut self,
        provider: String,
        base_url: String,
        path: String,
        headers: Vec<(String, String)>,
        body: Vec<u8>,
        stream_metadata: StreamResponseMetadata,
    ) -> Result<StreamResponseResult, String> {
        validate_stream_response_metadata(&stream_metadata)?;
        let resp = send_model_http_post(
            &provider,
            &base_url,
            &path,
            &headers,
            &body,
            self.task_provider.as_deref(),
            self.task_account().as_ref(),
            &self.model_route,
            self.fallback_route.as_ref(),
            &self.configured_routes,
        )?;
        let (final_body, last_sequence, stored_chunks) = store_stream_agent_response_chunks_from_reader(
            &self.sync,
            &self.plugin_id,
            &stream_metadata,
            resp.into_reader(),
            MAX_MODEL_RESPONSE_BODY_LEN,
        )?;
        Ok(buffered_stream_response_result(
            final_body,
            last_sequence,
            stored_chunks,
        ))
    }
}

/// The anonymous, least-privileged identity — the fail-closed fallback for
/// `get_identity` (no provider loaded, or any resolution/dispatch failure).
fn guest_identity() -> IdentityInfo {
    IdentityInfo {
        identity_type: "guest".to_string(),
        storage_tier: "ephemeral".to_string(),
        identifier: String::new(),
    }
}

/// Map an identity provider's `whoami` reply (a `DispatchResult` node JSON) into
/// `IdentityInfo`. Returns None on any shape mismatch or an `{error}` result — the
/// caller then falls back to the guest. Pure — unit-tested. The three string fields
/// mirror the WIT `identity-info` record and the provider's whoami result.
fn identity_from_whoami(node_json: &str) -> Option<IdentityInfo> {
    let node: serde_json::Value = serde_json::from_str(node_json).ok()?;
    let result = node.get("result")?;
    // An `{error}` result (unknown verb, provider failure) is not an identity.
    if result.get("error").is_some() {
        return None;
    }
    let field = |k: &str| result.get(k).and_then(|v| v.as_str()).map(str::to_string);
    Some(IdentityInfo {
        identity_type: field("identity_type")?,
        storage_tier: field("storage_tier")?,
        identifier: field("identifier").unwrap_or_default(),
    })
}

fn buffered_stream_response_result(
    final_body: Vec<u8>,
    last_sequence: Option<u32>,
    stored_chunks: u32,
) -> StreamResponseResult {
    StreamResponseResult {
        final_body,
        last_sequence,
        stored_chunks,
    }
}

fn validate_stream_response_metadata(metadata: &StreamResponseMetadata) -> Result<(), String> {
    validate_stream_text_field("prompt-ref", &metadata.prompt_ref, 512)?;
    validate_stream_text_field("model", &metadata.model, 256)?;
    let provider_family = normalize_provider_name(&metadata.provider_family);
    if provider_family != metadata.provider_family.trim() || !is_safe_provider_token(&provider_family) {
        return Err("[blocked: invalid stream provider-family]".to_string());
    }
    Ok(())
}

fn validate_stream_text_field(label: &str, value: &str, max_len: usize) -> Result<(), String> {
    if value.trim().is_empty() {
        return Err(format!("[blocked: stream {label} is empty]"));
    }
    if value.trim() != value || value.len() > max_len || !value.is_ascii() || value.chars().any(|c| c.is_control()) {
        return Err(format!("[blocked: invalid stream {label}]"));
    }
    Ok(())
}

// The model-HTTP call carries two natural groups — the request target
// (provider/base_url/path/headers/body) and the route guardrail
// (expected/fallback/configured, ADR-012) — passed positionally to keep this a thin
// internal seam. The guardrail's `configured` arg pushed it to 8; grouping into structs
// would ripple through the model bridge for no behavioural gain.
#[allow(clippy::too_many_arguments)]
#[allow(clippy::too_many_arguments)]
fn model_complete_http(
    provider: &str,
    base_url: &str,
    path: &str,
    headers: &[(String, String)],
    body: &[u8],
    task_provider: Option<&str>,
    task_account: Option<&AccountCredential>,
    expected: &ModelRoute,
    fallback: Option<&ModelRoute>,
    configured: &[ModelRoute],
) -> Result<Vec<u8>, String> {
    let resp = send_model_http_post(
        provider,
        base_url,
        path,
        headers,
        body,
        task_provider,
        task_account,
        expected,
        fallback,
        configured,
    )?;
    read_response_bytes(resp)
}

/// Accept a request that matches the primary route OR the optional fallback route.
/// Reuses the single-route `enforce_model_route` verbatim for each — every existing
/// validation branch is untouched. When there is no fallback (the common case), the
/// primary error is returned unchanged, so an unset MODEL_FALLBACK_PROVIDER behaves
/// byte-identically to a single-route host. On a fallback mismatch the primary
/// error surfaces (chosen to keep the no-fallback path's error string identical).
/// PURE. The routes admitted for THIS invocation, given what the task declared.
///
/// ISS-140 tier B. `None` leaves the set exactly as the node authorised it — the un-narrowed
/// behaviour, byte for byte. A declared provider INTERSECTS: only routes for that provider survive,
/// which can shrink the set to empty and can never add to it.
///
/// EMPTY IS A REFUSAL, not a fallthrough. A task that declares a provider the node never authorised
/// must be refused rather than quietly served by the primary route — that silent substitution is
/// the whole defect: a workspace bound to one account having its work sent to another while the
/// budget record named the first.
pub(crate) fn routes_for_task<'a>(
    task_provider: Option<&str>,
    primary: &'a ModelRoute,
    fallback: Option<&'a ModelRoute>,
    configured: &'a [ModelRoute],
) -> Vec<&'a ModelRoute> {
    let all: Vec<&ModelRoute> = std::iter::once(primary)
        .chain(fallback)
        .chain(configured.iter())
        .collect();
    let Some(wanted) = task_provider else {
        return all;
    };
    let wanted = normalize_provider_name(wanted);
    all.into_iter()
        .filter(|route| normalize_provider_name(&route.provider) == wanted)
        .collect()
}

fn enforce_model_route_any(
    provider: &str,
    base_url: &str,
    path: &str,
    primary: &ModelRoute,
    fallback: Option<&ModelRoute>,
    configured: &[ModelRoute],
) -> Result<(), String> {
    enforce_model_route_for_task(provider, base_url, path, None, primary, fallback, configured)
}

#[allow(clippy::too_many_arguments)]
fn enforce_model_route_for_task(
    provider: &str,
    base_url: &str,
    path: &str,
    task_provider: Option<&str>,
    primary: &ModelRoute,
    fallback: Option<&ModelRoute>,
    configured: &[ModelRoute],
) -> Result<(), String> {
    if let Some(wanted) = task_provider {
        let admitted = routes_for_task(Some(wanted), primary, fallback, configured);
        if admitted.is_empty() {
            return Err(format!(
                "[blocked: model-bridge task declared provider '{}', which this node did not authorise]",
                normalize_provider_name(wanted)
            ));
        }
        let mut last = String::new();
        for route in &admitted {
            match enforce_model_route(provider, base_url, path, route) {
                Ok(()) => return Ok(()),
                Err(err) => last = err,
            }
        }
        return Err(last);
    }
    match enforce_model_route(provider, base_url, path, primary) {
        Ok(()) => Ok(()),
        Err(primary_err) => {
            // Then the documented fallback route, then any ADR-012 configured-provider
            // route a profile may have selected. The PRIMARY error is what surfaces if
            // none match — so an unset fallback + empty configured list is byte-identical
            // to the single-route host, and the error string is unchanged.
            let mut nearest: Option<String> = None;
            let requested_provider = normalize_provider_name(provider);
            let mut consider = |route: &ModelRoute| -> Option<()> {
                match enforce_model_route(provider, base_url, path, route) {
                    Ok(()) => Some(()),
                    Err(err) => {
                        // THE NEAREST ROUTE'S COMPLAINT, not always the primary's. When a route was
                        // admitted for this very provider and refused the base url or the path, the
                        // primary's "provider mismatch" names a question nobody asked — measured
                        // 2026-08-17, where a Copilot request refused for its PATH was reported as
                        // requesting a provider the host did not expect, and the reading cost a
                        // debugging cycle before the real difference was found.
                        if nearest.is_none()
                            && normalize_provider_name(&route.provider) == requested_provider
                        {
                            nearest = Some(err);
                        }
                        None
                    }
                }
            };
            if let Some(fb) = fallback {
                if consider(fb).is_some() {
                    return Ok(());
                }
            }
            for route in configured {
                if consider(route).is_some() {
                    return Ok(());
                }
            }
            Err(nearest.unwrap_or(primary_err))
        }
    }
}

// Same request-target + route-guardrail parameter grouping as model_complete_http; the
// ADR-012 `configured` arg pushed it to 8. See that function's note.
#[allow(clippy::too_many_arguments)]
fn send_model_http_post(
    provider: &str,
    base_url: &str,
    path: &str,
    headers: &[(String, String)],
    body: &[u8],
    task_provider: Option<&str>,
    task_account: Option<&AccountCredential>,
    expected: &ModelRoute,
    fallback: Option<&ModelRoute>,
    configured: &[ModelRoute],
) -> Result<ureq::Response, String> {
    // THE ACCOUNT'S OWN ENDPOINT IS AN ADMITTED ROUTE (ISS-145). Two seats of one provider can
    // announce different hosts — the operator's Copilot pair do — so a task bound to the seat that
    // is NOT the provisioned default would otherwise be refused for a base url the node genuinely
    // authorised, just not under that provider's single entry.
    let account_route = task_account.and_then(|account| {
        account.base_url.as_ref().map(|url| ModelRoute {
            provider: normalize_provider_name(provider),
            base_url: url.clone(),
            path: known_provider_api_path(provider).to_string(),
        })
    });
    let mut admitted: Vec<ModelRoute> = configured.to_vec();
    if let Some(route) = account_route {
        admitted.push(route);
    }
    enforce_model_route_for_task(
        provider,
        base_url,
        path,
        task_provider,
        expected,
        fallback,
        &admitted,
    )?;
    enforce_model_request_body(body)?;
    let provider = normalize_provider_name(provider);

    let url = join_base_url_and_path(base_url, path);
    let mut req = ureq::post(&url);

    for (name, value) in sanitized_plugin_headers(headers) {
        req = req.set(name, value);
    }

    // THE SEAT THE TASK DECLARED, before the provider-wide variable. One env var per provider is
    // what made two accounts of one provider mutually exclusive; a task that named its account
    // spends THAT account, and one that named none keeps the previous behaviour exactly.
    let task_bearer = task_account.map(|account| format!("Bearer {}", account.access));
    if use_anthropic_auth(&provider) {
        let key = anthropic_api_key_from_env()?;
        req = req.set("x-api-key", &key);
    } else if use_openai_codex_auth(&provider) {
        let header = match task_bearer.clone() {
            Some(bearer) => bearer,
            None => bearer_key_for_provider(&provider)?
                .ok_or_else(|| "OPENAI_CODEX_ACCESS_TOKEN not set".to_string())?,
        };
        let account_id = match task_account.and_then(|a| a.account_id.clone()) {
            Some(id) => id,
            None => openai_codex_account_id_from_env()?,
        };
        for (name, value) in openai_codex_auth_headers(&header, &account_id, &codex_request_id()) {
            req = req.set(name, &value);
        }
    } else if use_github_copilot_auth(&provider) {
        let header = match task_bearer.clone() {
            Some(bearer) => bearer,
            None => bearer_key_for_provider(&provider)?
                .ok_or_else(|| "GITHUB_COPILOT_ACCESS_TOKEN not set".to_string())?,
        };
        for (name, value) in github_copilot_auth_headers(&header, &codex_request_id()) {
            req = req.set(name, &value);
        }
    } else if let Some(header) = task_bearer.or(bearer_key_for_provider(&provider)?) {
        req = req.set("authorization", &header);
    }

    match req.send_bytes(body) {
        Ok(resp) => Ok(resp),
        Err(ureq::Error::Status(code, resp)) => {
            let bytes = read_response_bytes(resp)?;
            Err(format!("HTTP {code}: {}", model_error_body_preview(&bytes)))
        }
        Err(e) => Err(format!("http error: {e}")),
    }
}

fn model_error_body_preview(bytes: &[u8]) -> String {
    const MAX_MODEL_ERROR_PREVIEW_LEN: usize = 8 * 1024;

    if bytes.len() <= MAX_MODEL_ERROR_PREVIEW_LEN {
        return String::from_utf8_lossy(bytes).to_string();
    }

    let prefix = String::from_utf8_lossy(&bytes[..MAX_MODEL_ERROR_PREVIEW_LEN]);
    format!(
        "{prefix}\n[truncated: model-bridge error body exceeded {MAX_MODEL_ERROR_PREVIEW_LEN} bytes]"
    )
}

fn use_anthropic_auth(provider: &str) -> bool {
    provider.trim().eq_ignore_ascii_case("anthropic")
}

/// PURE. One account's credential from the `MODEL_ACCOUNT_CREDENTIALS` map.
///
/// ## Why a per-ACCOUNT map exists at all
///
/// The host reads ONE credential env var per provider (`bearer_key_for_provider`), so two
/// authorised accounts of one provider could never both be provisioned — measured on the
/// operator's node, which holds a personal and a corporate Copilot seat with DIFFERENT endpoints
/// (`api.individual.` and `api.business.`). Until this existed, `provisionableAccounts` had to
/// refuse the pair and make him authorise one, and the workspace binding could name a seat the
/// host had no way to spend.
///
/// Keyed by the OPAQUE credential id, which is what the task already declares and what the budget
/// record already stamps — so the account that pays, the account that was bound, and the account
/// the record names are one id rather than three inferences.
///
/// NEVER REACHES THE GUEST: the key is refused by name in `sensitive_aliases::policy`, pinned by a
/// test there. The host reads it at send time and the guest holds a bridge handle.
pub(crate) fn parse_account_credential(
    raw: &str,
    credential_id: &str,
) -> Option<AccountCredential> {
    let parsed: serde_json::Value = serde_json::from_str(raw).ok()?;
    let entry = parsed.get(credential_id)?;
    let access = entry.get("access")?.as_str()?.trim();
    if access.is_empty() {
        return None;
    }
    let field = |name: &str| {
        entry
            .get(name)
            .and_then(|v| v.as_str())
            .map(str::trim)
            .filter(|v| !v.is_empty())
            .map(str::to_owned)
    };
    Some(AccountCredential {
        access: access.to_string(),
        account_id: field("accountId"),
        base_url: field("baseUrl"),
    })
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct AccountCredential {
    pub(crate) access: String,
    pub(crate) account_id: Option<String>,
    /// The endpoint THIS account announces, when it announces one. Per-account rather than
    /// per-provider because Copilot's token exchange returns a different host per seat.
    pub(crate) base_url: Option<String>,
}

/// The ENDPOINT half of a seat's credential, for callers that must not touch the token.
///
/// The sidecar needs the endpoint to tell the guest where to send; it has no business holding the
/// key. Two functions rather than one return value: a caller that only needs the address cannot
/// accidentally carry the secret with it.
pub(crate) fn account_base_url_from_env(credential_id: &str) -> Option<String> {
    account_credential_from_env(credential_id)?.base_url
}

fn account_credential_from_env(credential_id: &str) -> Option<AccountCredential> {
    let raw = std::env::var("MODEL_ACCOUNT_CREDENTIALS").ok()?;
    parse_account_credential(&raw, credential_id)
}

fn use_openai_codex_auth(provider: &str) -> bool {
    provider.trim().eq_ignore_ascii_case("openai-codex")
}

fn use_github_copilot_auth(provider: &str) -> bool {
    provider.trim().eq_ignore_ascii_case("github-copilot")
}

/// Copilot's editor-client headers.
///
/// DECLARED, NOT SMUGGLED. This node already announces that it reaches Copilot by imitating an
/// editor client — `refarm credential list` prints that notice on every listing, and clearing
/// `providers.githubCopilot.identity` stops it. The choice was made and printed; this is where it
/// is carried out. Sending only `authorization` reaches the endpoint and is refused by it.
fn github_copilot_auth_headers(bearer: &str, request_id: &str) -> Vec<(&'static str, String)> {
    vec![
        ("authorization", bearer.to_string()),
        ("Copilot-Integration-Id", "vscode-chat".to_string()),
        ("Editor-Version", "vscode/1.99.0".to_string()),
        ("Editor-Plugin-Version", "copilot-chat/0.26.0".to_string()),
        ("User-Agent", "GitHubCopilotChat/0.26.0".to_string()),
        ("Openai-Intent", "conversation-panel".to_string()),
        ("X-Request-Id", request_id.to_string()),
    ]
}

// Registry of known providers that need no MODEL_BASE_URL to work.
fn known_provider_base_url(provider: &str) -> Option<&'static str> {
    match provider.trim().to_ascii_lowercase().as_str() {
        "openai-codex" => Some("https://chatgpt.com"),
        "groq"       => Some("https://api.groq.com"),
        "mistral"    => Some("https://api.mistral.ai"),
        "xai"        => Some("https://api.x.ai"),
        "deepseek"   => Some("https://api.deepseek.com"),
        "together"   => Some("https://api.together.xyz"),
        "openrouter" => Some("https://openrouter.ai"),
        "gemini"     => Some("https://generativelanguage.googleapis.com"),
        _            => None,
    }
}

// Some providers diverge from the standard /v1/chat/completions path.
fn known_provider_api_path(provider: &str) -> &'static str {
    match provider.trim().to_ascii_lowercase().as_str() {
        "openai-codex" => "/backend-api/codex/responses",
        // Copilot speaks the OpenAI chat shape at its own root; its BASE URL is per-account and
        // arrives via MODEL_PROVIDER_BASE_URLS, never from a table here (ISS-141).
        "github-copilot" => "/chat/completions",
        "groq"       => "/openai/v1/chat/completions",
        "openrouter" => "/api/v1/chat/completions",
        "gemini"     => "/v1beta/openai/chat/completions",
        _            => "/v1/chat/completions",
    }
}

// Derive a Bearer auth header for any non-Anthropic provider.
// Resolution order: {PROVIDER_UPPER}_API_KEY → OPENAI_API_KEY (generic compat) → None (ollama).
/// A per-request identifier for the Codex `session-id`/`x-client-request-id`
/// headers. Derived from the wall clock — unique enough to identify a request;
/// prompt-cache affinity across a turn is a follow-on if it proves worth it.
fn codex_request_id() -> String {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| format!("refarm-{:032x}", d.as_nanos()))
        .unwrap_or_else(|_| "refarm-0".to_string())
}

/// The header set the ChatGPT-account Codex backend
/// (chatgpt.com/backend-api/codex/responses) expects from a legitimate client.
///
/// Advanced models (e.g. gpt-5.3-codex-spark and its separate worker quota) are
/// gated behind the FULL set a real Codex client sends — the default model works
/// with less, but the gated models do not. `originator` is refarm's OWN honest
/// identifier ("refarm", exactly as Pi sends "pi" — never impersonating the CLI);
/// the pieces that were missing are the protocol headers: a User-Agent, an SSE
/// `accept`, and a per-request session id. Pure so the shape is a tested invariant.
fn openai_codex_auth_headers(
    bearer: &str,
    account_id: &str,
    request_id: &str,
) -> Vec<(&'static str, String)> {
    vec![
        ("authorization", bearer.to_string()),
        ("chatgpt-account-id", account_id.to_string()),
        ("originator", "refarm".to_string()),
        ("OpenAI-Beta", "responses=experimental".to_string()),
        ("User-Agent", concat!("refarm/", env!("CARGO_PKG_VERSION")).to_string()),
        ("accept", "text/event-stream".to_string()),
        ("session-id", request_id.to_string()),
        ("x-client-request-id", request_id.to_string()),
    ]
}

fn bearer_key_for_provider(provider: &str) -> Result<Option<String>, String> {
    let normalized = normalize_provider_name(provider);

    let primary_env_var = if use_openai_codex_auth(&normalized) {
        "OPENAI_CODEX_ACCESS_TOKEN".to_string()
    } else if use_github_copilot_auth(&normalized) {
        // NOT the derived `GITHUB_COPILOT_API_KEY`. The credential is a subscription token, the
        // CLI exports it as `GITHUB_COPILOT_ACCESS_TOKEN` (`modelCredentialEnvKey`), and the
        // derived name would have looked for a variable nothing writes — a provider configured
        // everywhere and unreachable here.
        "GITHUB_COPILOT_ACCESS_TOKEN".to_string()
    } else if is_openai_provider_family(&normalized) {
        "OPENAI_API_KEY".to_string()
    } else {
        format!("{}_API_KEY", normalized.to_ascii_uppercase().replace('-', "_"))
    };

    let allow_openai_api_key_fallback =
        !use_openai_codex_auth(&normalized) && primary_env_var != "OPENAI_API_KEY";
    let (raw_key, used_var): (String, String) = match std::env::var(&primary_env_var) {
        Ok(k) => (k, primary_env_var),
        Err(_) if allow_openai_api_key_fallback => match std::env::var("OPENAI_API_KEY") {
            Ok(k) => (k, "OPENAI_API_KEY".to_string()),
            Err(_) => return Ok(None),
        },
        Err(_) => return Ok(None),
    };

    let key = sanitize_auth_token_for_header(&raw_key)
        .ok_or_else(|| format!("[blocked: invalid {used_var}]"))?;
    Ok(Some(format!("Bearer {key}")))
}

fn openai_codex_account_id_from_env() -> Result<String, String> {
    if let Ok(account_id) = std::env::var("OPENAI_CODEX_ACCOUNT_ID") {
        return sanitize_auth_token_for_header(&account_id)
            .ok_or_else(|| "[blocked: invalid OPENAI_CODEX_ACCOUNT_ID]".to_string());
    }
    let token = std::env::var("OPENAI_CODEX_ACCESS_TOKEN")
        .map_err(|_| "OPENAI_CODEX_ACCESS_TOKEN not set".to_string())?;
    extract_chatgpt_account_id_from_jwt(&token)
        .ok_or_else(|| "[blocked: invalid OPENAI_CODEX_ACCESS_TOKEN account claim]".to_string())
}

fn extract_chatgpt_account_id_from_jwt(token: &str) -> Option<String> {
    let payload = token.split('.').nth(1)?;
    let bytes = decode_base64url(payload)?;
    let value: serde_json::Value = serde_json::from_slice(&bytes).ok()?;
    let account_id = value
        .get("https://api.openai.com/auth")?
        .get("chatgpt_account_id")?
        .as_str()?;
    sanitize_auth_token_for_header(account_id)
}

fn decode_base64url(value: &str) -> Option<Vec<u8>> {
    fn sextet(byte: u8) -> Option<u8> {
        match byte {
            b'A'..=b'Z' => Some(byte - b'A'),
            b'a'..=b'z' => Some(byte - b'a' + 26),
            b'0'..=b'9' => Some(byte - b'0' + 52),
            b'-' => Some(62),
            b'_' => Some(63),
            b'=' => None,
            _ => None,
        }
    }

    let mut out = Vec::with_capacity(value.len() * 3 / 4);
    let mut buffer = 0u32;
    let mut bits = 0u8;
    for byte in value.bytes() {
        let Some(next) = sextet(byte) else {
            if byte == b'=' {
                break;
            }
            return None;
        };
        buffer = (buffer << 6) | u32::from(next);
        bits += 6;
        if bits >= 8 {
            bits -= 8;
            out.push(((buffer >> bits) & 0xff) as u8);
        }
    }
    Some(out)
}

fn enforce_model_request_body(body: &[u8]) -> Result<(), String> {
    const MAX_MODEL_REQUEST_BODY_LEN: usize = 1024 * 1024;
    if body.len() > MAX_MODEL_REQUEST_BODY_LEN {
        return Err("[blocked: model-bridge body too large]".to_string());
    }
    Ok(())
}

fn is_openai_provider_family(provider: &str) -> bool {
    let provider = provider.trim().to_ascii_lowercase();
    provider == "openai" || provider.starts_with("openai-")
}

fn sanitize_auth_token_for_header(token: &str) -> Option<String> {
    const MAX_AUTH_TOKEN_LEN: usize = 4096;
    let trimmed = token.trim();
    if trimmed.is_empty()
        || trimmed != token
        || trimmed.len() > MAX_AUTH_TOKEN_LEN
        || !trimmed.is_ascii()
        || trimmed.chars().any(|c| c.is_control())
        || trimmed.chars().any(|c| c.is_whitespace())
    {
        return None;
    }
    Some(trimmed.to_string())
}

fn anthropic_api_key_from_env() -> Result<String, String> {
    let key = std::env::var("ANTHROPIC_API_KEY")
        .map_err(|_| "ANTHROPIC_API_KEY not set".to_string())?;
    sanitize_auth_token_for_header(&key)
        .ok_or_else(|| "[blocked: invalid ANTHROPIC_API_KEY]".to_string())
}

fn provider_name_from_env() -> String {
    for key in ["MODEL_PROVIDER", "MODEL_DEFAULT_PROVIDER"] {
        if let Some(provider) = normalized_provider_from_env(key) {
            return provider;
        }
    }
    "ollama".to_string()
}

fn normalized_provider_from_env(key: &str) -> Option<String> {
    std::env::var(key)
        .ok()
        .map(|v| normalize_provider_name(&v))
        .filter(|v| !v.is_empty() && is_safe_provider_token(v))
}

fn normalize_provider_name(value: &str) -> String {
    value.trim().to_ascii_lowercase()
}

fn is_safe_provider_token(value: &str) -> bool {
    const MAX_PROVIDER_TOKEN_LEN: usize = 64;
    !value.is_empty()
        && value.len() <= MAX_PROVIDER_TOKEN_LEN
        && value
            .bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-' || b == b'_')
}

impl ModelRoute {
    /// Resolve the expected model route (provider + base-url + path) from the
    /// routing env vars ONCE at boot. This is the ONLY place the routing vars
    /// (MODEL_PROVIDER / MODEL_DEFAULT_PROVIDER, MODEL_BASE_URL) are read;
    /// the resolved route then rides on TractorNativeBindings and the per-request
    /// path validates against it without touching env. Secrets (API keys) are NOT
    /// part of this — they stay in env, read at send time keyed off the provider.
    pub(crate) fn from_env() -> Self {
        Self::for_provider(provider_name_from_env())
    }

    /// Build the route for a specific provider name, using the same per-provider
    /// resolution as `from_env` (anthropic hardcode, else known base/path or the
    /// openai-family / localhost floor, honoring MODEL_BASE_URL first). Shared by
    /// `from_env` and `fallback_from_env` so the primary and fallback routes are
    /// resolved by identical logic — the accepted fallback route equals exactly
    /// what the guest requests for that provider, nothing more.
    fn for_provider(provider: String) -> Self {
        if provider == "anthropic" {
            return ModelRoute {
                provider,
                base_url: "https://api.anthropic.com".to_string(),
                path: "/v1/messages".to_string(),
            };
        }

        let path = known_provider_api_path(&provider).to_string();
        // THE ACCOUNT'S OWN ENDPOINT FIRST. Some providers announce where to talk to them as part
        // of issuing the credential — GitHub Copilot returns a different host per seat
        // (`api.business.` vs `api.individual.`), measured on two real accounts 2026-08-17. A
        // static table cannot hold that, and the GLOBAL `MODEL_BASE_URL` cannot either: setting it
        // for one provider redirects every other provider's traffic with it.
        //
        // Order: the per-provider map, then the global override, then the static defaults. The map
        // is narrower than the override and describes a fact about the credential rather than an
        // operator's intent to redirect, so an operator who sets `MODEL_BASE_URL` deliberately is
        // still the one being obeyed for providers the map says nothing about.
        let base_url = provider_base_url_from_env(&provider)
            .or_else(model_base_url_from_env)
            .unwrap_or_else(|| {
            if let Some(url) = known_provider_base_url(&provider) {
                url.to_string()
            } else if is_openai_provider_family(&provider) {
                "https://api.openai.com".to_string()
            } else {
                "http://localhost:11434".to_string()
            }
        });

        ModelRoute { provider, base_url, path }
    }

    /// Resolve the OPTIONAL fallback route from MODEL_FALLBACK_PROVIDER, once at
    /// boot alongside `from_env`. Returns None when unset/empty/unsafe — and when
    /// None, the guardrail behaves byte-identically to a single-route host.
    ///
    /// The token is gated by `is_safe_provider_token`, which only admits
    /// `[a-z0-9_-]`. This keeps host and guest in lockstep for the routing that
    /// matters: the guest reads MODEL_FALLBACK_PROVIDER raw (runtime/wasm_flow.rs)
    /// and its openai-compat base_url/path arms (provider_config.rs, request_path.rs)
    /// are lowercase-only, so `for_provider` here selects the SAME branch off the
    /// SAME lowercase string. A non-lowercase spelling (e.g. "GROQ") is admitted by
    /// neither side's known-provider arms — the guest would fall through to the
    /// localhost default while the host returns None (no fallback route). That
    /// divergence fails CLOSED (the fallback simply does not activate) and only for
    /// a malformed provider token, so it is rejected here rather than routed.
    /// MODEL_FALLBACK_MODEL_ID is not read: model id does not change path/base_url.
    pub(crate) fn fallback_from_env() -> Option<ModelRoute> {
        let provider = std::env::var("MODEL_FALLBACK_PROVIDER").ok()?;
        let provider = provider.trim();
        if provider.is_empty() || !is_safe_provider_token(provider) {
            return None;
        }
        Some(Self::for_provider(provider.to_string()))
    }

    /// ADR-012: resolve one route per provider named in `MODEL_CONFIGURED_PROVIDERS`
    /// (the same non-secret list the guest resolves profiles against), using the SAME
    /// per-provider logic as the primary/fallback route. These are the routes a routing
    /// profile may legitimately select — the host accepts any of them so a profile can
    /// pick AMONG the operator's configured providers without the guardrail (pinned to
    /// the primary at boot) rejecting it. Unsafe/blank tokens are skipped; an unset or
    /// empty list yields an empty vec (no change to primary+fallback-only behavior).
    /// `parse_configured_providers` keeps the split-and-clean logic pure/testable.
    pub(crate) fn configured_routes_from_env() -> Vec<ModelRoute> {
        let raw = std::env::var("MODEL_CONFIGURED_PROVIDERS").unwrap_or_default();
        parse_configured_providers(&raw)
            .into_iter()
            .map(Self::for_provider)
            .collect()
    }
}

/// Split the `MODEL_CONFIGURED_PROVIDERS` list into safe, de-duplicated provider tokens.
/// Pure over its input (no env) so it is unit-testable. Separators are comma/whitespace;
/// tokens are lowercased and must pass `is_safe_provider_token` (a malformed token is
/// dropped, never routed). Order is preserved; duplicates are removed.
pub(crate) fn parse_configured_providers(raw: &str) -> Vec<String> {
    let mut seen = std::collections::HashSet::new();
    let mut out = Vec::new();
    for token in raw.split([',', ' ', '\t', '\n']) {
        let token = token.trim().to_ascii_lowercase();
        if token.is_empty() || !is_safe_provider_token(&token) {
            continue;
        }
        if seen.insert(token.clone()) {
            out.push(token);
        }
    }
    out
}

impl Default for ModelRoute {
    /// The env-unset default route (ollama on localhost) — what from_env resolves
    /// to with no routing vars set. Used by test-constructed bindings.
    fn default() -> Self {
        let provider = "ollama".to_string();
        ModelRoute {
            path: known_provider_api_path(&provider).to_string(),
            base_url: "http://localhost:11434".to_string(),
            provider,
        }
    }
}

#[cfg(test)]
impl ModelRoute {
    /// Explicit route (tests) — inject provider/base-url/path directly instead of
    /// steering the resolution via process env.
    pub(crate) fn for_test(provider: &str, base_url: &str, path: &str) -> Self {
        ModelRoute {
            provider: provider.to_string(),
            base_url: base_url.to_string(),
            path: path.to_string(),
        }
    }
}

/// PURE. One provider's endpoint from a `MODEL_PROVIDER_BASE_URLS` value.
///
/// FORMAT IS THE CONTRACT, shared with the CLI that writes it and the guest that reads it:
/// `provider=url` pairs joined by `,`, no whitespace, ASCII. A pair this cannot read is DROPPED
/// rather than guessed, which is what keeps host and guest able only to agree or both fall back —
/// never to disagree about where a request is allowed to go.
pub(crate) fn parse_provider_base_url(raw: &str, provider: &str) -> Option<String> {
    let wanted = provider.trim().to_ascii_lowercase();
    for pair in raw.split(',') {
        let (name, url) = pair.split_once('=')?;
        let name = name.trim().to_ascii_lowercase();
        let url = url.trim();
        if name != wanted || url.is_empty() {
            continue;
        }
        // Same shape the guardrail below will demand of it anyway; rejecting here keeps a
        // malformed entry from becoming an accepted route.
        if !url.starts_with("http://") && !url.starts_with("https://") {
            return None;
        }
        if !url.is_ascii() || url.chars().any(|c| c.is_whitespace() || c.is_control()) {
            return None;
        }
        return Some(url.to_string());
    }
    None
}

fn provider_base_url_from_env(provider: &str) -> Option<String> {
    let raw = std::env::var("MODEL_PROVIDER_BASE_URLS").ok()?;
    parse_provider_base_url(&raw, provider)
}

fn model_base_url_from_env() -> Option<String> {
    let value = std::env::var("MODEL_BASE_URL").ok()?;
    let trimmed = value.trim();
    if trimmed.is_empty() {
        None
    } else {
        Some(trimmed.to_string())
    }
}

fn enforce_model_route(
    provider: &str,
    base_url: &str,
    path: &str,
    expected: &ModelRoute,
) -> Result<(), String> {
    const MAX_BASE_URL_LEN: usize = 2048;
    const MAX_PATH_LEN: usize = 2048;

    if provider.chars().any(|c| c.is_control()) || expected.provider.chars().any(|c| c.is_control()) {
        return Err("[blocked: model-bridge provider contains control characters]".to_string());
    }
    if base_url.chars().any(|c| c.is_control()) || expected.base_url.chars().any(|c| c.is_control()) {
        return Err("[blocked: model-bridge base_url contains control characters]".to_string());
    }
    if path.chars().any(|c| c.is_control()) || expected.path.chars().any(|c| c.is_control()) {
        return Err("[blocked: model-bridge path contains control characters]".to_string());
    }
    if !path.is_ascii() || !expected.path.is_ascii() {
        return Err("[blocked: model-bridge path must be ascii]".to_string());
    }
    if path.trim().is_empty() || expected.path.trim().is_empty() {
        return Err("[blocked: model-bridge path must be non-empty]".to_string());
    }
    if path.trim() != path || expected.path.trim() != expected.path {
        return Err("[blocked: model-bridge path contains surrounding whitespace]".to_string());
    }
    if path.chars().any(|c| c.is_whitespace()) || expected.path.chars().any(|c| c.is_whitespace()) {
        return Err("[blocked: model-bridge path must not contain whitespace]".to_string());
    }
    if base_url.len() > MAX_BASE_URL_LEN || expected.base_url.len() > MAX_BASE_URL_LEN {
        return Err("[blocked: model-bridge base_url too long]".to_string());
    }
    if path.len() > MAX_PATH_LEN || expected.path.len() > MAX_PATH_LEN {
        return Err("[blocked: model-bridge path too long]".to_string());
    }
    if path.contains('?')
        || path.contains('#')
        || expected.path.contains('?')
        || expected.path.contains('#')
    {
        return Err("[blocked: model-bridge path must not include query or fragment]".to_string());
    }
    if path.contains('\\') || expected.path.contains('\\') {
        return Err("[blocked: model-bridge path contains invalid separator]".to_string());
    }

    let requested_provider = normalize_provider_name(provider);
    let expected_provider = normalize_provider_name(&expected.provider);
    if !is_safe_provider_token(&requested_provider) || !is_safe_provider_token(&expected_provider) {
        return Err("[blocked: model-bridge provider has invalid characters]".to_string());
    }
    if requested_provider != expected_provider {
        return Err(format!(
            "[blocked: model-bridge provider mismatch: requested '{requested_provider}', expected '{}']",
            expected_provider
        ));
    }

    let requested_base = normalize_base_url(base_url)?;
    let expected_base = normalize_base_url(&expected.base_url)?;
    if requested_base != expected_base {
        // BOTH VALUES, because the difference is the diagnosis and the operator cannot see either.
        // Measured 2026-08-17: this refused a Copilot request and named neither host, so the search
        // went to the allowlist while the difference was one seat's endpoint against another's.
        // These are addresses, not credentials — nothing here is secret.
        return Err(format!(
            "[blocked: model-bridge base_url not allowed: requested '{requested_base}', expected '{expected_base}']"
        ));
    }

    let requested_path = normalize_path(path);
    let expected_path = normalize_path(&expected.path);
    if requested_path != expected_path {
        return Err("[blocked: model-bridge path not allowed]".to_string());
    }

    Ok(())
}

fn normalize_base_url(base_url: &str) -> Result<String, String> {
    let raw = base_url.trim();
    if !raw.is_ascii() {
        return Err("[blocked: model-bridge base_url must be ascii]".to_string());
    }
    let lower_raw = raw.to_ascii_lowercase();

    if lower_raw.contains('?') || lower_raw.contains('#') {
        return Err("[blocked: model-bridge base_url must not include query or fragment]".to_string());
    }

    let rest = if let Some(v) = lower_raw.strip_prefix("http://") {
        v
    } else if let Some(v) = lower_raw.strip_prefix("https://") {
        v
    } else {
        return Err("[blocked: model-bridge base_url must use http(s)]".to_string());
    };

    let (authority, suffix) = rest
        .split_once('/')
        .map(|(a, b)| (a, Some(b)))
        .unwrap_or((rest, None));
    if authority.is_empty() {
        return Err("[blocked: model-bridge base_url must include host]".to_string());
    }
    if suffix.is_some_and(|s| !s.is_empty() && s.chars().any(|c| c != '/')) {
        return Err("[blocked: model-bridge base_url must not include path]".to_string());
    }
    if authority.contains('@') {
        return Err("[blocked: model-bridge base_url must not include credentials]".to_string());
    }
    if !is_safe_base_url_authority(authority) {
        return Err("[blocked: model-bridge base_url contains invalid authority characters]".to_string());
    }

    Ok(lower_raw.trim_end_matches('/').to_string())
}

fn is_safe_base_url_authority(authority: &str) -> bool {
    const MAX_AUTHORITY_LEN: usize = 255;
    if authority.is_empty() || authority.len() > MAX_AUTHORITY_LEN {
        return false;
    }

    fn valid_host_ascii(host: &str) -> bool {
        if host.is_empty() || host.len() > 253 {
            return false;
        }

        host.split('.').all(|label| {
            !label.is_empty()
                && label.len() <= 63
                && label
                    .bytes()
                    .all(|b| b.is_ascii_alphanumeric() || b == b'-')
                && label
                    .bytes()
                    .next()
                    .is_some_and(|b| b.is_ascii_alphanumeric())
                && label
                    .bytes()
                    .last()
                    .is_some_and(|b| b.is_ascii_alphanumeric())
        })
    }

    fn valid_port(port: &str) -> bool {
        if port.is_empty() || port.len() > 5 || !port.bytes().all(|b| b.is_ascii_digit()) {
            return false;
        }
        let Ok(value) = port.parse::<u16>() else {
            return false;
        };
        value > 0
    }

    if let Some(rest) = authority.strip_prefix('[') {
        let Some((ipv6, tail)) = rest.split_once(']') else {
            return false;
        };
        if ipv6.is_empty() || !ipv6.contains(':') || ipv6.parse::<std::net::Ipv6Addr>().is_err() {
            return false;
        }
        if tail.is_empty() {
            return true;
        }
        if let Some(port) = tail.strip_prefix(':') {
            return valid_port(port);
        }
        return false;
    }

    if authority.contains('[') || authority.contains(']') {
        return false;
    }

    match authority.rsplit_once(':') {
        Some((host, _port)) if host.contains(':') => false,
        Some((host, port)) => valid_host_ascii(host) && valid_port(port),
        None => valid_host_ascii(authority),
    }
}

fn normalize_path(path: &str) -> String {
    let p = path.trim();
    let mut normalized = if p.starts_with('/') {
        p.to_string()
    } else {
        format!("/{p}")
    };

    while normalized.len() > 1 && normalized.ends_with('/') {
        normalized.pop();
    }

    normalized
}

#[cfg(test)]
mod core_pure_tests {
    use super::*;

    // ── openai_codex_auth_headers ───────────────────────────────────────────
    // The header set that unlocks gated Codex models (worker-quota spark). A
    // regression guard: the protocol headers must stay present, and the
    // originator must stay refarm's OWN honest identifier — never the CLI's.

    #[test]
    fn codex_auth_headers_carry_the_full_gated_client_set() {
        let headers = openai_codex_auth_headers("Bearer tok", "acct-123", "req-abc");
        let map: std::collections::HashMap<&str, String> = headers.into_iter().collect();
        assert_eq!(map.get("authorization").map(String::as_str), Some("Bearer tok"));
        assert_eq!(map.get("chatgpt-account-id").map(String::as_str), Some("acct-123"));
        assert_eq!(map.get("OpenAI-Beta").map(String::as_str), Some("responses=experimental"));
        assert_eq!(map.get("accept").map(String::as_str), Some("text/event-stream"));
        assert_eq!(map.get("session-id").map(String::as_str), Some("req-abc"));
        assert_eq!(map.get("x-client-request-id").map(String::as_str), Some("req-abc"));
        // Honest identity — refarm names itself, and the UA is present + refarm-tagged.
        assert_eq!(map.get("originator").map(String::as_str), Some("refarm"));
        let ua = map.get("User-Agent").cloned().unwrap_or_default();
        assert!(ua.starts_with("refarm/"), "User-Agent must identify refarm: {ua}");
        assert!(!ua.contains("codex"), "must not impersonate the Codex CLI: {ua}");
    }

    #[test]
    fn codex_request_id_is_refarm_tagged_and_nonempty() {
        let id = codex_request_id();
        assert!(id.starts_with("refarm-"), "request id should be refarm-tagged: {id}");
        assert!(id.len() > "refarm-".len());
    }

    // ── provider_base_url_for_liveness ──────────────────────────────────────
    // Reads MODEL_BASE_URL via ModelRoute::for_provider, so guard the env and
    // resolve with MODEL_BASE_URL unset to exercise the per-provider defaults.

    #[test]
    fn liveness_base_url_covers_each_provider_family() {
        let _guard = crate::test_support::env_lock();
        let prev = std::env::var("MODEL_BASE_URL").ok();
        std::env::remove_var("MODEL_BASE_URL");

        // Resolve everything while the env is controlled, then restore, then assert.
        let anthropic = provider_base_url_for_liveness("anthropic");
        let codex = provider_base_url_for_liveness("openai-codex");
        let groq = provider_base_url_for_liveness("groq");
        let gemini = provider_base_url_for_liveness("gemini");
        let openai = provider_base_url_for_liveness("openai");
        let openai_family = provider_base_url_for_liveness("openai-foo");
        let unknown = provider_base_url_for_liveness("ollama");
        let messy = provider_base_url_for_liveness("  GROQ  ");

        match prev {
            Some(v) => std::env::set_var("MODEL_BASE_URL", v),
            None => std::env::remove_var("MODEL_BASE_URL"),
        }

        assert_eq!(anthropic, "https://api.anthropic.com");
        assert_eq!(codex, "https://chatgpt.com");
        assert_eq!(groq, "https://api.groq.com");
        assert_eq!(gemini, "https://generativelanguage.googleapis.com");
        // openai + openai-family (starts_with "openai-") fall to the openai floor.
        assert_eq!(openai, "https://api.openai.com");
        assert_eq!(openai_family, "https://api.openai.com");
        // An unknown provider gets the localhost floor.
        assert_eq!(unknown, "http://localhost:11434");
        // Surrounding whitespace + case are normalized before resolution.
        assert_eq!(messy, "https://api.groq.com");
    }

    #[test]
    fn liveness_base_url_honors_model_base_url_override_for_non_anthropic() {
        let _guard = crate::test_support::env_lock();
        let prev = std::env::var("MODEL_BASE_URL").ok();
        std::env::set_var("MODEL_BASE_URL", "https://proxy.example.com");

        let groq = provider_base_url_for_liveness("groq");
        // Anthropic is hardcoded and ignores MODEL_BASE_URL.
        let anthropic = provider_base_url_for_liveness("anthropic");

        match prev {
            Some(v) => std::env::set_var("MODEL_BASE_URL", v),
            None => std::env::remove_var("MODEL_BASE_URL"),
        }

        assert_eq!(groq, "https://proxy.example.com");
        assert_eq!(anthropic, "https://api.anthropic.com");
    }

    // ── use_anthropic_auth / use_openai_codex_auth ──────────────────────────

    #[test]
    fn anthropic_auth_selector_is_case_and_whitespace_insensitive() {
        assert!(use_anthropic_auth("anthropic"));
        assert!(use_anthropic_auth("Anthropic"));
        assert!(use_anthropic_auth("  ANTHROPIC  "));
        assert!(!use_anthropic_auth("openai"));
        assert!(!use_anthropic_auth("openai-codex"));
        assert!(!use_anthropic_auth(""));
    }

    #[test]
    fn openai_codex_auth_selector_is_case_and_whitespace_insensitive() {
        assert!(use_openai_codex_auth("openai-codex"));
        assert!(use_openai_codex_auth("OpenAI-Codex"));
        assert!(use_openai_codex_auth("  openai-codex  "));
        assert!(!use_openai_codex_auth("openai"));
        assert!(!use_openai_codex_auth("anthropic"));
        assert!(!use_openai_codex_auth(""));
    }

    // ── validate_stream_text_field ──────────────────────────────────────────

    #[test]
    fn stream_text_field_accepts_valid_within_limit_and_at_boundary() {
        assert!(validate_stream_text_field("prompt-ref", "r-123", 512).is_ok());
        // Exactly max_len is allowed; one over is rejected.
        assert!(validate_stream_text_field("model", "abcd", 4).is_ok());
        assert_eq!(
            validate_stream_text_field("model", "abcde", 4),
            Err("[blocked: invalid stream model]".to_string())
        );
    }

    #[test]
    fn stream_text_field_rejects_empty_and_whitespace_only() {
        assert_eq!(
            validate_stream_text_field("prompt-ref", "", 512),
            Err("[blocked: stream prompt-ref is empty]".to_string())
        );
        assert_eq!(
            validate_stream_text_field("prompt-ref", "   ", 512),
            Err("[blocked: stream prompt-ref is empty]".to_string())
        );
    }

    #[test]
    fn stream_text_field_rejects_surrounding_whitespace_nonascii_and_control() {
        // Surrounding whitespace: value.trim() != value.
        assert_eq!(
            validate_stream_text_field("model", " gpt-4", 512),
            Err("[blocked: invalid stream model]".to_string())
        );
        // Non-ascii.
        assert_eq!(
            validate_stream_text_field("model", "café", 512),
            Err("[blocked: invalid stream model]".to_string())
        );
        // Interior control character (tab is not trimmed away from the middle).
        assert_eq!(
            validate_stream_text_field("model", "a\tb", 512),
            Err("[blocked: invalid stream model]".to_string())
        );
    }

    // ── validate_stream_response_metadata ───────────────────────────────────

    fn meta(prompt_ref: &str, model: &str, provider_family: &str) -> StreamResponseMetadata {
        StreamResponseMetadata {
            prompt_ref: prompt_ref.to_string(),
            model: model.to_string(),
            provider_family: provider_family.to_string(),
            last_sequence: None,
        }
    }

    #[test]
    fn stream_metadata_accepts_valid_shape() {
        assert!(validate_stream_response_metadata(&meta("r-1", "gpt-4", "openai")).is_ok());
    }

    #[test]
    fn stream_metadata_rejects_empty_prompt_ref_and_model() {
        assert_eq!(
            validate_stream_response_metadata(&meta("", "gpt-4", "openai")),
            Err("[blocked: stream prompt-ref is empty]".to_string())
        );
        assert_eq!(
            validate_stream_response_metadata(&meta("r-1", "", "openai")),
            Err("[blocked: stream model is empty]".to_string())
        );
    }

    #[test]
    fn stream_metadata_rejects_oversize_prompt_ref() {
        // prompt-ref cap is 512.
        let long = "a".repeat(513);
        assert_eq!(
            validate_stream_response_metadata(&meta(&long, "gpt-4", "openai")),
            Err("[blocked: invalid stream prompt-ref]".to_string())
        );
    }

    #[test]
    fn stream_metadata_rejects_invalid_provider_family() {
        // Uppercase: normalized differs from the trimmed original.
        assert_eq!(
            validate_stream_response_metadata(&meta("r-1", "gpt-4", "OpenAI")),
            Err("[blocked: invalid stream provider-family]".to_string())
        );
        // An unsafe token (interior space) fails is_safe_provider_token.
        assert_eq!(
            validate_stream_response_metadata(&meta("r-1", "gpt-4", "open ai")),
            Err("[blocked: invalid stream provider-family]".to_string())
        );
        // Empty provider-family is unsafe too.
        assert_eq!(
            validate_stream_response_metadata(&meta("r-1", "gpt-4", "")),
            Err("[blocked: invalid stream provider-family]".to_string())
        );
    }

    // ── model_error_body_preview ────────────────────────────────────────────

    #[test]
    fn error_body_preview_passes_short_utf8_through_unchanged() {
        assert_eq!(model_error_body_preview(b"boom"), "boom");
        assert_eq!(model_error_body_preview(b""), "");
    }

    #[test]
    fn error_body_preview_lossily_decodes_non_utf8() {
        let bytes = [0xff_u8, 0xfe, 0x41]; // invalid lead bytes + 'A'
        assert_eq!(
            model_error_body_preview(&bytes),
            String::from_utf8_lossy(&bytes).to_string()
        );
    }

    #[test]
    fn error_body_preview_truncates_oversize_body_with_marker() {
        const MAX: usize = 8 * 1024;
        // Exactly at the cap: returned whole, no truncation marker.
        let at_cap = vec![b'a'; MAX];
        assert_eq!(model_error_body_preview(&at_cap), "a".repeat(MAX));

        // One over the cap: prefix + truncation marker.
        let over = vec![b'a'; MAX + 100];
        let preview = model_error_body_preview(&over);
        let expected = format!(
            "{}\n[truncated: model-bridge error body exceeded {MAX} bytes]",
            "a".repeat(MAX)
        );
        assert_eq!(preview, expected);
    }
}
