// TractorNativeBindings — host-side implementation of `tractor-bridge` WIT interface.
//
// Mirrors `WasiImports` from packages/tractor/src/lib/wasi-imports.ts.
//
// Implements traits generated by `wasmtime::component::bindgen!` in `plugin_host.rs`:
//   - `host::plugin::types::Host`          — empty (shared types interface, no methods)
//   - `host::plugin::tractor_bridge::Host` — CRDT/storage/telemetry host functions
//   - `host::plugin::model_bridge::Host`    — host-proxied HTTP completion boundary
//
// Return types use the WIT `result<T, plugin-error>` directly — no outer wasmtime::Result.

use crate::host::plugin_host::host::plugin::{
    model_bridge::{Host as ModelBridgeHost, StreamResponseMetadata, StreamResponseResult},
    tractor_bridge::Host as TractorBridgeHost,
    types::{Host as TypesHost, IdentityInfo, PluginError},
};
use crate::host::plugin_registry::PluginRegistry;
use crate::sync::NativeSync;
use crate::telemetry::TelemetryBus;
use std::io::Read as _;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ModelRoute {
    provider: String,
    base_url: String,
    path: String,
}

/// The handles a plugin's host-call needs to reach OTHER loaded plugins: the shared
/// capability registry (who is loaded + what they serve) and the event router (how a
/// dispatch reaches them). Cloned into every `TractorNativeBindings` at load, exactly
/// like `effect_policy` / `model_route` — so the cross-plugin host path reads `&self`,
/// never a global. All fields are `Arc`-backed clones sharing the runtime's live state.
///
/// This is the seam that unblocks two host features that both needed "reach another
/// loaded plugin" and were stalled on the same missing registry: the agent leg (#6,
/// `capability-tools` list/invoke) and `get_plugin_api` (was a STUB).
#[derive(Clone)]
pub struct CrossPluginAccess {
    /// Who is loaded + what each declares (`provides`/`subscribes`). Source of truth
    /// for tool eligibility; a revoked plugin never loads → never here → not listable.
    pub registry: PluginRegistry,
    /// event-name → subscriber-ids, for enumerating + routing a `<key>:dispatch`.
    pub event_router: crate::EventRouter,
    /// plugin-id → runner channel, the sinks `deliver_via_router` sends to.
    pub plugin_channels: crate::PluginChannels,
}

/// Resolve the base URL a liveness probe should ping for `provider`, reusing the
/// SAME canonical resolution the completion path uses (`ModelRoute::for_provider`
/// — known-provider map, anthropic/openai families, MODEL_BASE_URL override, and
/// the localhost floor). This is the sidecar's single seam onto the provider→URL
/// map; the raw `known_provider_base_url` stays private so there is one source of
/// truth for "where is my provider" across completion and liveness.
pub(crate) fn provider_base_url_for_liveness(provider: &str) -> String {
    ModelRoute::for_provider(provider.trim().to_ascii_lowercase()).base_url
}

/// Host-side implementation of the `tractor-bridge` WIT interface.
///
/// Holds references to NativeSync (storage) and TelemetryBus so plugin
/// calls are forwarded to the actual Tractor infrastructure.
pub struct TractorNativeBindings {
    pub plugin_id: String,
    pub sync: NativeSync,
    pub telemetry: TelemetryBus,
    /// Effect-dispatch policy (shell allowlist + fs root) resolved from env ONCE
    /// at PluginHost boot and cloned in here at load, so the per-call effect path
    /// reads &self, never std::env::var.
    pub(crate) effect_policy: crate::host::host_effects_bridge::HostEffectPolicy,
    /// The expected model ROUTE (provider + base-url + path) guardrail, resolved
    /// from the routing env vars (MODEL_PROVIDER / MODEL_BASE_URL)
    /// ONCE at boot. Read per model POST to validate the guest's requested route —
    /// no per-request env read. NOTE: only routing config lives here; the
    /// per-request API-key SECRETS stay in env (12-factor), read at send time
    /// keyed off the provider.
    pub(crate) model_route: ModelRoute,
    /// The OPTIONAL fallback route, resolved from MODEL_FALLBACK_PROVIDER once at
    /// boot (None when unset). When set, the model-POST guardrail accepts a request
    /// matching EITHER the primary route or this one — the host-side half of the
    /// guest's documented MODEL_FALLBACK_PROVIDER retry. None → single-route
    /// behavior, byte-identical to before this field existed.
    pub(crate) fallback_route: Option<ModelRoute>,
    /// The plugin's capability grant: the permissions it DECLARED in its manifest
    /// plus the host security mode. `request_permission` consults this to answer
    /// honestly ("did this plugin declare this capability?") instead of always
    /// granting. Resolved at load from the manifest.
    pub(crate) permission_grant: PermissionGrant,
    /// The sovereign trusted-plugins allowlist resolved ONCE per load (fs ∩ node,
    /// deny-dominates — B) and cloned in, so the per-spawn host-shell gate reads
    /// `&self` instead of a live `.refarm/config.json` read on every spawn. The SAME
    /// set the load gate (`trusted_to_load`) used, so load and shell can never disagree
    /// — one source of truth, node-aware for free. None = permissive (not configured);
    /// Some(set): `*` = all, empty = deny-all.
    pub(crate) trusted_plugins: Option<std::collections::HashSet<String>>,
    /// The shared registry of LOADED plugins' capability profiles + a router handle,
    /// so a host-call from THIS plugin can list/invoke OTHER loaded plugins' verbs
    /// (the agent leg #6 `capability-tools`) and resolve a named API (`get_plugin_api`).
    /// `None` for test-constructed bindings / hosts wired without a registry — those
    /// paths keep the pre-registry behavior (empty tool list, `get_plugin_api` NotFound).
    pub(crate) cross_plugin: Option<crate::host::wasi_bridge::CrossPluginAccess>,
}

/// A plugin's capability grant for the `request-permission` host export.
///
/// This is the honest minimal grant the architecture already implies: the
/// manifest DECLARES the permissions a plugin needs, so a request for a declared
/// permission is granted and an undeclared one is denied. Gated by `SecurityMode`:
/// in `None`/`Permissive` (dev) it grants regardless (mirroring the effect
/// bridge's permissive-when-unconfigured default); in `Strict` it enforces the
/// manifest declaration. NOTE: the WIT calls this a "user-facing permission
/// prompt", but the host has no prompt UI — the honest behavior is a static
/// manifest-declared allow/deny, which this documents.
#[derive(Debug, Clone)]
pub(crate) struct PermissionGrant {
    declared: std::collections::HashSet<String>,
    security_mode: crate::trust::SecurityMode,
}

impl PermissionGrant {
    pub(crate) fn new(
        declared: std::collections::HashSet<String>,
        security_mode: crate::trust::SecurityMode,
    ) -> Self {
        Self { declared, security_mode }
    }

    /// Permissive default (no declared permissions, dev security mode) — grants
    /// everything, matching the pre-wiring behavior. Used by test-constructed
    /// bindings and the host-effects load path.
    pub(crate) fn permissive() -> Self {
        Self {
            declared: std::collections::HashSet::new(),
            security_mode: crate::trust::SecurityMode::None,
        }
    }

    /// Decide whether `capability` is granted. Only `Strict` enforces the
    /// manifest declaration; dev modes grant regardless. Consulted both by
    /// request_permission (guest-cooperative advisory) and, for interfaces the
    /// host can gate at the Linker, by the load path to pick a capability-scoped
    /// linker — turning the advisory into a real enforcement boundary.
    pub(crate) fn grants(&self, capability: &str) -> bool {
        match self.security_mode {
            crate::trust::SecurityMode::Strict => self.declared.contains(capability),
            crate::trust::SecurityMode::Permissive | crate::trust::SecurityMode::None => true,
        }
    }

    /// Typed grant check over the canonical vocabulary. Callers that know the
    /// capability at compile time (the host-fs/host-shell/linker gates) use this
    /// so the permission string can never be a typo — the enum is the single
    /// source of truth. Delegates to `grants` on the wire string.
    pub(crate) fn grants_permission(&self, permission: crate::host::permission::Permission) -> bool {
        self.grants(permission.as_str())
    }

    /// Test constructor: a Strict grant declaring exactly `caps`.
    #[cfg(test)]
    pub(crate) fn strict_declaring(caps: &[&str]) -> Self {
        Self {
            declared: caps.iter().map(|c| c.to_string()).collect(),
            security_mode: crate::trust::SecurityMode::Strict,
        }
    }
}

#[cfg(test)]
mod permission_grant_tests {
    use super::PermissionGrant;

    #[test]
    fn strict_grants_only_declared_capabilities() {
        let grant = PermissionGrant::strict_declaring(&["fs:read", "shell:spawn"]);
        assert!(grant.grants("fs:read"), "declared capability is granted");
        assert!(grant.grants("shell:spawn"), "declared capability is granted");
        assert!(
            !grant.grants("network:outbound"),
            "an UNdeclared capability must be denied in Strict mode"
        );
        assert!(!grant.grants("fs:write"), "undeclared capability denied");
    }

    #[test]
    fn dev_modes_grant_regardless_of_declaration() {
        // Permissive default (no declarations, dev mode) grants everything —
        // matching the pre-wiring behavior so dev/test isn't broken.
        let grant = PermissionGrant::permissive();
        assert!(grant.grants("anything"));
        assert!(grant.grants("network:outbound"));
    }
}

impl TractorNativeBindings {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        plugin_id: impl Into<String>,
        sync: NativeSync,
        telemetry: TelemetryBus,
        effect_policy: crate::host::host_effects_bridge::HostEffectPolicy,
        model_route: ModelRoute,
        fallback_route: Option<ModelRoute>,
        permission_grant: PermissionGrant,
        trusted_plugins: Option<std::collections::HashSet<String>>,
        cross_plugin: Option<CrossPluginAccess>,
    ) -> Self {
        Self {
            plugin_id: plugin_id.into(),
            sync,
            telemetry,
            effect_policy,
            model_route,
            fallback_route,
            permission_grant,
            trusted_plugins,
            cross_plugin,
        }
    }
}

// ── types::Host ───────────────────────────────────────────────────────────────
//
// The `types` interface defines shared types (plugin-error, identity-info, etc.)
// but contains no functions. The generated `Host` trait has no methods.
impl TypesHost for TractorNativeBindings {}

// ── tractor_bridge::Host ──────────────────────────────────────────────────────
//
// Each method corresponds to one WIT function in `tractor-bridge`.
// Return type is `Result<T, PluginError>` — the WIT result directly.

#[wasmtime::component::__internal::async_trait]
impl TractorBridgeHost for TractorNativeBindings {
    /// Store (upsert) a JSON-LD node into the sovereign graph.
    async fn store_node(&mut self, node_json: String) -> Result<String, PluginError> {
        let value: serde_json::Value = match serde_json::from_str(&node_json) {
            Ok(v) => v,
            Err(e) => return Err(PluginError::InvalidSchema(e.to_string())),
        };

        let id = value["@id"]
            .as_str()
            .or_else(|| value["id"].as_str())
            .unwrap_or("urn:unknown")
            .to_string();

        let type_ = value["@type"]
            .as_str()
            .or_else(|| value["type"].as_str())
            .unwrap_or("Unknown")
            .to_string();

        self.sync
            .store_node(&id, &type_, None, &node_json, Some(&self.plugin_id))
            .map_err(|e| PluginError::Internal(e.to_string()))?;

        self.telemetry.emit_named(
            "plugin:store_node",
            Some(self.plugin_id.clone()),
            Some(serde_json::json!({ "nodeId": id, "type": type_ })),
        );

        Ok(id)
    }

    /// Retrieve a previously stored node by ID.
    async fn get_node(&mut self, id: String) -> Result<String, PluginError> {
        match self.sync.get_node(&id) {
            Ok(Some(payload)) => Ok(payload),
            Ok(None) => Err(PluginError::NotFound(id)),
            Err(e) => Err(PluginError::Internal(e.to_string())),
        }
    }

    /// Query nodes by @type, returning up to `limit` results.
    async fn query_nodes(
        &mut self,
        node_type: String,
        limit: u32,
    ) -> Result<Vec<String>, PluginError> {
        self.sync
            .query_nodes(&node_type)
            .map_err(|e| PluginError::Internal(e.to_string()))
            .map(|rows| {
                rows.into_iter()
                    .take(limit as usize)
                    .map(|r| r.payload)
                    .collect()
            })
    }

    /// Decide whether the plugin may use `capability`. The WIT names this a
    /// "user-facing permission prompt", but the host has no prompt UI — the honest
    /// behavior is a static grant from the plugin's manifest-declared permissions
    /// (see PermissionGrant): in Strict mode a declared capability is granted and
    /// an undeclared one denied; dev modes grant regardless. A denial is emitted
    /// as telemetry (a security-relevant event) rather than silently returned.
    async fn request_permission(&mut self, capability: String, reason: String) -> bool {
        let granted = self.permission_grant.grants(&capability);
        if !granted {
            self.telemetry.emit_named(
                "permission:denied",
                Some(self.plugin_id.clone()),
                Some(serde_json::json!({ "capability": capability, "reason": reason })),
            );
        }
        granted
    }

    /// Return the current user's identity information.
    ///
    /// STUB: the tractor host has no identity/user/session source yet, so this
    /// always reports an anonymous ephemeral guest. A guest that branches on
    /// `storage_tier` is told a fixed value — do not treat it as authoritative
    /// until a real identity source is wired.
    async fn get_identity(&mut self) -> Result<IdentityInfo, PluginError> {
        Ok(IdentityInfo {
            identity_type: "guest".to_string(),
            storage_tier: "ephemeral".to_string(),
            identifier: "".to_string(),
        })
    }

    /// Discover a plugin that provides a named API (SPI pattern).
    ///
    /// Resolves against the shared plugin registry (the same one that powers the
    /// agent leg's `capability-tools`): a loaded plugin that declares `api:<name>`
    /// in its `provides` is returned by id. Before the registry existed this was a
    /// STUB that always returned `NotFound`; that fallback remains when no registry
    /// is wired (test bindings), so behavior only ever GAINS resolution, never loses
    /// it. Only LOADED plugins resolve — a revoked/unloaded provider is invisible.
    async fn get_plugin_api(&mut self, api_name: String) -> Result<String, PluginError> {
        if let Some(cross) = self.cross_plugin.as_ref() {
            if let Some(plugin_id) = cross.registry.plugin_providing_api(&api_name) {
                return Ok(plugin_id);
            }
        }
        Err(PluginError::NotFound(format!(
            "no plugin provides api: {api_name}"
        )))
    }

    /// Call a verb on another loaded plugin, by its id (the SPI call leg, pairs with
    /// `get_plugin_api` discovery). Routes through the SAME shared dispatch the agent
    /// leg's tool-call uses (`dispatch_to_plugin`) — one protocol, addressed by verb,
    /// no duplication. The callee runs under ITS OWN grant; a revoked/unloaded target
    /// is absent from the registry so the dispatch finds no channel and fails honestly.
    async fn call_plugin(
        &mut self,
        plugin_id: String,
        verb: String,
        input_json: String,
    ) -> Result<String, PluginError> {
        let Some(cross) = self.cross_plugin.as_ref() else {
            return Err(PluginError::NotFound(
                "cross-plugin unavailable: no registry wired".to_string(),
            ));
        };
        let input = if input_json.trim().is_empty() {
            serde_json::json!({})
        } else {
            serde_json::from_str(&input_json).map_err(|e| PluginError::InvalidSchema(e.to_string()))?
        };
        // A plugin_id carries no routing key; derive it the sidecar's canonical way
        // (last path segment): `@refarm.dev/quality` → `quality` for `quality:dispatch`.
        let plugin_key = plugin_id.rsplit('/').next().unwrap_or(&plugin_id).to_string();
        crate::host::host_effects_bridge::dispatch_to_plugin(
            cross,
            &self.sync,
            &self.telemetry,
            &plugin_id,
            &plugin_key,
            &verb,
            input,
        )
        .await
        .map_err(PluginError::Internal)
    }

    /// Emit a telemetry event from the plugin.
    async fn emit_telemetry(&mut self, event: String, payload: Option<String>) {
        let payload_val = payload.and_then(|p| serde_json::from_str(&p).ok());
        self.telemetry
            .emit_named(event, Some(self.plugin_id.clone()), payload_val);
    }
}

// ── model_bridge::Host ───────────────────────────────────────────────────────

#[wasmtime::component::__internal::async_trait]
impl ModelBridgeHost for TractorNativeBindings {
    async fn complete_http(
        &mut self,
        provider: String,
        base_url: String,
        path: String,
        headers: Vec<(String, String)>,
        body: Vec<u8>,
    ) -> Result<Vec<u8>, String> {
        model_complete_http(
            &provider,
            &base_url,
            &path,
            &headers,
            &body,
            &self.model_route,
            self.fallback_route.as_ref(),
        )
    }

    /// Streaming contract compatibility path.
    ///
    /// This preserves the new WIT boundary while final response semantics are
    /// still under design. It reads response bytes through the generic SSE
    /// reader seam and persists text chunks as complete SSE frames arrive.
    async fn complete_http_stream(
        &mut self,
        provider: String,
        base_url: String,
        path: String,
        headers: Vec<(String, String)>,
        body: Vec<u8>,
        stream_metadata: StreamResponseMetadata,
    ) -> Result<StreamResponseResult, String> {
        validate_stream_response_metadata(&stream_metadata)?;
        let resp = send_model_http_post(
            &provider,
            &base_url,
            &path,
            &headers,
            &body,
            &self.model_route,
            self.fallback_route.as_ref(),
        )?;
        let (final_body, last_sequence, stored_chunks) = store_stream_agent_response_chunks_from_reader(
            &self.sync,
            &self.plugin_id,
            &stream_metadata,
            resp.into_reader(),
            MAX_MODEL_RESPONSE_BODY_LEN,
        )?;
        Ok(buffered_stream_response_result(
            final_body,
            last_sequence,
            stored_chunks,
        ))
    }
}

fn buffered_stream_response_result(
    final_body: Vec<u8>,
    last_sequence: Option<u32>,
    stored_chunks: u32,
) -> StreamResponseResult {
    StreamResponseResult {
        final_body,
        last_sequence,
        stored_chunks,
    }
}

fn validate_stream_response_metadata(metadata: &StreamResponseMetadata) -> Result<(), String> {
    validate_stream_text_field("prompt-ref", &metadata.prompt_ref, 512)?;
    validate_stream_text_field("model", &metadata.model, 256)?;
    let provider_family = normalize_provider_name(&metadata.provider_family);
    if provider_family != metadata.provider_family.trim() || !is_safe_provider_token(&provider_family) {
        return Err("[blocked: invalid stream provider-family]".to_string());
    }
    Ok(())
}

fn validate_stream_text_field(label: &str, value: &str, max_len: usize) -> Result<(), String> {
    if value.trim().is_empty() {
        return Err(format!("[blocked: stream {label} is empty]"));
    }
    if value.trim() != value || value.len() > max_len || !value.is_ascii() || value.chars().any(|c| c.is_control()) {
        return Err(format!("[blocked: invalid stream {label}]"));
    }
    Ok(())
}

fn model_complete_http(
    provider: &str,
    base_url: &str,
    path: &str,
    headers: &[(String, String)],
    body: &[u8],
    expected: &ModelRoute,
    fallback: Option<&ModelRoute>,
) -> Result<Vec<u8>, String> {
    let resp = send_model_http_post(provider, base_url, path, headers, body, expected, fallback)?;
    read_response_bytes(resp)
}

/// Accept a request that matches the primary route OR the optional fallback route.
/// Reuses the single-route `enforce_model_route` verbatim for each — every existing
/// validation branch is untouched. When there is no fallback (the common case), the
/// primary error is returned unchanged, so an unset MODEL_FALLBACK_PROVIDER behaves
/// byte-identically to a single-route host. On a fallback mismatch the primary
/// error surfaces (chosen to keep the no-fallback path's error string identical).
fn enforce_model_route_any(
    provider: &str,
    base_url: &str,
    path: &str,
    primary: &ModelRoute,
    fallback: Option<&ModelRoute>,
) -> Result<(), String> {
    match enforce_model_route(provider, base_url, path, primary) {
        Ok(()) => Ok(()),
        Err(primary_err) => match fallback {
            Some(fb) => enforce_model_route(provider, base_url, path, fb),
            None => Err(primary_err),
        },
    }
}

fn send_model_http_post(
    provider: &str,
    base_url: &str,
    path: &str,
    headers: &[(String, String)],
    body: &[u8],
    expected: &ModelRoute,
    fallback: Option<&ModelRoute>,
) -> Result<ureq::Response, String> {
    enforce_model_route_any(provider, base_url, path, expected, fallback)?;
    enforce_model_request_body(body)?;
    let provider = normalize_provider_name(provider);

    let url = join_base_url_and_path(base_url, path);
    let mut req = ureq::post(&url);

    for (name, value) in sanitized_plugin_headers(headers) {
        req = req.set(name, value);
    }

    if use_anthropic_auth(&provider) {
        let key = anthropic_api_key_from_env()?;
        req = req.set("x-api-key", &key);
    } else if use_openai_codex_auth(&provider) {
        let Some(header) = bearer_key_for_provider(&provider)? else {
            return Err("OPENAI_CODEX_ACCESS_TOKEN not set".to_string());
        };
        let account_id = openai_codex_account_id_from_env()?;
        req = req
            .set("authorization", &header)
            .set("chatgpt-account-id", &account_id)
            .set("originator", "refarm")
            .set("OpenAI-Beta", "responses=experimental");
    } else if let Some(header) = bearer_key_for_provider(&provider)? {
        req = req.set("authorization", &header);
    }

    match req.send_bytes(body) {
        Ok(resp) => Ok(resp),
        Err(ureq::Error::Status(code, resp)) => {
            let bytes = read_response_bytes(resp)?;
            Err(format!("HTTP {code}: {}", model_error_body_preview(&bytes)))
        }
        Err(e) => Err(format!("http error: {e}")),
    }
}

fn model_error_body_preview(bytes: &[u8]) -> String {
    const MAX_MODEL_ERROR_PREVIEW_LEN: usize = 8 * 1024;

    if bytes.len() <= MAX_MODEL_ERROR_PREVIEW_LEN {
        return String::from_utf8_lossy(bytes).to_string();
    }

    let prefix = String::from_utf8_lossy(&bytes[..MAX_MODEL_ERROR_PREVIEW_LEN]);
    format!(
        "{prefix}\n[truncated: model-bridge error body exceeded {MAX_MODEL_ERROR_PREVIEW_LEN} bytes]"
    )
}

fn use_anthropic_auth(provider: &str) -> bool {
    provider.trim().eq_ignore_ascii_case("anthropic")
}

fn use_openai_codex_auth(provider: &str) -> bool {
    provider.trim().eq_ignore_ascii_case("openai-codex")
}

// Registry of known providers that need no MODEL_BASE_URL to work.
fn known_provider_base_url(provider: &str) -> Option<&'static str> {
    match provider.trim().to_ascii_lowercase().as_str() {
        "openai-codex" => Some("https://chatgpt.com"),
        "groq"       => Some("https://api.groq.com"),
        "mistral"    => Some("https://api.mistral.ai"),
        "xai"        => Some("https://api.x.ai"),
        "deepseek"   => Some("https://api.deepseek.com"),
        "together"   => Some("https://api.together.xyz"),
        "openrouter" => Some("https://openrouter.ai"),
        "gemini"     => Some("https://generativelanguage.googleapis.com"),
        _            => None,
    }
}

// Some providers diverge from the standard /v1/chat/completions path.
fn known_provider_api_path(provider: &str) -> &'static str {
    match provider.trim().to_ascii_lowercase().as_str() {
        "openai-codex" => "/backend-api/codex/responses",
        "groq"       => "/openai/v1/chat/completions",
        "openrouter" => "/api/v1/chat/completions",
        "gemini"     => "/v1beta/openai/chat/completions",
        _            => "/v1/chat/completions",
    }
}

// Derive a Bearer auth header for any non-Anthropic provider.
// Resolution order: {PROVIDER_UPPER}_API_KEY → OPENAI_API_KEY (generic compat) → None (ollama).
fn bearer_key_for_provider(provider: &str) -> Result<Option<String>, String> {
    let normalized = normalize_provider_name(provider);

    let primary_env_var = if use_openai_codex_auth(&normalized) {
        "OPENAI_CODEX_ACCESS_TOKEN".to_string()
    } else if is_openai_provider_family(&normalized) {
        "OPENAI_API_KEY".to_string()
    } else {
        format!("{}_API_KEY", normalized.to_ascii_uppercase().replace('-', "_"))
    };

    let allow_openai_api_key_fallback =
        !use_openai_codex_auth(&normalized) && primary_env_var != "OPENAI_API_KEY";
    let (raw_key, used_var): (String, String) = match std::env::var(&primary_env_var) {
        Ok(k) => (k, primary_env_var),
        Err(_) if allow_openai_api_key_fallback => match std::env::var("OPENAI_API_KEY") {
            Ok(k) => (k, "OPENAI_API_KEY".to_string()),
            Err(_) => return Ok(None),
        },
        Err(_) => return Ok(None),
    };

    let key = sanitize_auth_token_for_header(&raw_key)
        .ok_or_else(|| format!("[blocked: invalid {used_var}]"))?;
    Ok(Some(format!("Bearer {key}")))
}

fn openai_codex_account_id_from_env() -> Result<String, String> {
    if let Ok(account_id) = std::env::var("OPENAI_CODEX_ACCOUNT_ID") {
        return sanitize_auth_token_for_header(&account_id)
            .ok_or_else(|| "[blocked: invalid OPENAI_CODEX_ACCOUNT_ID]".to_string());
    }
    let token = std::env::var("OPENAI_CODEX_ACCESS_TOKEN")
        .map_err(|_| "OPENAI_CODEX_ACCESS_TOKEN not set".to_string())?;
    extract_chatgpt_account_id_from_jwt(&token)
        .ok_or_else(|| "[blocked: invalid OPENAI_CODEX_ACCESS_TOKEN account claim]".to_string())
}

fn extract_chatgpt_account_id_from_jwt(token: &str) -> Option<String> {
    let payload = token.split('.').nth(1)?;
    let bytes = decode_base64url(payload)?;
    let value: serde_json::Value = serde_json::from_slice(&bytes).ok()?;
    let account_id = value
        .get("https://api.openai.com/auth")?
        .get("chatgpt_account_id")?
        .as_str()?;
    sanitize_auth_token_for_header(account_id)
}

fn decode_base64url(value: &str) -> Option<Vec<u8>> {
    fn sextet(byte: u8) -> Option<u8> {
        match byte {
            b'A'..=b'Z' => Some(byte - b'A'),
            b'a'..=b'z' => Some(byte - b'a' + 26),
            b'0'..=b'9' => Some(byte - b'0' + 52),
            b'-' => Some(62),
            b'_' => Some(63),
            b'=' => None,
            _ => None,
        }
    }

    let mut out = Vec::with_capacity(value.len() * 3 / 4);
    let mut buffer = 0u32;
    let mut bits = 0u8;
    for byte in value.bytes() {
        let Some(next) = sextet(byte) else {
            if byte == b'=' {
                break;
            }
            return None;
        };
        buffer = (buffer << 6) | u32::from(next);
        bits += 6;
        if bits >= 8 {
            bits -= 8;
            out.push(((buffer >> bits) & 0xff) as u8);
        }
    }
    Some(out)
}

fn enforce_model_request_body(body: &[u8]) -> Result<(), String> {
    const MAX_MODEL_REQUEST_BODY_LEN: usize = 1024 * 1024;
    if body.len() > MAX_MODEL_REQUEST_BODY_LEN {
        return Err("[blocked: model-bridge body too large]".to_string());
    }
    Ok(())
}

fn is_openai_provider_family(provider: &str) -> bool {
    let provider = provider.trim().to_ascii_lowercase();
    provider == "openai" || provider.starts_with("openai-")
}

fn sanitize_auth_token_for_header(token: &str) -> Option<String> {
    const MAX_AUTH_TOKEN_LEN: usize = 4096;
    let trimmed = token.trim();
    if trimmed.is_empty()
        || trimmed != token
        || trimmed.len() > MAX_AUTH_TOKEN_LEN
        || !trimmed.is_ascii()
        || trimmed.chars().any(|c| c.is_control())
        || trimmed.chars().any(|c| c.is_whitespace())
    {
        return None;
    }
    Some(trimmed.to_string())
}

fn anthropic_api_key_from_env() -> Result<String, String> {
    let key = std::env::var("ANTHROPIC_API_KEY")
        .map_err(|_| "ANTHROPIC_API_KEY not set".to_string())?;
    sanitize_auth_token_for_header(&key)
        .ok_or_else(|| "[blocked: invalid ANTHROPIC_API_KEY]".to_string())
}

fn provider_name_from_env() -> String {
    for key in ["MODEL_PROVIDER", "MODEL_DEFAULT_PROVIDER"] {
        if let Some(provider) = normalized_provider_from_env(key) {
            return provider;
        }
    }
    "ollama".to_string()
}

fn normalized_provider_from_env(key: &str) -> Option<String> {
    std::env::var(key)
        .ok()
        .map(|v| normalize_provider_name(&v))
        .filter(|v| !v.is_empty() && is_safe_provider_token(v))
}

fn normalize_provider_name(value: &str) -> String {
    value.trim().to_ascii_lowercase()
}

fn is_safe_provider_token(value: &str) -> bool {
    const MAX_PROVIDER_TOKEN_LEN: usize = 64;
    !value.is_empty()
        && value.len() <= MAX_PROVIDER_TOKEN_LEN
        && value
            .bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-' || b == b'_')
}

impl ModelRoute {
    /// Resolve the expected model route (provider + base-url + path) from the
    /// routing env vars ONCE at boot. This is the ONLY place the routing vars
    /// (MODEL_PROVIDER / MODEL_DEFAULT_PROVIDER, MODEL_BASE_URL) are read;
    /// the resolved route then rides on TractorNativeBindings and the per-request
    /// path validates against it without touching env. Secrets (API keys) are NOT
    /// part of this — they stay in env, read at send time keyed off the provider.
    pub(crate) fn from_env() -> Self {
        Self::for_provider(provider_name_from_env())
    }

    /// Build the route for a specific provider name, using the same per-provider
    /// resolution as `from_env` (anthropic hardcode, else known base/path or the
    /// openai-family / localhost floor, honoring MODEL_BASE_URL first). Shared by
    /// `from_env` and `fallback_from_env` so the primary and fallback routes are
    /// resolved by identical logic — the accepted fallback route equals exactly
    /// what the guest requests for that provider, nothing more.
    fn for_provider(provider: String) -> Self {
        if provider == "anthropic" {
            return ModelRoute {
                provider,
                base_url: "https://api.anthropic.com".to_string(),
                path: "/v1/messages".to_string(),
            };
        }

        let path = known_provider_api_path(&provider).to_string();
        let base_url = model_base_url_from_env().unwrap_or_else(|| {
            if let Some(url) = known_provider_base_url(&provider) {
                url.to_string()
            } else if is_openai_provider_family(&provider) {
                "https://api.openai.com".to_string()
            } else {
                "http://localhost:11434".to_string()
            }
        });

        ModelRoute { provider, base_url, path }
    }

    /// Resolve the OPTIONAL fallback route from MODEL_FALLBACK_PROVIDER, once at
    /// boot alongside `from_env`. Returns None when unset/empty/unsafe — and when
    /// None, the guardrail behaves byte-identically to a single-route host.
    ///
    /// The token is gated by `is_safe_provider_token`, which only admits
    /// `[a-z0-9_-]`. This keeps host and guest in lockstep for the routing that
    /// matters: the guest reads MODEL_FALLBACK_PROVIDER raw (runtime/wasm_flow.rs)
    /// and its openai-compat base_url/path arms (provider_config.rs, request_path.rs)
    /// are lowercase-only, so `for_provider` here selects the SAME branch off the
    /// SAME lowercase string. A non-lowercase spelling (e.g. "GROQ") is admitted by
    /// neither side's known-provider arms — the guest would fall through to the
    /// localhost default while the host returns None (no fallback route). That
    /// divergence fails CLOSED (the fallback simply does not activate) and only for
    /// a malformed provider token, so it is rejected here rather than routed.
    /// MODEL_FALLBACK_MODEL_ID is not read: model id does not change path/base_url.
    pub(crate) fn fallback_from_env() -> Option<ModelRoute> {
        let provider = std::env::var("MODEL_FALLBACK_PROVIDER").ok()?;
        let provider = provider.trim();
        if provider.is_empty() || !is_safe_provider_token(provider) {
            return None;
        }
        Some(Self::for_provider(provider.to_string()))
    }
}

impl Default for ModelRoute {
    /// The env-unset default route (ollama on localhost) — what from_env resolves
    /// to with no routing vars set. Used by test-constructed bindings.
    fn default() -> Self {
        let provider = "ollama".to_string();
        ModelRoute {
            path: known_provider_api_path(&provider).to_string(),
            base_url: "http://localhost:11434".to_string(),
            provider,
        }
    }
}

#[cfg(test)]
impl ModelRoute {
    /// Explicit route (tests) — inject provider/base-url/path directly instead of
    /// steering the resolution via process env.
    pub(crate) fn for_test(provider: &str, base_url: &str, path: &str) -> Self {
        ModelRoute {
            provider: provider.to_string(),
            base_url: base_url.to_string(),
            path: path.to_string(),
        }
    }
}

fn model_base_url_from_env() -> Option<String> {
    let value = std::env::var("MODEL_BASE_URL").ok()?;
    let trimmed = value.trim();
    if trimmed.is_empty() {
        None
    } else {
        Some(trimmed.to_string())
    }
}

fn enforce_model_route(
    provider: &str,
    base_url: &str,
    path: &str,
    expected: &ModelRoute,
) -> Result<(), String> {
    const MAX_BASE_URL_LEN: usize = 2048;
    const MAX_PATH_LEN: usize = 2048;

    if provider.chars().any(|c| c.is_control()) || expected.provider.chars().any(|c| c.is_control()) {
        return Err("[blocked: model-bridge provider contains control characters]".to_string());
    }
    if base_url.chars().any(|c| c.is_control()) || expected.base_url.chars().any(|c| c.is_control()) {
        return Err("[blocked: model-bridge base_url contains control characters]".to_string());
    }
    if path.chars().any(|c| c.is_control()) || expected.path.chars().any(|c| c.is_control()) {
        return Err("[blocked: model-bridge path contains control characters]".to_string());
    }
    if !path.is_ascii() || !expected.path.is_ascii() {
        return Err("[blocked: model-bridge path must be ascii]".to_string());
    }
    if path.trim().is_empty() || expected.path.trim().is_empty() {
        return Err("[blocked: model-bridge path must be non-empty]".to_string());
    }
    if path.trim() != path || expected.path.trim() != expected.path {
        return Err("[blocked: model-bridge path contains surrounding whitespace]".to_string());
    }
    if path.chars().any(|c| c.is_whitespace()) || expected.path.chars().any(|c| c.is_whitespace()) {
        return Err("[blocked: model-bridge path must not contain whitespace]".to_string());
    }
    if base_url.len() > MAX_BASE_URL_LEN || expected.base_url.len() > MAX_BASE_URL_LEN {
        return Err("[blocked: model-bridge base_url too long]".to_string());
    }
    if path.len() > MAX_PATH_LEN || expected.path.len() > MAX_PATH_LEN {
        return Err("[blocked: model-bridge path too long]".to_string());
    }
    if path.contains('?')
        || path.contains('#')
        || expected.path.contains('?')
        || expected.path.contains('#')
    {
        return Err("[blocked: model-bridge path must not include query or fragment]".to_string());
    }
    if path.contains('\\') || expected.path.contains('\\') {
        return Err("[blocked: model-bridge path contains invalid separator]".to_string());
    }

    let requested_provider = normalize_provider_name(provider);
    let expected_provider = normalize_provider_name(&expected.provider);
    if !is_safe_provider_token(&requested_provider) || !is_safe_provider_token(&expected_provider) {
        return Err("[blocked: model-bridge provider has invalid characters]".to_string());
    }
    if requested_provider != expected_provider {
        return Err(format!(
            "[blocked: model-bridge provider mismatch: requested '{requested_provider}', expected '{}']",
            expected_provider
        ));
    }

    let requested_base = normalize_base_url(base_url)?;
    let expected_base = normalize_base_url(&expected.base_url)?;
    if requested_base != expected_base {
        return Err("[blocked: model-bridge base_url not allowed]".to_string());
    }

    let requested_path = normalize_path(path);
    let expected_path = normalize_path(&expected.path);
    if requested_path != expected_path {
        return Err("[blocked: model-bridge path not allowed]".to_string());
    }

    Ok(())
}

fn normalize_base_url(base_url: &str) -> Result<String, String> {
    let raw = base_url.trim();
    if !raw.is_ascii() {
        return Err("[blocked: model-bridge base_url must be ascii]".to_string());
    }
    let lower_raw = raw.to_ascii_lowercase();

    if lower_raw.contains('?') || lower_raw.contains('#') {
        return Err("[blocked: model-bridge base_url must not include query or fragment]".to_string());
    }

    let rest = if let Some(v) = lower_raw.strip_prefix("http://") {
        v
    } else if let Some(v) = lower_raw.strip_prefix("https://") {
        v
    } else {
        return Err("[blocked: model-bridge base_url must use http(s)]".to_string());
    };

    let (authority, suffix) = rest
        .split_once('/')
        .map(|(a, b)| (a, Some(b)))
        .unwrap_or((rest, None));
    if authority.is_empty() {
        return Err("[blocked: model-bridge base_url must include host]".to_string());
    }
    if suffix.is_some_and(|s| !s.is_empty() && s.chars().any(|c| c != '/')) {
        return Err("[blocked: model-bridge base_url must not include path]".to_string());
    }
    if authority.contains('@') {
        return Err("[blocked: model-bridge base_url must not include credentials]".to_string());
    }
    if !is_safe_base_url_authority(authority) {
        return Err("[blocked: model-bridge base_url contains invalid authority characters]".to_string());
    }

    Ok(lower_raw.trim_end_matches('/').to_string())
}

fn is_safe_base_url_authority(authority: &str) -> bool {
    const MAX_AUTHORITY_LEN: usize = 255;
    if authority.is_empty() || authority.len() > MAX_AUTHORITY_LEN {
        return false;
    }

    fn valid_host_ascii(host: &str) -> bool {
        if host.is_empty() || host.len() > 253 {
            return false;
        }

        host.split('.').all(|label| {
            !label.is_empty()
                && label.len() <= 63
                && label
                    .bytes()
                    .all(|b| b.is_ascii_alphanumeric() || b == b'-')
                && label
                    .bytes()
                    .next()
                    .is_some_and(|b| b.is_ascii_alphanumeric())
                && label
                    .bytes()
                    .last()
                    .is_some_and(|b| b.is_ascii_alphanumeric())
        })
    }

    fn valid_port(port: &str) -> bool {
        if port.is_empty() || port.len() > 5 || !port.bytes().all(|b| b.is_ascii_digit()) {
            return false;
        }
        let Ok(value) = port.parse::<u16>() else {
            return false;
        };
        value > 0
    }

    if let Some(rest) = authority.strip_prefix('[') {
        let Some((ipv6, tail)) = rest.split_once(']') else {
            return false;
        };
        if ipv6.is_empty() || !ipv6.contains(':') || ipv6.parse::<std::net::Ipv6Addr>().is_err() {
            return false;
        }
        if tail.is_empty() {
            return true;
        }
        if let Some(port) = tail.strip_prefix(':') {
            return valid_port(port);
        }
        return false;
    }

    if authority.contains('[') || authority.contains(']') {
        return false;
    }

    match authority.rsplit_once(':') {
        Some((host, _port)) if host.contains(':') => false,
        Some((host, port)) => valid_host_ascii(host) && valid_port(port),
        None => valid_host_ascii(authority),
    }
}

fn normalize_path(path: &str) -> String {
    let p = path.trim();
    let mut normalized = if p.starts_with('/') {
        p.to_string()
    } else {
        format!("/{p}")
    };

    while normalized.len() > 1 && normalized.ends_with('/') {
        normalized.pop();
    }

    normalized
}
