// WASM Plugin Host - Validação Refarm
// Carrega hello-world-plugin.wasm transpilado via jco

// @ts-ignore - Generated by jco transpile, no type declarations
import * as plugin from "./generated/hello-world.js";
// @ts-ignore - Plain JS module
import { setLogCallback } from "./generated/kernel-bridge.js";

interface PluginMetadata {
  name: string;
  version: string;
  description: string;
  supportedTypes: string[];
  requiredCapabilities: string[];
}

interface PluginInstance {
  setup(): void;
  ingest(): number;
  push(payload: string): void;
  teardown(): void;
  metadata(): PluginMetadata;
}

// UI State
let pluginInstance: PluginInstance | null = null;
const statusEl = document.getElementById("status")!;
const logsEl = document.getElementById("logs")!;
const loadBtn = document.getElementById("load-btn") as HTMLButtonElement;
const setupBtn = document.getElementById("setup-btn") as HTMLButtonElement;
const ingestBtn = document.getElementById("ingest-btn") as HTMLButtonElement;
const metadataBtn = document.getElementById(
  "metadata-btn",
) as HTMLButtonElement;
const teardownBtn = document.getElementById(
  "teardown-btn",
) as HTMLButtonElement;

// Metrics
const metrics = {
  loadTime: document.getElementById("load-time")!,
  setupTime: document.getElementById("setup-time")!,
  ingestTime: document.getElementById("ingest-time")!,
  wasmSize: document.getElementById("wasm-size")!,
};

function addLog(level: string, message: string) {
  const entry = document.createElement("div");
  entry.className = `log-entry log-${level}`;
  entry.textContent = `[${new Date().toLocaleTimeString()}] [${level.toUpperCase()}] ${message}`;
  logsEl.appendChild(entry);
  logsEl.scrollTop = logsEl.scrollHeight;
}

function setStatus(
  text: string,
  type: "ready" | "pending" | "success" | "error",
) {
  statusEl.textContent = text;
  statusEl.className = `status ${type}`;
}

function formatMs(ms: number): string {
  return `${ms.toFixed(2)} ms`;
}

// Setup log callback so kernel-bridge.js can log to UI
setLogCallback(addLog);

// 1. Load Plugin
loadBtn.addEventListener("click", async () => {
  try {
    setStatus("⏳ Carregando plugin...", "pending");
    addLog("info", "Loading transpiled WASM component...");

    const start = performance.now();

    // The plugin module was imported at the top via ESM
    // Extract the integration interface
    pluginInstance = plugin.integration as unknown as PluginInstance;

    if (!pluginInstance) {
      throw new Error("Plugin did not export refarmSdkIntegration");
    }

    // WASM size from generated cores (hello-world.core.wasm + hello-world.core2.wasm)
    const wasmSize = 50.6 + 11.6; // KB
    metrics.wasmSize.textContent = `${wasmSize.toFixed(1)} KB`;

    const elapsed = performance.now() - start;
    metrics.loadTime.textContent = formatMs(elapsed);

    setStatus("✅ Plugin carregado", "success");
    addLog("info", `Plugin loaded in ${formatMs(elapsed)} (jco transpiled)`);

    // Enable next buttons
    setupBtn.disabled = false;
    metadataBtn.disabled = false;
    loadBtn.disabled = true;
  } catch (error) {
    setStatus("❌ Erro ao carregar plugin", "error");
    addLog("error", `${error}`);
  }
});

// 2. Setup
setupBtn.addEventListener("click", async () => {
  if (!pluginInstance) return;

  try {
    setStatus("⏳ Executando setup...", "pending");
    const start = performance.now();

    pluginInstance.setup();

    const elapsed = performance.now() - start;
    metrics.setupTime.textContent = formatMs(elapsed);

    setStatus("✅ Setup concluído", "success");
    addLog("info", `Setup completed in ${formatMs(elapsed)}`);

    ingestBtn.disabled = false;
  } catch (error) {
    setStatus("❌ Erro no setup", "error");
    addLog("error", `${error}`);
  }
});

// 3. Ingest
ingestBtn.addEventListener("click", async () => {
  if (!pluginInstance) return;

  try {
    setStatus("⏳ Executando ingest...", "pending");
    const start = performance.now();

    const count = pluginInstance.ingest();
    const elapsed = performance.now() - start;
    metrics.ingestTime.textContent = formatMs(elapsed);

    setStatus("✅ Ingest concluído", "success");
    addLog("info", `Ingest completed: ${count} nodes in ${formatMs(elapsed)}`);

    teardownBtn.disabled = false;
  } catch (error) {
    setStatus("❌ Erro no ingest", "error");
    addLog("error", `${error}`);
  }
});

// 4. Metadata
metadataBtn.addEventListener("click", () => {
  if (!pluginInstance) return;

  try {
    const metadata = pluginInstance.metadata();
    addLog("info", `Plugin: ${metadata.name} v${metadata.version}`);
    addLog("info", `Description: ${metadata.description}`);
    addLog("info", `Supported types: ${metadata.supportedTypes.join(", ")}`);
  } catch (error) {
    addLog("error", `${error}`);
  }
});

// 5. Teardown
teardownBtn.addEventListener("click", () => {
  if (!pluginInstance) return;

  try {
    pluginInstance.teardown();
    setStatus("✅ Teardown concluído", "success");

    // Reset
    pluginInstance = null;
    loadBtn.disabled = false;
    setupBtn.disabled = true;
    ingestBtn.disabled = true;
    metadataBtn.disabled = true;
    teardownBtn.disabled = true;
  } catch (error) {
    setStatus("❌ Erro no teardown", "error");
    addLog("error", `${error}`);
  }
});

// Initial logs
addLog("info", 'Host initialized. Click "1️⃣ Carregar Plugin" to start.');
addLog("info", "Using jco-transpiled WASM Component Model (Rust + WIT)");
