name: "Deploy Pages"
description: "Secure wrapper for actions/deploy-pages with pinned hash."

outputs:
  page_url:
    description: "The URL of the deployed page"
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: "composite"
  steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
