import { execFileSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

/**
 * Repo-hygiene guard: `src/bindings.rs` is GENERATED by wit-bindgen during
 * `cargo component build` — it is not source and must never be committed for a product
 * package (it drifts from the WIT and traps a clean `cargo test --lib`, which needs it to
 * exist but expects the build to produce it). The root .gitignore ignores the
 * per-package bindings glob; this test fails if one is ever tracked again, so a future
 * WIT package that generates bindings can't silently re-introduce the drift.
 *
 * Frozen test fixtures (tractor/tests/fixtures) commit theirs ON PURPOSE (they are a
 * snapshot, not a build target) and are excepted.
 */
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");

const FIXTURE_EXCEPTIONS = ["packages/tractor/tests/fixtures/"];

function trackedProductBindings() {
	// Build the glob without a literal `*/` in source — some JS transformers misread
	// `*/` inside a string as a block-comment terminator.
	const glob = "*" + "/src/bindings.rs";
	const out = execFileSync("git", ["ls-files", glob], {
		cwd: repoRoot,
		encoding: "utf-8",
	});
	return out
		.split("\n")
		.filter(Boolean)
		.filter((f) => !FIXTURE_EXCEPTIONS.some((ex) => f.startsWith(ex)));
}

describe("repo hygiene — generated WIT bindings must not be committed", () => {
	it("no product package tracks a generated src/bindings.rs", () => {
		const offenders = trackedProductBindings();
		const message =
			"These src/bindings.rs are GENERATED (cargo component build) and must not be tracked. " +
			"Run: git rm --cached <path>. The root .gitignore already ignores packages/*/src/bindings.rs. " +
			"Offenders: " +
			offenders.join(", ");
		expect(offenders, message).toEqual([]);
	});
});
