//! TractorNativeBindings — host-side implementation of `tractor-bridge` WIT interface.
//!
//! Mirrors `WasiImports` from packages/tractor/src/lib/wasi-imports.ts.
//!
//! Implements traits generated by `wasmtime::component::bindgen!` in `plugin_host.rs`:
//!   - `refarm::plugin::types::Host`          — empty (shared types interface, no methods)
//!   - `refarm::plugin::tractor_bridge::Host` — CRDT/storage/telemetry host functions
//!   - `refarm::plugin::llm_bridge::Host`     — host-proxied HTTP completion boundary
//!
//! Return types use the WIT `result<T, plugin-error>` directly — no outer wasmtime::Result.

use crate::host::plugin_host::refarm::plugin::{
    llm_bridge::Host as LlmBridgeHost,
    tractor_bridge::Host as TractorBridgeHost,
    types::{Host as TypesHost, IdentityInfo, PluginError},
};
use crate::sync::NativeSync;
use crate::telemetry::TelemetryBus;
use std::io::Read as _;

#[derive(Debug, Clone, PartialEq, Eq)]
struct LlmRoute {
    provider: String,
    base_url: String,
    path: String,
}

/// Host-side implementation of the `tractor-bridge` WIT interface.
///
/// Holds references to NativeSync (storage) and TelemetryBus so plugin
/// calls are forwarded to the actual Tractor infrastructure.
pub struct TractorNativeBindings {
    pub plugin_id: String,
    pub sync: NativeSync,
    pub telemetry: TelemetryBus,
}

impl TractorNativeBindings {
    pub fn new(plugin_id: impl Into<String>, sync: NativeSync, telemetry: TelemetryBus) -> Self {
        Self {
            plugin_id: plugin_id.into(),
            sync,
            telemetry,
        }
    }
}

// ── types::Host ───────────────────────────────────────────────────────────────
//
// The `types` interface defines shared types (plugin-error, identity-info, etc.)
// but contains no functions. The generated `Host` trait has no methods.
impl TypesHost for TractorNativeBindings {}

// ── tractor_bridge::Host ──────────────────────────────────────────────────────
//
// Each method corresponds to one WIT function in `tractor-bridge`.
// Return type is `Result<T, PluginError>` — the WIT result directly.

#[wasmtime::component::__internal::async_trait]
impl TractorBridgeHost for TractorNativeBindings {
    /// Store (upsert) a JSON-LD node into the sovereign graph.
    async fn store_node(&mut self, node_json: String) -> Result<String, PluginError> {
        let value: serde_json::Value = match serde_json::from_str(&node_json) {
            Ok(v) => v,
            Err(e) => return Err(PluginError::InvalidSchema(e.to_string())),
        };

        let id = value["@id"]
            .as_str()
            .or_else(|| value["id"].as_str())
            .unwrap_or("urn:unknown")
            .to_string();

        let type_ = value["@type"]
            .as_str()
            .or_else(|| value["type"].as_str())
            .unwrap_or("Unknown")
            .to_string();

        self.sync
            .store_node(&id, &type_, None, &node_json, Some(&self.plugin_id))
            .map_err(|e| PluginError::Internal(e.to_string()))?;

        self.telemetry.emit_named(
            "plugin:store_node",
            Some(self.plugin_id.clone()),
            Some(serde_json::json!({ "nodeId": id, "type": type_ })),
        );

        Ok(id)
    }

    /// Retrieve a previously stored node by ID.
    async fn get_node(&mut self, id: String) -> Result<String, PluginError> {
        match self.sync.get_node(&id) {
            Ok(Some(payload)) => Ok(payload),
            Ok(None) => Err(PluginError::NotFound(id)),
            Err(e) => Err(PluginError::Internal(e.to_string())),
        }
    }

    /// Query nodes by @type, returning up to `limit` results.
    async fn query_nodes(
        &mut self,
        node_type: String,
        limit: u32,
    ) -> Result<Vec<String>, PluginError> {
        self.sync
            .query_nodes(&node_type)
            .map_err(|e| PluginError::Internal(e.to_string()))
            .map(|rows| {
                rows.into_iter()
                    .take(limit as usize)
                    .map(|r| r.payload)
                    .collect()
            })
    }

    /// Request a user-facing permission prompt. Always grants in Phase 4 (stub).
    async fn request_permission(&mut self, _capability: String, _reason: String) -> bool {
        true
    }

    /// Return the current user's identity information.
    async fn get_identity(&mut self) -> Result<IdentityInfo, PluginError> {
        Ok(IdentityInfo {
            identity_type: "guest".to_string(),
            storage_tier: "ephemeral".to_string(),
            identifier: "".to_string(),
        })
    }

    /// Discover a plugin that provides a named API (SPI pattern).
    async fn get_plugin_api(&mut self, api_name: String) -> Result<String, PluginError> {
        Err(PluginError::NotFound(format!(
            "no plugin provides api: {api_name}"
        )))
    }

    /// Emit a telemetry event from the plugin.
    async fn emit_telemetry(&mut self, event: String, payload: Option<String>) {
        let payload_val = payload.and_then(|p| serde_json::from_str(&p).ok());
        self.telemetry
            .emit_named(event, Some(self.plugin_id.clone()), payload_val);
    }
}

// ── llm_bridge::Host ─────────────────────────────────────────────────────────

#[wasmtime::component::__internal::async_trait]
impl LlmBridgeHost for TractorNativeBindings {
    async fn complete_http(
        &mut self,
        provider: String,
        base_url: String,
        path: String,
        headers: Vec<(String, String)>,
        body: Vec<u8>,
    ) -> Result<Vec<u8>, String> {
        llm_complete_http(&provider, &base_url, &path, &headers, &body)
    }
}

fn llm_complete_http(
    provider: &str,
    base_url: &str,
    path: &str,
    headers: &[(String, String)],
    body: &[u8],
) -> Result<Vec<u8>, String> {
    let expected = expected_llm_route_from_env();
    enforce_llm_route(provider, base_url, path, &expected)?;
    enforce_llm_request_body(body)?;
    let provider = normalize_provider_name(provider);

    let url = join_base_url_and_path(base_url, path);
    let mut req = ureq::post(&url);

    for (name, value) in sanitized_plugin_headers(headers) {
        req = req.set(name, value);
    }

    if use_anthropic_auth(&provider) {
        let key = std::env::var("ANTHROPIC_API_KEY")
            .map_err(|_| "ANTHROPIC_API_KEY not set".to_string())?;
        req = req.set("x-api-key", &key);
    } else if use_openai_auth(&provider) {
        if let Ok(key) = std::env::var("OPENAI_API_KEY") {
            if !key.trim().is_empty() {
                req = req.set("authorization", &format!("Bearer {key}"));
            }
        }
    }

    match req.send_bytes(body) {
        Ok(resp) => read_response_bytes(resp),
        Err(ureq::Error::Status(code, resp)) => {
            let bytes = read_response_bytes(resp)?;
            Err(format!("HTTP {code}: {}", String::from_utf8_lossy(&bytes)))
        }
        Err(e) => Err(format!("http error: {e}")),
    }
}

fn use_anthropic_auth(provider: &str) -> bool {
    provider.trim().eq_ignore_ascii_case("anthropic")
}

fn enforce_llm_request_body(body: &[u8]) -> Result<(), String> {
    const MAX_LLM_REQUEST_BODY_LEN: usize = 1024 * 1024;
    if body.len() > MAX_LLM_REQUEST_BODY_LEN {
        return Err("[blocked: llm-bridge body too large]".to_string());
    }
    Ok(())
}

fn is_openai_provider_family(provider: &str) -> bool {
    let provider = provider.trim().to_ascii_lowercase();
    provider == "openai" || provider.starts_with("openai-")
}

fn use_openai_auth(provider: &str) -> bool {
    is_openai_provider_family(provider)
}

fn provider_name_from_env() -> String {
    std::env::var("LLM_PROVIDER")
        .ok()
        .map(|v| normalize_provider_name(&v))
        .filter(|v| !v.is_empty())
        .or_else(|| {
            std::env::var("LLM_DEFAULT_PROVIDER")
                .ok()
                .map(|v| normalize_provider_name(&v))
                .filter(|v| !v.is_empty())
        })
        .unwrap_or_else(|| "ollama".to_string())
}

fn normalize_provider_name(value: &str) -> String {
    value.trim().to_ascii_lowercase()
}

fn is_safe_provider_token(value: &str) -> bool {
    const MAX_PROVIDER_TOKEN_LEN: usize = 64;
    !value.is_empty()
        && value.len() <= MAX_PROVIDER_TOKEN_LEN
        && value
            .bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-' || b == b'_')
}

fn expected_llm_route_from_env() -> LlmRoute {
    let provider = provider_name_from_env();
    if provider == "anthropic" {
        return LlmRoute {
            provider,
            base_url: "https://api.anthropic.com".to_string(),
            path: "/v1/messages".to_string(),
        };
    }

    let base_url = std::env::var("LLM_BASE_URL").unwrap_or_else(|_| {
        if is_openai_provider_family(&provider) {
            "https://api.openai.com".to_string()
        } else {
            "http://localhost:11434".to_string()
        }
    });

    LlmRoute {
        provider,
        base_url,
        path: "/v1/chat/completions".to_string(),
    }
}

fn enforce_llm_route(
    provider: &str,
    base_url: &str,
    path: &str,
    expected: &LlmRoute,
) -> Result<(), String> {
    const MAX_BASE_URL_LEN: usize = 2048;
    const MAX_PATH_LEN: usize = 2048;

    if provider.chars().any(|c| c.is_control()) || expected.provider.chars().any(|c| c.is_control()) {
        return Err("[blocked: llm-bridge provider contains control characters]".to_string());
    }
    if base_url.chars().any(|c| c.is_control()) || expected.base_url.chars().any(|c| c.is_control()) {
        return Err("[blocked: llm-bridge base_url contains control characters]".to_string());
    }
    if path.chars().any(|c| c.is_control()) || expected.path.chars().any(|c| c.is_control()) {
        return Err("[blocked: llm-bridge path contains control characters]".to_string());
    }
    if base_url.len() > MAX_BASE_URL_LEN || expected.base_url.len() > MAX_BASE_URL_LEN {
        return Err("[blocked: llm-bridge base_url too long]".to_string());
    }
    if path.len() > MAX_PATH_LEN || expected.path.len() > MAX_PATH_LEN {
        return Err("[blocked: llm-bridge path too long]".to_string());
    }
    if path.contains('?')
        || path.contains('#')
        || expected.path.contains('?')
        || expected.path.contains('#')
    {
        return Err("[blocked: llm-bridge path must not include query or fragment]".to_string());
    }
    if path.contains('\\') || expected.path.contains('\\') {
        return Err("[blocked: llm-bridge path contains invalid separator]".to_string());
    }

    let requested_provider = normalize_provider_name(provider);
    let expected_provider = normalize_provider_name(&expected.provider);
    if !is_safe_provider_token(&requested_provider) || !is_safe_provider_token(&expected_provider) {
        return Err("[blocked: llm-bridge provider has invalid characters]".to_string());
    }
    if requested_provider != expected_provider {
        return Err(format!(
            "[blocked: llm-bridge provider mismatch: requested '{requested_provider}', expected '{}']",
            expected_provider
        ));
    }

    let requested_base = normalize_base_url(base_url)?;
    let expected_base = normalize_base_url(&expected.base_url)?;
    if requested_base != expected_base {
        return Err("[blocked: llm-bridge base_url not allowed]".to_string());
    }

    let requested_path = normalize_path(path);
    let expected_path = normalize_path(&expected.path);
    if requested_path != expected_path {
        return Err("[blocked: llm-bridge path not allowed]".to_string());
    }

    Ok(())
}

fn normalize_base_url(base_url: &str) -> Result<String, String> {
    let raw = base_url.trim();
    let lower_raw = raw.to_ascii_lowercase();

    if lower_raw.contains('?') || lower_raw.contains('#') {
        return Err("[blocked: llm-bridge base_url must not include query or fragment]".to_string());
    }

    let rest = if let Some(v) = lower_raw.strip_prefix("http://") {
        v
    } else if let Some(v) = lower_raw.strip_prefix("https://") {
        v
    } else {
        return Err("[blocked: llm-bridge base_url must use http(s)]".to_string());
    };

    let authority = rest.split('/').next().unwrap_or_default();
    if authority.is_empty() {
        return Err("[blocked: llm-bridge base_url must include host]".to_string());
    }
    if authority.contains('@') {
        return Err("[blocked: llm-bridge base_url must not include credentials]".to_string());
    }

    Ok(lower_raw.trim_end_matches('/').to_string())
}

fn normalize_path(path: &str) -> String {
    let p = path.trim();
    let mut normalized = if p.starts_with('/') {
        p.to_string()
    } else {
        format!("/{p}")
    };

    while normalized.len() > 1 && normalized.ends_with('/') {
        normalized.pop();
    }

    normalized
}

fn sanitized_plugin_headers(headers: &[(String, String)]) -> Vec<(&str, &str)> {
    const MAX_FORWARDED_HEADER_COUNT: usize = 64;
    const MAX_HEADER_SCAN: usize = 256;
    const MAX_HEADER_PAIR_BYTES: usize = 16 * 1024;
    const MAX_HEADER_TOTAL_BYTES: usize = 256 * 1024;

    let mut out = Vec::new();
    let mut seen_names = std::collections::HashSet::new();
    let mut total_bytes = 0usize;

    for (name, value) in headers.iter().take(MAX_HEADER_SCAN) {
        if out.len() >= MAX_FORWARDED_HEADER_COUNT {
            break;
        }

        let n = name.trim().to_ascii_lowercase();
        if n.is_empty()
            || n == "authorization"
            || n == "x-api-key"
            || n == "host"
            || n == "content-length"
            || n == "transfer-encoding"
            || n == "connection"
            || n == "proxy-authorization"
            || n == "proxy-authenticate"
            || n == "proxy-connection"
            || n == "te"
            || n == "trailer"
            || n == "upgrade"
            || n == "keep-alive"
            || !is_safe_header_name(name)
            || !is_safe_header_value(value)
        {
            continue;
        }

        let trimmed_name = name.trim();
        let pair_bytes = trimmed_name.len().saturating_add(value.len());
        if pair_bytes > MAX_HEADER_PAIR_BYTES {
            continue;
        }
        if !seen_names.insert(n) {
            continue;
        }
        let next_total = total_bytes.saturating_add(pair_bytes);
        if next_total > MAX_HEADER_TOTAL_BYTES {
            continue;
        }
        total_bytes = next_total;
        out.push((trimmed_name, value.as_str()));
    }

    out
}

fn is_safe_header_name(name: &str) -> bool {
    let trimmed = name.trim();
    const MAX_HEADER_NAME_LEN: usize = 128;
    !trimmed.is_empty()
        && trimmed.len() <= MAX_HEADER_NAME_LEN
        && trimmed
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b"!#$%&'*+-.^_`|~".contains(&b))
}

fn is_safe_header_value(value: &str) -> bool {
    const MAX_HEADER_VALUE_LEN: usize = 16 * 1024;
    value.len() <= MAX_HEADER_VALUE_LEN && !value.chars().any(|c| c.is_control())
}

fn join_base_url_and_path(base_url: &str, path: &str) -> String {
    let left = base_url.trim().trim_end_matches('/');
    let right = path.trim();
    if right.starts_with('/') {
        format!("{left}{right}")
    } else {
        format!("{left}/{right}")
    }
}

fn read_response_bytes(resp: ureq::Response) -> Result<Vec<u8>, String> {
    const MAX_LLM_RESPONSE_BODY_LEN: usize = 2 * 1024 * 1024;
    let reader = resp.into_reader();
    read_limited_bytes(reader, MAX_LLM_RESPONSE_BODY_LEN, "llm-bridge response body")
}

fn read_limited_bytes(
    mut reader: impl std::io::Read,
    max_len: usize,
    label: &str,
) -> Result<Vec<u8>, String> {
    let mut out = Vec::new();
    (&mut reader)
        .take(max_len as u64 + 1)
        .read_to_end(&mut out)
        .map_err(|e| format!("response read: {e}"))?;
    if out.len() > max_len {
        return Err(format!("{label} too large"));
    }
    Ok(out)
}

#[cfg(test)]
#[path = "wasi_bridge_tests.rs"]
mod tests;
