//! TractorNativeBindings — host-side implementation of `tractor-bridge` WIT interface.
//!
//! Mirrors `WasiImports` from packages/tractor/src/lib/wasi-imports.ts.
//!
//! Implements traits generated by `wasmtime::component::bindgen!` in `plugin_host.rs`:
//!   - `refarm::plugin::types::Host`          — empty (shared types interface, no methods)
//!   - `refarm::plugin::tractor_bridge::Host` — CRDT/storage/telemetry host functions
//!   - `refarm::plugin::llm_bridge::Host`     — host-proxied HTTP completion boundary
//!
//! Return types use the WIT `result<T, plugin-error>` directly — no outer wasmtime::Result.

use crate::host::plugin_host::refarm::plugin::{
    llm_bridge::Host as LlmBridgeHost,
    tractor_bridge::Host as TractorBridgeHost,
    types::{Host as TypesHost, IdentityInfo, PluginError},
};
use crate::sync::NativeSync;
use crate::telemetry::TelemetryBus;
use std::io::Read as _;

#[derive(Debug, Clone, PartialEq, Eq)]
struct LlmRoute {
    provider: String,
    base_url: String,
    path: String,
}

/// Host-side implementation of the `tractor-bridge` WIT interface.
///
/// Holds references to NativeSync (storage) and TelemetryBus so plugin
/// calls are forwarded to the actual Tractor infrastructure.
pub struct TractorNativeBindings {
    pub plugin_id: String,
    pub sync: NativeSync,
    pub telemetry: TelemetryBus,
}

impl TractorNativeBindings {
    pub fn new(plugin_id: impl Into<String>, sync: NativeSync, telemetry: TelemetryBus) -> Self {
        Self {
            plugin_id: plugin_id.into(),
            sync,
            telemetry,
        }
    }
}

// ── types::Host ───────────────────────────────────────────────────────────────
//
// The `types` interface defines shared types (plugin-error, identity-info, etc.)
// but contains no functions. The generated `Host` trait has no methods.
impl TypesHost for TractorNativeBindings {}

// ── tractor_bridge::Host ──────────────────────────────────────────────────────
//
// Each method corresponds to one WIT function in `tractor-bridge`.
// Return type is `Result<T, PluginError>` — the WIT result directly.

#[wasmtime::component::__internal::async_trait]
impl TractorBridgeHost for TractorNativeBindings {
    /// Store (upsert) a JSON-LD node into the sovereign graph.
    async fn store_node(&mut self, node_json: String) -> Result<String, PluginError> {
        let value: serde_json::Value = match serde_json::from_str(&node_json) {
            Ok(v) => v,
            Err(e) => return Err(PluginError::InvalidSchema(e.to_string())),
        };

        let id = value["@id"]
            .as_str()
            .or_else(|| value["id"].as_str())
            .unwrap_or("urn:unknown")
            .to_string();

        let type_ = value["@type"]
            .as_str()
            .or_else(|| value["type"].as_str())
            .unwrap_or("Unknown")
            .to_string();

        self.sync
            .store_node(&id, &type_, None, &node_json, Some(&self.plugin_id))
            .map_err(|e| PluginError::Internal(e.to_string()))?;

        self.telemetry.emit_named(
            "plugin:store_node",
            Some(self.plugin_id.clone()),
            Some(serde_json::json!({ "nodeId": id, "type": type_ })),
        );

        Ok(id)
    }

    /// Retrieve a previously stored node by ID.
    async fn get_node(&mut self, id: String) -> Result<String, PluginError> {
        match self.sync.get_node(&id) {
            Ok(Some(payload)) => Ok(payload),
            Ok(None) => Err(PluginError::NotFound(id)),
            Err(e) => Err(PluginError::Internal(e.to_string())),
        }
    }

    /// Query nodes by @type, returning up to `limit` results.
    async fn query_nodes(
        &mut self,
        node_type: String,
        limit: u32,
    ) -> Result<Vec<String>, PluginError> {
        self.sync
            .query_nodes(&node_type)
            .map_err(|e| PluginError::Internal(e.to_string()))
            .map(|rows| {
                rows.into_iter()
                    .take(limit as usize)
                    .map(|r| r.payload)
                    .collect()
            })
    }

    /// Request a user-facing permission prompt. Always grants in Phase 4 (stub).
    async fn request_permission(&mut self, _capability: String, _reason: String) -> bool {
        true
    }

    /// Return the current user's identity information.
    async fn get_identity(&mut self) -> Result<IdentityInfo, PluginError> {
        Ok(IdentityInfo {
            identity_type: "guest".to_string(),
            storage_tier: "ephemeral".to_string(),
            identifier: "".to_string(),
        })
    }

    /// Discover a plugin that provides a named API (SPI pattern).
    async fn get_plugin_api(&mut self, api_name: String) -> Result<String, PluginError> {
        Err(PluginError::NotFound(format!(
            "no plugin provides api: {api_name}"
        )))
    }

    /// Emit a telemetry event from the plugin.
    async fn emit_telemetry(&mut self, event: String, payload: Option<String>) {
        let payload_val = payload.and_then(|p| serde_json::from_str(&p).ok());
        self.telemetry
            .emit_named(event, Some(self.plugin_id.clone()), payload_val);
    }
}

// ── llm_bridge::Host ─────────────────────────────────────────────────────────

#[wasmtime::component::__internal::async_trait]
impl LlmBridgeHost for TractorNativeBindings {
    async fn complete_http(
        &mut self,
        provider: String,
        base_url: String,
        path: String,
        headers: Vec<(String, String)>,
        body: Vec<u8>,
    ) -> Result<Vec<u8>, String> {
        llm_complete_http(&provider, &base_url, &path, &headers, &body)
    }
}

fn llm_complete_http(
    provider: &str,
    base_url: &str,
    path: &str,
    headers: &[(String, String)],
    body: &[u8],
) -> Result<Vec<u8>, String> {
    let expected = expected_llm_route_from_env();
    enforce_llm_route(provider, base_url, path, &expected)?;
    enforce_llm_request_body(body)?;
    let provider = normalize_provider_name(provider);

    let url = join_base_url_and_path(base_url, path);
    let mut req = ureq::post(&url);

    for (name, value) in sanitized_plugin_headers(headers) {
        req = req.set(name, value);
    }

    if use_anthropic_auth(&provider) {
        let key = anthropic_api_key_from_env()?;
        req = req.set("x-api-key", &key);
    } else if use_openai_auth(&provider) {
        if let Some(header) = openai_auth_header_from_env()? {
            req = req.set("authorization", &header);
        }
    }

    match req.send_bytes(body) {
        Ok(resp) => read_response_bytes(resp),
        Err(ureq::Error::Status(code, resp)) => {
            let bytes = read_response_bytes(resp)?;
            Err(format!("HTTP {code}: {}", llm_error_body_preview(&bytes)))
        }
        Err(e) => Err(format!("http error: {e}")),
    }
}

fn llm_error_body_preview(bytes: &[u8]) -> String {
    const MAX_LLM_ERROR_PREVIEW_LEN: usize = 8 * 1024;

    if bytes.len() <= MAX_LLM_ERROR_PREVIEW_LEN {
        return String::from_utf8_lossy(bytes).to_string();
    }

    let prefix = String::from_utf8_lossy(&bytes[..MAX_LLM_ERROR_PREVIEW_LEN]);
    format!(
        "{prefix}\n[truncated: llm-bridge error body exceeded {MAX_LLM_ERROR_PREVIEW_LEN} bytes]"
    )
}

fn use_anthropic_auth(provider: &str) -> bool {
    provider.trim().eq_ignore_ascii_case("anthropic")
}

fn enforce_llm_request_body(body: &[u8]) -> Result<(), String> {
    const MAX_LLM_REQUEST_BODY_LEN: usize = 1024 * 1024;
    if body.len() > MAX_LLM_REQUEST_BODY_LEN {
        return Err("[blocked: llm-bridge body too large]".to_string());
    }
    Ok(())
}

fn is_openai_provider_family(provider: &str) -> bool {
    let provider = provider.trim().to_ascii_lowercase();
    provider == "openai" || provider.starts_with("openai-")
}

fn use_openai_auth(provider: &str) -> bool {
    is_openai_provider_family(provider)
}

fn sanitize_auth_token_for_header(token: &str) -> Option<String> {
    const MAX_AUTH_TOKEN_LEN: usize = 4096;
    let trimmed = token.trim();
    if trimmed.is_empty()
        || trimmed != token
        || trimmed.len() > MAX_AUTH_TOKEN_LEN
        || !trimmed.is_ascii()
        || trimmed.chars().any(|c| c.is_control())
        || trimmed.chars().any(|c| c.is_whitespace())
    {
        return None;
    }
    Some(trimmed.to_string())
}

fn anthropic_api_key_from_env() -> Result<String, String> {
    let key = std::env::var("ANTHROPIC_API_KEY")
        .map_err(|_| "ANTHROPIC_API_KEY not set".to_string())?;
    sanitize_auth_token_for_header(&key)
        .ok_or_else(|| "[blocked: invalid ANTHROPIC_API_KEY]".to_string())
}

fn openai_auth_header_from_env() -> Result<Option<String>, String> {
    let Ok(key) = std::env::var("OPENAI_API_KEY") else {
        return Ok(None);
    };
    let key = sanitize_auth_token_for_header(&key)
        .ok_or_else(|| "[blocked: invalid OPENAI_API_KEY]".to_string())?;
    Ok(Some(format!("Bearer {key}")))
}

fn provider_name_from_env() -> String {
    std::env::var("LLM_PROVIDER")
        .ok()
        .map(|v| normalize_provider_name(&v))
        .filter(|v| !v.is_empty() && is_safe_provider_token(v))
        .or_else(|| {
            std::env::var("LLM_DEFAULT_PROVIDER")
                .ok()
                .map(|v| normalize_provider_name(&v))
                .filter(|v| !v.is_empty() && is_safe_provider_token(v))
        })
        .unwrap_or_else(|| "ollama".to_string())
}

fn normalize_provider_name(value: &str) -> String {
    value.trim().to_ascii_lowercase()
}

fn is_safe_provider_token(value: &str) -> bool {
    const MAX_PROVIDER_TOKEN_LEN: usize = 64;
    !value.is_empty()
        && value.len() <= MAX_PROVIDER_TOKEN_LEN
        && value
            .bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-' || b == b'_')
}

fn expected_llm_route_from_env() -> LlmRoute {
    let provider = provider_name_from_env();
    if provider == "anthropic" {
        return LlmRoute {
            provider,
            base_url: "https://api.anthropic.com".to_string(),
            path: "/v1/messages".to_string(),
        };
    }

    let base_url = std::env::var("LLM_BASE_URL").unwrap_or_else(|_| {
        if is_openai_provider_family(&provider) {
            "https://api.openai.com".to_string()
        } else {
            "http://localhost:11434".to_string()
        }
    });

    LlmRoute {
        provider,
        base_url,
        path: "/v1/chat/completions".to_string(),
    }
}

fn enforce_llm_route(
    provider: &str,
    base_url: &str,
    path: &str,
    expected: &LlmRoute,
) -> Result<(), String> {
    const MAX_BASE_URL_LEN: usize = 2048;
    const MAX_PATH_LEN: usize = 2048;

    if provider.chars().any(|c| c.is_control()) || expected.provider.chars().any(|c| c.is_control()) {
        return Err("[blocked: llm-bridge provider contains control characters]".to_string());
    }
    if base_url.chars().any(|c| c.is_control()) || expected.base_url.chars().any(|c| c.is_control()) {
        return Err("[blocked: llm-bridge base_url contains control characters]".to_string());
    }
    if path.chars().any(|c| c.is_control()) || expected.path.chars().any(|c| c.is_control()) {
        return Err("[blocked: llm-bridge path contains control characters]".to_string());
    }
    if !path.is_ascii() || !expected.path.is_ascii() {
        return Err("[blocked: llm-bridge path must be ascii]".to_string());
    }
    if path.trim().is_empty() || expected.path.trim().is_empty() {
        return Err("[blocked: llm-bridge path must be non-empty]".to_string());
    }
    if path.trim() != path || expected.path.trim() != expected.path {
        return Err("[blocked: llm-bridge path contains surrounding whitespace]".to_string());
    }
    if path.chars().any(|c| c.is_whitespace()) || expected.path.chars().any(|c| c.is_whitespace()) {
        return Err("[blocked: llm-bridge path must not contain whitespace]".to_string());
    }
    if base_url.len() > MAX_BASE_URL_LEN || expected.base_url.len() > MAX_BASE_URL_LEN {
        return Err("[blocked: llm-bridge base_url too long]".to_string());
    }
    if path.len() > MAX_PATH_LEN || expected.path.len() > MAX_PATH_LEN {
        return Err("[blocked: llm-bridge path too long]".to_string());
    }
    if path.contains('?')
        || path.contains('#')
        || expected.path.contains('?')
        || expected.path.contains('#')
    {
        return Err("[blocked: llm-bridge path must not include query or fragment]".to_string());
    }
    if path.contains('\\') || expected.path.contains('\\') {
        return Err("[blocked: llm-bridge path contains invalid separator]".to_string());
    }

    let requested_provider = normalize_provider_name(provider);
    let expected_provider = normalize_provider_name(&expected.provider);
    if !is_safe_provider_token(&requested_provider) || !is_safe_provider_token(&expected_provider) {
        return Err("[blocked: llm-bridge provider has invalid characters]".to_string());
    }
    if requested_provider != expected_provider {
        return Err(format!(
            "[blocked: llm-bridge provider mismatch: requested '{requested_provider}', expected '{}']",
            expected_provider
        ));
    }

    let requested_base = normalize_base_url(base_url)?;
    let expected_base = normalize_base_url(&expected.base_url)?;
    if requested_base != expected_base {
        return Err("[blocked: llm-bridge base_url not allowed]".to_string());
    }

    let requested_path = normalize_path(path);
    let expected_path = normalize_path(&expected.path);
    if requested_path != expected_path {
        return Err("[blocked: llm-bridge path not allowed]".to_string());
    }

    Ok(())
}

fn normalize_base_url(base_url: &str) -> Result<String, String> {
    let raw = base_url.trim();
    if !raw.is_ascii() {
        return Err("[blocked: llm-bridge base_url must be ascii]".to_string());
    }
    let lower_raw = raw.to_ascii_lowercase();

    if lower_raw.contains('?') || lower_raw.contains('#') {
        return Err("[blocked: llm-bridge base_url must not include query or fragment]".to_string());
    }

    let rest = if let Some(v) = lower_raw.strip_prefix("http://") {
        v
    } else if let Some(v) = lower_raw.strip_prefix("https://") {
        v
    } else {
        return Err("[blocked: llm-bridge base_url must use http(s)]".to_string());
    };

    let (authority, suffix) = rest
        .split_once('/')
        .map(|(a, b)| (a, Some(b)))
        .unwrap_or((rest, None));
    if authority.is_empty() {
        return Err("[blocked: llm-bridge base_url must include host]".to_string());
    }
    if suffix.is_some_and(|s| !s.is_empty() && s.chars().any(|c| c != '/')) {
        return Err("[blocked: llm-bridge base_url must not include path]".to_string());
    }
    if authority.contains('@') {
        return Err("[blocked: llm-bridge base_url must not include credentials]".to_string());
    }
    if !is_safe_base_url_authority(authority) {
        return Err("[blocked: llm-bridge base_url contains invalid authority characters]".to_string());
    }

    Ok(lower_raw.trim_end_matches('/').to_string())
}

fn is_safe_base_url_authority(authority: &str) -> bool {
    const MAX_AUTHORITY_LEN: usize = 255;
    if authority.is_empty() || authority.len() > MAX_AUTHORITY_LEN {
        return false;
    }

    fn valid_host_ascii(host: &str) -> bool {
        if host.is_empty() || host.len() > 253 {
            return false;
        }

        host.split('.').all(|label| {
            !label.is_empty()
                && label.len() <= 63
                && label
                    .bytes()
                    .all(|b| b.is_ascii_alphanumeric() || b == b'-')
                && label
                    .bytes()
                    .next()
                    .is_some_and(|b| b.is_ascii_alphanumeric())
                && label
                    .bytes()
                    .last()
                    .is_some_and(|b| b.is_ascii_alphanumeric())
        })
    }

    fn valid_port(port: &str) -> bool {
        if port.is_empty() || port.len() > 5 || !port.bytes().all(|b| b.is_ascii_digit()) {
            return false;
        }
        let Ok(value) = port.parse::<u16>() else {
            return false;
        };
        value > 0
    }

    if let Some(rest) = authority.strip_prefix('[') {
        let Some((ipv6, tail)) = rest.split_once(']') else {
            return false;
        };
        if ipv6.is_empty() || !ipv6.contains(':') || ipv6.parse::<std::net::Ipv6Addr>().is_err() {
            return false;
        }
        if tail.is_empty() {
            return true;
        }
        if let Some(port) = tail.strip_prefix(':') {
            return valid_port(port);
        }
        return false;
    }

    if authority.contains('[') || authority.contains(']') {
        return false;
    }

    match authority.rsplit_once(':') {
        Some((host, _port)) if host.contains(':') => false,
        Some((host, port)) => valid_host_ascii(host) && valid_port(port),
        None => valid_host_ascii(authority),
    }
}

fn normalize_path(path: &str) -> String {
    let p = path.trim();
    let mut normalized = if p.starts_with('/') {
        p.to_string()
    } else {
        format!("/{p}")
    };

    while normalized.len() > 1 && normalized.ends_with('/') {
        normalized.pop();
    }

    normalized
}

fn sanitized_plugin_headers(headers: &[(String, String)]) -> Vec<(&str, &str)> {
    const MAX_FORWARDED_HEADER_COUNT: usize = 64;
    const MAX_HEADER_SCAN: usize = 256;
    const MAX_HEADER_NAME_LEN: usize = 128;
    const MAX_HEADER_PAIR_BYTES: usize = 16 * 1024;
    const MAX_HEADER_TOTAL_BYTES: usize = 256 * 1024;

    let mut out = Vec::new();
    let mut seen_names = std::collections::HashSet::new();
    let mut total_bytes = 0usize;

    for (name, value) in headers.iter().take(MAX_HEADER_SCAN) {
        if out.len() >= MAX_FORWARDED_HEADER_COUNT {
            break;
        }

        let trimmed_name = name.trim();
        if trimmed_name.is_empty() || trimmed_name.len() > MAX_HEADER_NAME_LEN {
            continue;
        }

        let n = trimmed_name.to_ascii_lowercase();
        if n.is_empty()
            || n == "authorization"
            || n == "x-authorization"
            || n == "authentication"
            || n == "x-api-key"
            || n == "x-api-token"
            || n == "api-key"
            || n == "x-auth-token"
            || n == "x-authentication-token"
            || n == "x-access-token"
            || n == "x-session-token"
            || n == "x-id-token"
            || n == "x-amz-security-token"
            || n == "cf-access-jwt-assertion"
            || n == "x-goog-iap-jwt-assertion"
            || n == "x-goog-authenticated-user-email"
            || n == "x-goog-authenticated-user-id"
            || n == "x-google-authenticated-user-email"
            || n == "x-google-authenticated-user-id"
            || n == "x-amzn-oidc-data"
            || n == "x-amzn-oidc-identity"
            || n == "x-amzn-oidc-accesstoken"
            || n == "x-forwarded-user"
            || n == "x-forwarded-groups"
            || n == "x-remote-user"
            || n == "x-remote-email"
            || n == "x-remote-groups"
            || n == "x-original-user"
            || n == "x-original-groups"
            || n == "x-auth-user"
            || n == "x-auth-email"
            || n == "x-auth-request-user"
            || n == "x-auth-request-user-id"
            || n == "x-auth-request-uid"
            || n == "x-auth-request-name"
            || n == "x-auth-request-email"
            || n == "x-auth-request-preferred-username"
            || n == "x-auth-request-groups"
            || n == "x-auth-request-access-token"
            || n == "impersonate-user"
            || n == "impersonate-group"
            || n == "impersonate-uid"
            || n.starts_with("impersonate-extra-")
            || n == "x-forwarded-email"
            || n == "x-forwarded-access-token"
            || n == "cf-access-authenticated-user-email"
            || n == "cf-access-authenticated-user-id"
            || n == "x-authenticated-userid"
            || n == "x-authenticated-user-id"
            || n == "x-authenticated-user"
            || n == "x-authenticated-user-name"
            || n == "x-authenticated-user-email"
            || n == "x-authenticated-email"
            || n == "x-authenticated-groups"
            || n == "x-end-user"
            || n == "x-end-user-email"
            || n == "x-user-id"
            || n == "x-user"
            || n == "x-user-name"
            || n == "x-user-email"
            || n == "x-user-groups"
            || n == "x-principal"
            || n == "x-principal-id"
            || n == "x-principal-name"
            || n == "x-gitlab-user-id"
            || n == "x-gitlab-username"
            || n == "x-gitlab-user-login"
            || n == "x-gitlab-user-email"
            || n.starts_with("x-gitlab-user-")
            || n == "x-github-user-id"
            || n == "x-github-login"
            || n == "x-github-user-email"
            || n.starts_with("x-github-user-")
            || n == "x-bitbucket-user"
            || n == "x-bitbucket-uuid"
            || n == "x-bitbucket-user-email"
            || n.starts_with("x-bitbucket-user-")
            || n == "x-ms-client-principal"
            || n == "x-ms-client-principal-id"
            || n == "x-ms-client-principal-name"
            || n == "x-ms-client-principal-idp"
            || n == "x-ms-token-aad-id-token"
            || n == "x-ms-token-aad-access-token"
            || n == "x-ms-token-aad-refresh-token"
            || n == "x-ms-token-aad-expires-on"
            || n == "x-client-verify"
            || n == "x-client-dn"
            || n == "x-client-cert-chain"
            || n == "x-ssl-client-verify"
            || n == "x-ssl-client-dn"
            || n == "x-ssl-client-s-dn"
            || n == "x-ssl-client-i-dn"
            || n == "x-ssl-client-san"
            || n == "cookie"
            || n == "set-cookie"
            || n == "host"
            || n == "content-length"
            || n == "transfer-encoding"
            || n == "connection"
            || n == "forwarded"
            || n == "via"
            || n == "x-forwarded-for"
            || n == "x-forwarded-host"
            || n == "x-forwarded-proto"
            || n == "x-forwarded-protocol"
            || n == "x-forwarded-scheme"
            || n == "x-forwarded-ssl"
            || n == "x-url-scheme"
            || n == "x-forwarded-port"
            || n == "x-forwarded-server"
            || n == "x-forwarded-prefix"
            || n == "x-original-forwarded-host"
            || n == "x-original-forwarded-proto"
            || n == "x-original-forwarded-port"
            || n == "x-original-host"
            || n == "x-host"
            || n == "front-end-https"
            || n == "x-real-ip"
            || n == "x-forwarded-client-ip"
            || n == "x-original-forwarded-for"
            || n == "x-cluster-client-ip"
            || n == "x-envoy-external-address"
            || n == "x-envoy-peer-metadata"
            || n == "x-envoy-peer-metadata-id"
            || n == "fastly-client-ip"
            || n == "x-forwarded-client-cert"
            || n == "x-client-cert"
            || n == "x-ssl-client-cert"
            || n == "x-arr-clientcert"
            || n == "ssl-client-cert"
            || n == "x-http-method-override"
            || n == "x-method-override"
            || n == "x-http-method"
            || n == "x-original-url"
            || n == "x-original-uri"
            || n == "x-forwarded-uri"
            || n == "x-rewrite-url"
            || n == "x-rewrite-uri"
            || n == "x-envoy-original-path"
            || n == "x-envoy-original-url"
            || n == "x-client-ip"
            || n == "true-client-ip"
            || n == "cf-connecting-ip"
            || n == "proxy-authorization"
            || n == "proxy-authenticate"
            || n == "proxy-connection"
            || n == "te"
            || n == "trailer"
            || n == "upgrade"
            || n == "keep-alive"
            || !is_safe_header_name(trimmed_name)
            || !is_safe_header_value(value)
        {
            continue;
        }

        let pair_bytes = trimmed_name.len().saturating_add(value.len());
        if pair_bytes > MAX_HEADER_PAIR_BYTES {
            continue;
        }
        if !seen_names.insert(n) {
            continue;
        }
        let next_total = total_bytes.saturating_add(pair_bytes);
        if next_total > MAX_HEADER_TOTAL_BYTES {
            continue;
        }
        total_bytes = next_total;
        out.push((trimmed_name, value.as_str()));
    }

    out
}

fn is_safe_header_name(name: &str) -> bool {
    let trimmed = name.trim();
    const MAX_HEADER_NAME_LEN: usize = 128;
    !trimmed.is_empty()
        && trimmed.len() <= MAX_HEADER_NAME_LEN
        && trimmed
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b"!#$%&'*+-.^_`|~".contains(&b))
}

fn is_safe_header_value(value: &str) -> bool {
    const MAX_HEADER_VALUE_LEN: usize = 16 * 1024;
    value.len() <= MAX_HEADER_VALUE_LEN
        && value.is_ascii()
        && value.trim() == value
        && !value.chars().any(|c| c.is_control())
}

fn join_base_url_and_path(base_url: &str, path: &str) -> String {
    let left = base_url.trim().trim_end_matches('/');
    let right = path.trim();
    if right.starts_with('/') {
        format!("{left}{right}")
    } else {
        format!("{left}/{right}")
    }
}

fn read_response_bytes(resp: ureq::Response) -> Result<Vec<u8>, String> {
    const MAX_LLM_RESPONSE_BODY_LEN: usize = 2 * 1024 * 1024;
    let reader = resp.into_reader();
    read_limited_bytes(reader, MAX_LLM_RESPONSE_BODY_LEN, "llm-bridge response body")
}

fn read_limited_bytes(
    mut reader: impl std::io::Read,
    max_len: usize,
    label: &str,
) -> Result<Vec<u8>, String> {
    let mut out = Vec::new();
    (&mut reader)
        .take(max_len as u64 + 1)
        .read_to_end(&mut out)
        .map_err(|e| format!("response read: {e}"))?;
    if out.len() > max_len {
        return Err(format!("{label} too large"));
    }
    Ok(out)
}

#[cfg(test)]
#[path = "wasi_bridge_tests.rs"]
mod tests;
