//! TractorNativeBindings — host-side implementation of `tractor-bridge` WIT interface.
//!
//! Mirrors `WasiImports` from packages/tractor/src/lib/wasi-imports.ts.
//!
//! Implements traits generated by `wasmtime::component::bindgen!` in `plugin_host.rs`:
//!   - `refarm::plugin::types::Host`          — empty (shared types interface, no methods)
//!   - `refarm::plugin::tractor_bridge::Host` — CRDT/storage/telemetry host functions
//!   - `refarm::plugin::llm_bridge::Host`     — host-proxied HTTP completion boundary
//!
//! Return types use the WIT `result<T, plugin-error>` directly — no outer wasmtime::Result.

use crate::host::plugin_host::refarm::plugin::{
    llm_bridge::Host as LlmBridgeHost,
    tractor_bridge::Host as TractorBridgeHost,
    types::{Host as TypesHost, IdentityInfo, PluginError},
};
use crate::sync::NativeSync;
use crate::telemetry::TelemetryBus;
use std::io::Read as _;

#[derive(Debug, Clone, PartialEq, Eq)]
struct LlmRoute {
    provider: String,
    base_url: String,
    path: String,
}

/// Host-side implementation of the `tractor-bridge` WIT interface.
///
/// Holds references to NativeSync (storage) and TelemetryBus so plugin
/// calls are forwarded to the actual Tractor infrastructure.
pub struct TractorNativeBindings {
    pub plugin_id: String,
    pub sync: NativeSync,
    pub telemetry: TelemetryBus,
}

impl TractorNativeBindings {
    pub fn new(plugin_id: impl Into<String>, sync: NativeSync, telemetry: TelemetryBus) -> Self {
        Self {
            plugin_id: plugin_id.into(),
            sync,
            telemetry,
        }
    }
}

// ── types::Host ───────────────────────────────────────────────────────────────
//
// The `types` interface defines shared types (plugin-error, identity-info, etc.)
// but contains no functions. The generated `Host` trait has no methods.
impl TypesHost for TractorNativeBindings {}

// ── tractor_bridge::Host ──────────────────────────────────────────────────────
//
// Each method corresponds to one WIT function in `tractor-bridge`.
// Return type is `Result<T, PluginError>` — the WIT result directly.

#[wasmtime::component::__internal::async_trait]
impl TractorBridgeHost for TractorNativeBindings {
    /// Store (upsert) a JSON-LD node into the sovereign graph.
    async fn store_node(&mut self, node_json: String) -> Result<String, PluginError> {
        let value: serde_json::Value = match serde_json::from_str(&node_json) {
            Ok(v) => v,
            Err(e) => return Err(PluginError::InvalidSchema(e.to_string())),
        };

        let id = value["@id"]
            .as_str()
            .or_else(|| value["id"].as_str())
            .unwrap_or("urn:unknown")
            .to_string();

        let type_ = value["@type"]
            .as_str()
            .or_else(|| value["type"].as_str())
            .unwrap_or("Unknown")
            .to_string();

        self.sync
            .store_node(&id, &type_, None, &node_json, Some(&self.plugin_id))
            .map_err(|e| PluginError::Internal(e.to_string()))?;

        self.telemetry.emit_named(
            "plugin:store_node",
            Some(self.plugin_id.clone()),
            Some(serde_json::json!({ "nodeId": id, "type": type_ })),
        );

        Ok(id)
    }

    /// Retrieve a previously stored node by ID.
    async fn get_node(&mut self, id: String) -> Result<String, PluginError> {
        match self.sync.get_node(&id) {
            Ok(Some(payload)) => Ok(payload),
            Ok(None) => Err(PluginError::NotFound(id)),
            Err(e) => Err(PluginError::Internal(e.to_string())),
        }
    }

    /// Query nodes by @type, returning up to `limit` results.
    async fn query_nodes(
        &mut self,
        node_type: String,
        limit: u32,
    ) -> Result<Vec<String>, PluginError> {
        self.sync
            .query_nodes(&node_type)
            .map_err(|e| PluginError::Internal(e.to_string()))
            .map(|rows| {
                rows.into_iter()
                    .take(limit as usize)
                    .map(|r| r.payload)
                    .collect()
            })
    }

    /// Request a user-facing permission prompt. Always grants in Phase 4 (stub).
    async fn request_permission(&mut self, _capability: String, _reason: String) -> bool {
        true
    }

    /// Return the current user's identity information.
    async fn get_identity(&mut self) -> Result<IdentityInfo, PluginError> {
        Ok(IdentityInfo {
            identity_type: "guest".to_string(),
            storage_tier: "ephemeral".to_string(),
            identifier: "".to_string(),
        })
    }

    /// Discover a plugin that provides a named API (SPI pattern).
    async fn get_plugin_api(&mut self, api_name: String) -> Result<String, PluginError> {
        Err(PluginError::NotFound(format!(
            "no plugin provides api: {api_name}"
        )))
    }

    /// Emit a telemetry event from the plugin.
    async fn emit_telemetry(&mut self, event: String, payload: Option<String>) {
        let payload_val = payload.and_then(|p| serde_json::from_str(&p).ok());
        self.telemetry
            .emit_named(event, Some(self.plugin_id.clone()), payload_val);
    }
}

// ── llm_bridge::Host ─────────────────────────────────────────────────────────

#[wasmtime::component::__internal::async_trait]
impl LlmBridgeHost for TractorNativeBindings {
    async fn complete_http(
        &mut self,
        provider: String,
        base_url: String,
        path: String,
        headers: Vec<(String, String)>,
        body: Vec<u8>,
    ) -> Result<Vec<u8>, String> {
        llm_complete_http(&provider, &base_url, &path, &headers, &body)
    }
}

fn llm_complete_http(
    provider: &str,
    base_url: &str,
    path: &str,
    headers: &[(String, String)],
    body: &[u8],
) -> Result<Vec<u8>, String> {
    let expected = expected_llm_route_from_env();
    enforce_llm_route(provider, base_url, path, &expected)?;
    let provider = normalize_provider_name(provider);

    let url = join_base_url_and_path(base_url, path);
    let mut req = ureq::post(&url);

    for (name, value) in sanitized_plugin_headers(headers) {
        req = req.set(name, value);
    }

    if use_anthropic_auth(&provider) {
        let key = std::env::var("ANTHROPIC_API_KEY")
            .map_err(|_| "ANTHROPIC_API_KEY not set".to_string())?;
        req = req.set("x-api-key", &key);
    } else if use_openai_auth(&provider) {
        if let Ok(key) = std::env::var("OPENAI_API_KEY") {
            if !key.trim().is_empty() {
                req = req.set("authorization", &format!("Bearer {key}"));
            }
        }
    }

    match req.send_bytes(body) {
        Ok(resp) => read_response_bytes(resp),
        Err(ureq::Error::Status(code, resp)) => {
            let bytes = read_response_bytes(resp)?;
            Err(format!("HTTP {code}: {}", String::from_utf8_lossy(&bytes)))
        }
        Err(e) => Err(format!("http error: {e}")),
    }
}

fn use_anthropic_auth(provider: &str) -> bool {
    provider.trim() == "anthropic"
}

fn use_openai_auth(provider: &str) -> bool {
    let provider = provider.trim();
    provider != "ollama" && provider != "anthropic"
}

fn provider_name_from_env() -> String {
    std::env::var("LLM_PROVIDER")
        .ok()
        .map(|v| normalize_provider_name(&v))
        .filter(|v| !v.is_empty())
        .or_else(|| {
            std::env::var("LLM_DEFAULT_PROVIDER")
                .ok()
                .map(|v| normalize_provider_name(&v))
                .filter(|v| !v.is_empty())
        })
        .unwrap_or_else(|| "ollama".to_string())
}

fn normalize_provider_name(value: &str) -> String {
    value.trim().to_ascii_lowercase()
}

fn expected_llm_route_from_env() -> LlmRoute {
    let provider = provider_name_from_env();
    if provider == "anthropic" {
        return LlmRoute {
            provider,
            base_url: "https://api.anthropic.com".to_string(),
            path: "/v1/messages".to_string(),
        };
    }

    let base_url = std::env::var("LLM_BASE_URL").unwrap_or_else(|_| {
        if provider == "openai" {
            "https://api.openai.com".to_string()
        } else {
            "http://localhost:11434".to_string()
        }
    });

    LlmRoute {
        provider,
        base_url,
        path: "/v1/chat/completions".to_string(),
    }
}

fn enforce_llm_route(
    provider: &str,
    base_url: &str,
    path: &str,
    expected: &LlmRoute,
) -> Result<(), String> {
    let requested_provider = normalize_provider_name(provider);
    let expected_provider = normalize_provider_name(&expected.provider);
    if requested_provider != expected_provider {
        return Err(format!(
            "[blocked: llm-bridge provider mismatch: requested '{requested_provider}', expected '{}']",
            expected_provider
        ));
    }

    let requested_base = normalize_base_url(base_url)?;
    let expected_base = normalize_base_url(&expected.base_url)?;
    if requested_base != expected_base {
        return Err("[blocked: llm-bridge base_url not allowed]".to_string());
    }

    let requested_path = normalize_path(path);
    let expected_path = normalize_path(&expected.path);
    if requested_path != expected_path {
        return Err("[blocked: llm-bridge path not allowed]".to_string());
    }

    Ok(())
}

fn normalize_base_url(base_url: &str) -> Result<String, String> {
    let trimmed = base_url.trim().trim_end_matches('/');
    if trimmed.starts_with("http://") || trimmed.starts_with("https://") {
        Ok(trimmed.to_string())
    } else {
        Err("[blocked: llm-bridge base_url must use http(s)]".to_string())
    }
}

fn normalize_path(path: &str) -> String {
    let p = path.trim();
    let mut normalized = if p.starts_with('/') {
        p.to_string()
    } else {
        format!("/{p}")
    };

    while normalized.len() > 1 && normalized.ends_with('/') {
        normalized.pop();
    }

    normalized
}

fn sanitized_plugin_headers(headers: &[(String, String)]) -> Vec<(&str, &str)> {
    headers
        .iter()
        .filter(|(name, _)| {
            let n = name.trim().to_ascii_lowercase();
            n != "authorization" && n != "x-api-key"
        })
        .map(|(name, value)| (name.trim(), value.as_str()))
        .collect()
}

fn join_base_url_and_path(base_url: &str, path: &str) -> String {
    let left = base_url.trim().trim_end_matches('/');
    let right = path.trim();
    if right.starts_with('/') {
        format!("{left}{right}")
    } else {
        format!("{left}/{right}")
    }
}

fn read_response_bytes(resp: ureq::Response) -> Result<Vec<u8>, String> {
    let mut reader = resp.into_reader();
    let mut out = Vec::new();
    reader
        .read_to_end(&mut out)
        .map_err(|e| format!("response read: {e}"))?;
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn reset_llm_env() {
        for k in ["LLM_PROVIDER", "LLM_DEFAULT_PROVIDER", "LLM_BASE_URL"] {
            std::env::remove_var(k);
        }
    }

    #[test]
    fn expected_route_defaults_to_ollama() {
        reset_llm_env();
        let route = expected_llm_route_from_env();
        assert_eq!(
            route,
            LlmRoute {
                provider: "ollama".to_string(),
                base_url: "http://localhost:11434".to_string(),
                path: "/v1/chat/completions".to_string(),
            }
        );
    }

    #[test]
    fn expected_route_trims_provider_from_env() {
        reset_llm_env();
        std::env::set_var("LLM_PROVIDER", "  openai  ");

        let route = expected_llm_route_from_env();
        assert_eq!(route.provider, "openai");
        assert_eq!(route.base_url, "https://api.openai.com");
        assert_eq!(route.path, "/v1/chat/completions");

        reset_llm_env();
    }

    #[test]
    fn expected_route_normalizes_provider_case_from_env() {
        reset_llm_env();
        std::env::set_var("LLM_PROVIDER", "OpenAI");

        let route = expected_llm_route_from_env();
        assert_eq!(route.provider, "openai");
        assert_eq!(route.base_url, "https://api.openai.com");

        reset_llm_env();
    }

    #[test]
    fn expected_route_uses_default_provider_when_primary_is_blank() {
        reset_llm_env();
        std::env::set_var("LLM_PROVIDER", "   ");
        std::env::set_var("LLM_DEFAULT_PROVIDER", " openai ");

        let route = expected_llm_route_from_env();
        assert_eq!(route.provider, "openai");
        assert_eq!(route.base_url, "https://api.openai.com");

        reset_llm_env();
    }

    #[test]
    fn enforce_route_blocks_provider_mismatch() {
        let expected = LlmRoute {
            provider: "openai".to_string(),
            base_url: "https://api.openai.com".to_string(),
            path: "/v1/chat/completions".to_string(),
        };
        let err = enforce_llm_route(
            "ollama",
            "https://api.openai.com",
            "/v1/chat/completions",
            &expected,
        )
        .unwrap_err();
        assert!(err.contains("provider mismatch"));
    }

    #[test]
    fn enforce_route_blocks_base_url_mismatch() {
        let expected = LlmRoute {
            provider: "openai".to_string(),
            base_url: "https://api.openai.com".to_string(),
            path: "/v1/chat/completions".to_string(),
        };
        let err = enforce_llm_route(
            "openai",
            "https://attacker.example",
            "/v1/chat/completions",
            &expected,
        )
        .unwrap_err();
        assert!(err.contains("base_url not allowed"));
    }

    #[test]
    fn enforce_route_blocks_path_mismatch() {
        let expected = LlmRoute {
            provider: "openai".to_string(),
            base_url: "https://api.openai.com".to_string(),
            path: "/v1/chat/completions".to_string(),
        };
        let err = enforce_llm_route(
            "openai",
            "https://api.openai.com",
            "/v1/responses",
            &expected,
        )
        .unwrap_err();
        assert!(err.contains("path not allowed"));
    }

    #[test]
    fn enforce_route_blocks_non_http_base_url() {
        let expected = LlmRoute {
            provider: "openai".to_string(),
            base_url: "https://api.openai.com".to_string(),
            path: "/v1/chat/completions".to_string(),
        };
        let err = enforce_llm_route(
            "openai",
            "file:///tmp/evil",
            "/v1/chat/completions",
            &expected,
        )
        .unwrap_err();
        assert!(err.contains("base_url must use http(s)"));
    }

    #[test]
    fn enforce_route_accepts_path_without_leading_slash() {
        let expected = LlmRoute {
            provider: "openai".to_string(),
            base_url: "https://api.openai.com".to_string(),
            path: "/v1/chat/completions".to_string(),
        };
        let result = enforce_llm_route(
            "openai",
            "https://api.openai.com",
            "v1/chat/completions",
            &expected,
        );
        assert!(result.is_ok());
    }

    #[test]
    fn enforce_route_accepts_base_url_with_trailing_slash() {
        let expected = LlmRoute {
            provider: "openai".to_string(),
            base_url: "https://api.openai.com".to_string(),
            path: "/v1/chat/completions".to_string(),
        };
        let result = enforce_llm_route(
            "openai",
            "https://api.openai.com/",
            "/v1/chat/completions",
            &expected,
        );
        assert!(result.is_ok());
    }

    #[test]
    fn enforce_route_accepts_path_with_trailing_slash() {
        let expected = LlmRoute {
            provider: "openai".to_string(),
            base_url: "https://api.openai.com".to_string(),
            path: "/v1/chat/completions".to_string(),
        };
        let result = enforce_llm_route(
            "openai",
            "https://api.openai.com",
            "/v1/chat/completions/",
            &expected,
        );
        assert!(result.is_ok());
    }

    #[test]
    fn enforce_route_accepts_trimmed_provider_base_url_and_path() {
        let expected = LlmRoute {
            provider: "openai".to_string(),
            base_url: "https://api.openai.com".to_string(),
            path: "/v1/chat/completions".to_string(),
        };
        let result = enforce_llm_route(
            " openai ",
            " https://api.openai.com/ ",
            "  v1/chat/completions  ",
            &expected,
        );
        assert!(result.is_ok());
    }

    #[test]
    fn enforce_route_accepts_mixed_case_provider_name() {
        let expected = LlmRoute {
            provider: "openai".to_string(),
            base_url: "https://api.openai.com".to_string(),
            path: "/v1/chat/completions".to_string(),
        };
        let result = enforce_llm_route(
            "OpenAI",
            "https://api.openai.com",
            "/v1/chat/completions",
            &expected,
        );
        assert!(result.is_ok());
    }

    #[test]
    fn sanitized_headers_drop_sensitive_auth_keys() {
        let headers = vec![
            ("content-type".to_string(), "application/json".to_string()),
            ("authorization".to_string(), "Bearer fake".to_string()),
            ("x-api-key".to_string(), "fake-key".to_string()),
        ];
        let out = sanitized_plugin_headers(&headers);
        assert_eq!(out.len(), 1);
        assert_eq!(out[0].0, "content-type");
    }

    #[test]
    fn sanitized_headers_drop_sensitive_auth_keys_case_insensitive() {
        let headers = vec![
            ("Content-Type".to_string(), "application/json".to_string()),
            ("Authorization".to_string(), "Bearer fake".to_string()),
            ("X-API-KEY".to_string(), "fake-key".to_string()),
        ];
        let out = sanitized_plugin_headers(&headers);
        assert_eq!(out.len(), 1);
        assert_eq!(out[0].0, "Content-Type");
    }

    #[test]
    fn sanitized_headers_drop_sensitive_auth_keys_with_surrounding_spaces() {
        let headers = vec![
            (" content-type ".to_string(), "application/json".to_string()),
            (" authorization ".to_string(), "Bearer fake".to_string()),
            (" x-api-key ".to_string(), "fake-key".to_string()),
        ];
        let out = sanitized_plugin_headers(&headers);
        assert_eq!(out.len(), 1);
        assert_eq!(out[0].0, "content-type");
    }

    #[test]
    fn join_base_url_and_path_trims_surrounding_whitespace() {
        let url = join_base_url_and_path(" https://api.openai.com/ ", " /v1/chat/completions ");
        assert_eq!(url, "https://api.openai.com/v1/chat/completions");
    }

    #[test]
    fn auth_policy_treats_trimmed_ollama_as_no_host_auth() {
        assert!(!use_anthropic_auth("ollama"));
        assert!(!use_openai_auth("ollama"));

        assert!(!use_anthropic_auth(" ollama "));
        assert!(!use_openai_auth(" ollama "));
    }

    #[test]
    fn auth_policy_treats_trimmed_anthropic_as_anthropic_auth() {
        assert!(use_anthropic_auth("anthropic"));
        assert!(!use_openai_auth("anthropic"));

        assert!(use_anthropic_auth(" anthropic "));
        assert!(!use_openai_auth(" anthropic "));
    }
}
