export {
	buildChannelEffort,
	buildChannelEffortPath,
	buildChannelEffortsPath,
	CHANNEL_CONTROL_SURFACE_OPERATION_UNSUPPORTED_ERROR,
	decodeChannel,
	hasChannelControlCapability,
	encodeChannel,
	isChannelEffortPayload,
	normalizeChannelContext,
	normalizeChannelSource,
	parseTaskTransport,
	assertChannelControlCapability,
	type ChannelControlSurfaceAdapter,
	type ChannelControlSurfaceCapabilities,
	type ChannelControlSurfaceOperation,
	type ChannelDispatchTransport,
	type DispatchTransport,
	isKnownChannelControlSurface,
	listKnownChannelControlSurfaces,
	resolveChannelControlSurfaceAdapter,
	resolveChannelFromTransport,
	setChannelControlSurfaceAdapter,
	removeChannelControlSurfaceAdapter,
	getRegisteredChannelControlSurface,
} from "./dispatch-surface.js";
