/**
 * The Extension Bench VS Code extension — the editor SHELL that binds the bench's generated
 * commands to CLI invocations and paints them as a tree. It is deliberately thin: the command set
 * + tree come from the bench's registry (via buildVscodeManifest → this package's package.json and
 * the ide model at runtime), so the editor surface is the same declare-once projection as the CLI,
 * TUI, and web. `activate()` registers each contributed command to run `dgk <verb>` in a terminal.
 *
 * Typed against a MINIMAL local `vscode` interface (the subset used) so the package doesn't pull
 * the heavy @types/vscode — the real `vscode` module is injected by the editor at runtime.
 */

// The minimal surface of the `vscode` module this extension uses.
interface VscodeApi {
	commands: { registerCommand(id: string, handler: () => void): Disposable };
	window: {
		createTerminal(name: string): { sendText(text: string): void; show(): void };
		registerTreeDataProvider(viewId: string, provider: TreeDataProvider): Disposable;
		showInformationMessage(message: string): void;
	};
	EventEmitter: new () => { event: unknown; fire(): void };
	TreeItem: new (label: string, collapsibleState?: number) => TreeItemLike;
	TreeItemCollapsibleState: { None: number; Collapsed: number; Expanded: number };
}
interface Disposable {
	dispose(): void;
}
interface TreeItemLike {
	label: string;
	command?: { command: string; title: string };
	contextValue?: string;
}
interface TreeDataProvider {
	getTreeItem(element: TreeNode): TreeItemLike;
	getChildren(element?: TreeNode): TreeNode[];
}
interface ExtensionContext {
	subscriptions: Disposable[];
}

/** A node in the bench's command tree — a group, or a command under it. */
interface TreeNode {
	kind: "group" | "command";
	label: string;
	commandId?: string;
	children?: TreeNode[];
}

/** The command tree the extension paints — read from the extension's own contributed commands.
 * (In a full build this would call `dgk ide --json`; here it is derived from package.json's
 * contributes at load, kept simple + offline.) */
function buildTree(contributes: { commands: Array<{ command: string; title: string; category: string }> }): TreeNode[] {
	const groups = new Map<string, TreeNode[]>();
	for (const c of contributes.commands) {
		// The tree group is the segment after the namespace category — fall back to "commands".
		const group = c.category || "commands";
		const list = groups.get(group) ?? [];
		list.push({ kind: "command", label: c.title, commandId: c.command });
		groups.set(group, list);
	}
	return [...groups.entries()].map(([label, children]) => ({ kind: "group", label, children }));
}

/** The command the extension runs for a verb — `dgk <verb>` (the verb name is the command id's tail). */
function verbFromCommandId(commandId: string): string {
	const dot = commandId.indexOf(".");
	return dot >= 0 ? commandId.slice(dot + 1) : commandId;
}

export function activate(context: ExtensionContext): void {
	// The editor injects the real `vscode` module; require it at runtime (never a build dep).
	// eslint-disable-next-line @typescript-eslint/no-require-imports
	const vscode = require("vscode") as VscodeApi;
	// The extension's own manifest — its contributed commands (generated by buildVscodeManifest).
	// eslint-disable-next-line @typescript-eslint/no-require-imports
	const pkg = require("../package.json") as { contributes: { commands: Array<{ command: string; title: string; category: string }> } };

	const terminalName = "Extension Bench";
	const runVerb = (commandId: string): void => {
		const term = vscode.window.createTerminal(terminalName);
		term.sendText(`dgk ${verbFromCommandId(commandId)}`);
		term.show();
	};

	// Register every contributed command to run its verb in a terminal.
	for (const c of pkg.contributes.commands) {
		context.subscriptions.push(vscode.commands.registerCommand(c.command, () => runVerb(c.command)));
	}

	// Paint the command tree in the bench's activity-bar view.
	const tree = buildTree(pkg.contributes);
	const provider: TreeDataProvider = {
		getTreeItem(node) {
			const collapsible = node.kind === "group" ? vscode.TreeItemCollapsibleState.Expanded : vscode.TreeItemCollapsibleState.None;
			const item = new vscode.TreeItem(node.label, collapsible);
			if (node.kind === "command" && node.commandId) {
				item.command = { command: node.commandId, title: node.label };
			}
			return item;
		},
		getChildren(node) {
			return node ? (node.children ?? []) : tree;
		},
	};
	context.subscriptions.push(vscode.window.registerTreeDataProvider("dgk.commands", provider));
	vscode.window.showInformationMessage("Extension Bench: the bench's verbs are in the command palette and the tree.");
}

export function deactivate(): void {
	/* nothing to clean up — the subscriptions are disposed by the editor */
}
