// Use the bindings generated by wit-bindgen
wit_bindgen::generate!({
    world: "refarm-plugin",
    path: "../../wit/refarm-sdk.wit",
});

use exports::refarm::plugin::integration::Guest;
use refarm::plugin::tractor_bridge::*;

struct MyPlugin;

impl Guest for MyPlugin {
    fn setup() -> Result<(), PluginError> {
        log(LogLevel::Info, "Rust plugin setup called!");
        
        let granted = request_permission(
            "network:https://api.github.com",
            "Needed to fetch your repositories"
        );
        
        if granted {
            Ok(())
        } else {
            Err(PluginError::NotPermitted("Permission denied".to_string()))
        }
    }

    fn ingest() -> Result<u32, PluginError> {
        log(LogLevel::Info, "Rust plugin ingest called!");
        // Logic to fetch and store nodes would go here
        Ok(0)
    }

    fn push(_payload: String) -> Result<(), PluginError> {
        Ok(())
    }

    fn teardown() {
        // Cleanup logic
    }

    fn get_help_nodes() -> Result<Vec<String>, PluginError> {
        Ok(vec![])
    }

    fn metadata() -> PluginMetadata {
        PluginMetadata {
            name: "Rust Template Plugin".to_string(),
            version: "0.1.0".to_string(),
            description: "A template for building Refarm plugins in Rust".to_string(),
            supported_types: vec!["Repository".to_string()],
            required_capabilities: vec!["network:https://api.github.com".to_string()],
        }
    }

    fn on_event(_event: String, _payload: Option<String>) {
        // Handle system events
    }
}

export!(MyPlugin);
