#!/usr/bin/env bash
set -euo pipefail

TARGET_USER="${1:-vscode}"
PROJECT_DIR="${2:-/workspaces/refarm}"
INIT_FILE="/home/${TARGET_USER}/.farm-init.sh"

cat > "$INIT_FILE" <<INIT
[ -f /home/${TARGET_USER}/.bashrc ] && . /home/${TARGET_USER}/.bashrc
export HOME=/home/${TARGET_USER}
export USER=${TARGET_USER}
export LANG=pt_BR.UTF-8
export LC_ALL=pt_BR.UTF-8
export LANGUAGE=pt_BR:pt:en
export TERM=\${TERM:-xterm-256color}
export COLORTERM=\${COLORTERM:-truecolor}
export PNPM_HOME=/home/${TARGET_USER}/.local/share/pnpm
export NPM_CONFIG_PREFIX=/home/${TARGET_USER}/.npm-global
export CARGO_HOME=/usr/local/cargo
export RUSTUP_HOME=/usr/local/rustup
export CARGO_TERM_COLOR=always
export PATH=/home/${TARGET_USER}/.local/share/pnpm:/home/${TARGET_USER}/.npm-global/bin:/home/${TARGET_USER}/.cargo-local/bin:/home/${TARGET_USER}/.local/bin:/usr/local/cargo/bin:\$PATH
cd "${PROJECT_DIR}"
INIT

chmod 644 "$INIT_FILE"
exec su -s /bin/bash "$TARGET_USER" -- --init-file "$INIT_FILE"
