name: "Playwright Cache Wrapper"
description: "Cache Playwright browser binaries"

inputs:
  path:
    description: "Playwright browser cache directory"
    required: false
    default: ~/.cache/ms-playwright
  key:
    description: "Primary cache key"
    required: true
  restore-keys:
    description: "Restore key prefixes"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Cache Playwright browsers
      id: cache
      uses: ./.github/actions/cache
      with:
        path: ${{ inputs.path }}
        key: ${{ inputs.key }}
        restore-keys: ${{ inputs.restore-keys }}
