import { PluginManifest } from "@refarm.dev/plugin-manifest";
import { TelemetryEvent } from "./telemetry";
import type { PluginInstance } from "./instance-handle";

/**
 * Abstraction over plugin instantiation strategies.
 *
 * Different execution contexts (main thread, WebWorker, ServiceWorker, Edge)
 * require different instantiation mechanisms. Each `PluginRunner` encapsulates
 * one strategy and declares which contexts it supports.
 *
 * `PluginHost` calls `resolveRunner(manifest)` to pick the appropriate runner
 * based on `manifest.executionContext.preferred`, falling back gracefully.
 *
 * @see ExecutionContextConfig in @refarm.dev/plugin-manifest
 */
export interface PluginRunner {
  /**
   * Returns true if this runner can operate in the current environment.
   * Used for automatic fallback when the preferred context is unavailable.
   */
  supports(manifest: PluginManifest): boolean;

  /**
   * Instantiate the plugin from a WASM buffer and return a live PluginInstance.
   *
   * @param manifest     - The plugin's manifest (used for id, name, capabilities)
   * @param wasmBuffer   - Raw WASM binary already fetched and integrity-verified
   * @param imports      - WASI and bridge imports generated by WasiImports
   * @param emit         - Telemetry emitter for plugin events
   * @param onTerminate  - Callback invoked when the plugin is terminated
   */
  instantiate(
    manifest: PluginManifest,
    wasmBuffer: ArrayBuffer,
    imports: Record<string, any>,
    emit: (data: TelemetryEvent) => void,
    onTerminate: (id: string) => void,
  ): Promise<PluginInstance>;
}
