// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type Keypair = refarm::heartwood::types::Keypair;
pub type HeartwoodError = refarm::heartwood::types::HeartwoodError;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_sign_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: *mut u8,
    arg3: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let len1 = arg3;
    let result2 = T::sign(
        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
        _rt::Vec::from_raw_parts(arg2.cast(), len1, len1),
    );
    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result2 {
        Ok(e) => {
            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
            let vec4 = (e).into_boxed_slice();
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();
            ::core::mem::forget(vec4);
            *ptr3.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
            *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4
                .cast_mut();
        }
        Err(e) => {
            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
            use refarm::heartwood::types::HeartwoodError as V6;
            match e {
                V6::InvalidSignature => {
                    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32)
                        as u8;
                }
                V6::Unauthorized => {
                    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32)
                        as u8;
                }
                V6::InternalError(e) => {
                    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (2i32)
                        as u8;
                    let vec5 = (e.into_bytes()).into_boxed_slice();
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    ::core::mem::forget(vec5);
                    *ptr3.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr3
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr5.cast_mut();
                }
            }
        }
    };
    ptr3
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_sign<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base3 = l1;
            let len3 = l2;
            _rt::cabi_dealloc(base3, len3 * 1, 1);
        }
        _ => {
            let l4 = i32::from(
                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
            );
            match l4 {
                0 => {}
                1 => {}
                _ => {
                    let l5 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l6 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l5, l6, 1);
                }
            }
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_verify_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: *mut u8,
    arg3: usize,
    arg4: *mut u8,
    arg5: usize,
) -> i32 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let len1 = arg3;
    let len2 = arg5;
    let result3 = T::verify(
        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
        _rt::Vec::from_raw_parts(arg2.cast(), len1, len1),
        _rt::Vec::from_raw_parts(arg4.cast(), len2, len2),
    );
    match result3 {
        true => 1,
        false => 0,
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_generate_keypair_cabi<T: Guest>() -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::generate_keypair();
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let refarm::heartwood::types::Keypair {
        public_key: public_key2,
        secret_key: secret_key2,
    } = result0;
    let vec3 = (public_key2).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr1.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    let vec4 = (secret_key2).into_boxed_slice();
    let ptr4 = vec4.as_ptr().cast::<u8>();
    let len4 = vec4.len();
    ::core::mem::forget(vec4);
    *ptr1.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
    *ptr1.add(2 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4
        .cast_mut();
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_generate_keypair<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base2 = l0;
    let len2 = l1;
    _rt::cabi_dealloc(base2, len2 * 1, 1);
    let l3 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l4 = *arg0.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base5 = l3;
    let len5 = l4;
    _rt::cabi_dealloc(base5, len5 * 1, 1);
}
pub trait Guest {
    fn sign(
        payload: _rt::Vec<u8>,
        secret_key: _rt::Vec<u8>,
    ) -> Result<_rt::Vec<u8>, HeartwoodError>;
    fn verify(
        payload: _rt::Vec<u8>,
        signature: _rt::Vec<u8>,
        public_key: _rt::Vec<u8>,
    ) -> bool;
    fn generate_keypair() -> Keypair;
}
#[doc(hidden)]
macro_rules! __export_world_core_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "sign")] unsafe extern "C" fn
        export_sign(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8, arg3 : usize,) -> *
        mut u8 { unsafe { $($path_to_types)*:: _export_sign_cabi::<$ty > (arg0, arg1,
        arg2, arg3) } } #[unsafe (export_name = "cabi_post_sign")] unsafe extern "C" fn
        _post_return_sign(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_sign::<$ty > (arg0) } } #[unsafe (export_name = "verify")] unsafe
        extern "C" fn export_verify(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8, arg3
        : usize, arg4 : * mut u8, arg5 : usize,) -> i32 { unsafe { $($path_to_types)*::
        _export_verify_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4, arg5) } } #[unsafe
        (export_name = "generate-keypair")] unsafe extern "C" fn
        export_generate_keypair() -> * mut u8 { unsafe { $($path_to_types)*::
        _export_generate_keypair_cabi::<$ty > () } } #[unsafe (export_name =
        "cabi_post_generate-keypair")] unsafe extern "C" fn
        _post_return_generate_keypair(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_generate_keypair::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_core_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 4 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 4 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod refarm {
    pub mod heartwood {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct Keypair {
                pub public_key: _rt::Vec<u8>,
                pub secret_key: _rt::Vec<u8>,
            }
            impl ::core::fmt::Debug for Keypair {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Keypair")
                        .field("public-key", &self.public_key)
                        .field("secret-key", &self.secret_key)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub enum HeartwoodError {
                InvalidSignature,
                Unauthorized,
                InternalError(_rt::String),
            }
            impl ::core::fmt::Debug for HeartwoodError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        HeartwoodError::InvalidSignature => {
                            f.debug_tuple("HeartwoodError::InvalidSignature").finish()
                        }
                        HeartwoodError::Unauthorized => {
                            f.debug_tuple("HeartwoodError::Unauthorized").finish()
                        }
                        HeartwoodError::InternalError(e) => {
                            f.debug_tuple("HeartwoodError::InternalError")
                                .field(e)
                                .finish()
                        }
                    }
                }
            }
            impl ::core::fmt::Display for HeartwoodError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for HeartwoodError {}
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_core_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_core_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_core_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:refarm:heartwood:core:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 489] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xee\x02\x01A\x02\x01\
A\x0e\x01B\x05\x01p}\x01r\x02\x0apublic-key\0\x0asecret-key\0\x04\0\x07keypair\x03\
\0\x01\x01q\x03\x11invalid-signature\0\0\x0cunauthorized\0\0\x0einternal-error\x01\
s\0\x04\0\x0fheartwood-error\x03\0\x03\x03\0\x16refarm:heartwood/types\x05\0\x02\
\x03\0\0\x07keypair\x03\0\x07keypair\x03\0\x01\x02\x03\0\0\x0fheartwood-error\x03\
\0\x0fheartwood-error\x03\0\x03\x01p}\x01j\x01\x05\x01\x04\x01@\x02\x07payload\x05\
\x0asecret-key\x05\0\x06\x04\0\x04sign\x01\x07\x01@\x03\x07payload\x05\x09signat\
ure\x05\x0apublic-key\x05\0\x7f\x04\0\x06verify\x01\x08\x01@\0\0\x02\x04\0\x10ge\
nerate-keypair\x01\x09\x04\0\x15refarm:heartwood/core\x04\0\x0b\x0a\x01\0\x04cor\
e\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10\
wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
