import {
	parseProcessCatalog,
	ProcessDeclarationError,
	type ProcessDeclaration,
} from "@refarm.dev/process-contract-v1";
import { describe, expect, it } from "vitest";

import {
	quoteExecArgument,
	renderSystemdTimer,
	renderSystemdUnit,
	systemdRestartValue,
	systemdUnitName,
	systemdUnitPath,
	systemdUserUnitDir,
} from "./unit.js";

function declare(overrides: Record<string, unknown> = {}): ProcessDeclaration {
	const catalog = parseProcessCatalog({
		processes: {
			"web-serve": {
				description: "the mesh distribution server the phone bootstraps from",
				command: ["/usr/local/bin/refarm", "web", "serve", ".refarm/dist/farm-client"],
				workingDirectory: "/home/op/github/refarm",
				restart: "always",
				stopTimeoutSeconds: 20,
				restartDelaySeconds: 5,
				...overrides,
			},
		},
	});
	return catalog.get("web-serve")!;
}

describe("where a unit goes", () => {
	it("names the unit with the refarm prefix, so refarm's units are identifiable", () => {
		expect(systemdUnitName("web-serve")).toBe("refarm-web-serve.service");
	});

	it("honours XDG_CONFIG_HOME — which is what makes this testable without touching ~/.config", () => {
		expect(systemdUserUnitDir({ XDG_CONFIG_HOME: "/tmp/throwaway/config", HOME: "/home/op" })).toBe(
			"/tmp/throwaway/config/systemd/user",
		);
		expect(systemdUnitPath("web-serve", { XDG_CONFIG_HOME: "/tmp/throwaway/config" })).toBe(
			"/tmp/throwaway/config/systemd/user/refarm-web-serve.service",
		);
	});

	it("falls back to ~/.config, and refuses honestly when it has neither", () => {
		expect(systemdUserUnitDir({ HOME: "/home/op" })).toBe("/home/op/.config/systemd/user");
		expect(() => systemdUserUnitDir({})).toThrow(ProcessDeclarationError);
	});
});

describe("the generated unit is well-formed and says what it does", () => {
	const unit = renderSystemdUnit(declare());

	it("has the three sections systemd requires, in order", () => {
		expect(unit.indexOf("[Unit]")).toBeGreaterThanOrEqual(0);
		expect(unit.indexOf("[Service]")).toBeGreaterThan(unit.indexOf("[Unit]"));
		expect(unit.indexOf("[Install]")).toBeGreaterThan(unit.indexOf("[Service]"));
		expect(unit).toContain("WantedBy=default.target");
		expect(unit.endsWith("\n")).toBe(true);
	});

	it("every non-comment, non-blank line is a section header or a KEY=value pair", () => {
		for (const line of unit.split("\n")) {
			if (!line.trim() || line.startsWith("#")) continue;
			expect(line).toMatch(/^(\[[A-Za-z]+\]|[A-Za-z][A-Za-z0-9]*=.*)$/);
		}
	});

	it("carries the declared command as an absolute ExecStart", () => {
		expect(unit).toContain("ExecStart=/usr/local/bin/refarm web serve .refarm/dist/farm-client");
		expect(unit).toContain("WorkingDirectory=/home/op/github/refarm");
		expect(unit).toContain("Type=simple");
	});

	it("carries the declared RESTART POLICY and its cooldown", () => {
		expect(unit).toContain("Restart=always");
		expect(unit).toContain("RestartSec=5");
		expect(unit).toContain("StartLimitIntervalSec=60");
		expect(unit).toContain("StartLimitBurst=5");
	});

	it("carries the STOP TIMEOUT — the ordered termination refarm gets for free here", () => {
		expect(unit).toContain("TimeoutStopSec=20");
		expect(unit).toContain("KillMode=mixed");
		expect(unit).toMatch(/handle no SIGTERM today/);
	});

	it("spells the restart policies in systemd's own vocabulary", () => {
		expect(systemdRestartValue("always")).toBe("always");
		expect(systemdRestartValue("on-failure")).toBe("on-failure");
		expect(systemdRestartValue("never")).toBe("no");
		expect(renderSystemdUnit(declare({ restart: "never" }))).toContain("Restart=no");
		expect(renderSystemdUnit(declare({ restart: "on-failure" }))).toContain("Restart=on-failure");
	});

	// The header names WHOEVER the caller said generated it, not a brand this package spells
	// (ADR-087, ISS-114). Both halves are pinned: what a caller supplies, and what an unsupplied
	// caller gets — a truthful comment that names no tool rather than the wrong one.
	it("explains itself in a header, so the file is legible a year later", () => {
		const named = renderSystemdUnit(declare(), {
			generator: "my-app",
			rewriteCommand: "my-app process install web-serve",
		});
		expect(named).toContain('# Generated by my-app from the "processes" declaration');
		expect(named).toContain("# Process: web-serve");
		expect(named).toContain("my-app process install web-serve");

		expect(unit).toContain('# Generated by the process supervisor from the "processes" declaration');
		expect(unit).toContain("`re-running the installer` rewrites this file");
	});

	it("renders declared environment, and the parser has already refused secrets", () => {
		const withEnv = renderSystemdUnit(declare({ environment: { NODE_ENV: "production" } }));
		expect(withEnv).toContain('Environment="NODE_ENV=production"');
	});
});

describe("what would silently become a different command", () => {
	it("escapes % so systemd does not expand a specifier inside a path or argument", () => {
		const unit = renderSystemdUnit(
			declare({ command: ["/usr/local/bin/refarm", "web", "serve", "/srv/100%-done"] }),
		);
		expect(unit).toContain("/srv/100%%-done");
		expect(unit).not.toContain("/srv/100%-done");
	});

	it("quotes an argument holding whitespace or a quote, and leaves plain ones bare", () => {
		expect(quoteExecArgument("serve")).toBe("serve");
		expect(quoteExecArgument("two words")).toBe('"two words"');
		expect(quoteExecArgument('say "hi"')).toBe('"say \\"hi\\""');
		expect(quoteExecArgument("back\\slash")).toBe('"back\\\\slash"');
		expect(renderSystemdUnit(declare({ command: ["/bin/echo", "two words"] }))).toContain(
			'ExecStart=/bin/echo "two words"',
		);
	});

	it("refuses a relative executable — systemd does not search PATH", () => {
		expect(() => renderSystemdUnit(declare({ command: ["refarm", "web", "serve"] }))).toThrow(
			/command\[0\] must be an ABSOLUTE path/,
		);
		expect(() => renderSystemdUnit(declare({ command: ["refarm"] }))).toThrow(/command -v refarm/);
	});
});

describe("a periodic declaration renders a timer, and the service stops pretending to be one", () => {
	/** The customer, and the reason this field exists: ISS-066. A complete cron evaluator, a
	 *  fire-once ledger and a host command all existed; NOTHING CALLED THEM ON A CLOCK. */
	const TICK: ProcessDeclaration = {
		name: "automations",
		description: "fire due local scheduled work",
		command: ["/home/op/.local/bin/refarm", "project", "automations", "tick", "--submit"],
		workingDirectory: "/home/op/repo",
		environment: {},
		restart: "never",
		stopTimeoutSeconds: 20,
		restartDelaySeconds: 5,
		everySeconds: 60,
	};

	it("makes the service oneshot and gives it NO [Install]", () => {
		const unit = renderSystemdUnit(TICK);
		expect(unit).toContain("Type=oneshot");
		expect(unit).not.toContain("Type=simple");
		// A periodic service enabled on its own runs once at boot and never again, which looks
		// exactly like a working install. The timer is what gets enabled.
		expect(unit).not.toContain("[Install]");
		expect(unit).not.toContain("WantedBy=");
		// `Restart=always` on a `Type=oneshot` is refused by systemd itself; "never" emits none.
		expect(unit).not.toContain("Restart=");
	});

	it("leaves a long-running declaration exactly as it was", () => {
		const unit = renderSystemdUnit({ ...TICK, everySeconds: undefined, restart: "always" });
		expect(unit).toContain("Type=simple");
		expect(unit).toContain("Restart=always");
		expect(unit).toContain("WantedBy=default.target");
	});

	it("skips a missed window rather than catching up — spec D5, and NOT systemd's careless default", () => {
		// `Persistent=true` fires immediately at boot for every window that passed, so a week
		// offline becomes a week of backlog at once. Every customer here wants now or nothing.
		const timer = renderSystemdTimer(TICK);
		expect(timer).toContain("Persistent=false");
		expect(timer).not.toContain("Persistent=true");
	});

	it("asks for second accuracy, because a minute of slack skips a whole minute", () => {
		// systemd spends up to ONE MINUTE of slack by default to batch wakeups. Due-ness is decided
		// at minute resolution with a fire key to match, so that slack can drop a minute entirely —
		// and a skipped minute is a skipped automation nothing reports.
		expect(renderSystemdTimer(TICK)).toContain("AccuracySec=1s");
	});

	it("fires the FIRST time too", () => {
		// `OnUnitActiveSec` alone never fires initially: there is no previous activation to measure
		// from. The pair is the idiom.
		const timer = renderSystemdTimer(TICK);
		expect(timer).toContain("OnBootSec=60s");
		expect(timer).toContain("OnUnitActiveSec=60s");
		expect(timer).toContain("Unit=refarm-automations.service");
		expect(timer).toContain("WantedBy=timers.target");
	});

	it("refuses to render a timer for something that declared no interval", () => {
		expect(() => renderSystemdTimer({ ...TICK, everySeconds: undefined })).toThrow(
			/long-running process/u,
		);
	});

	it("names the pair in both files, so neither is a mystery on its own", () => {
		expect(renderSystemdUnit(TICK)).toContain("refarm-automations.timer");
		expect(renderSystemdTimer(TICK)).toContain("every 60s");
	});
});
