import {
	parseProcessCatalog,
	ProcessDeclarationError,
	type ProcessDeclaration,
} from "@refarm.dev/process-contract-v1";
import { describe, expect, it } from "vitest";

import {
	quoteExecArgument,
	renderSystemdUnit,
	systemdRestartValue,
	systemdUnitName,
	systemdUnitPath,
	systemdUserUnitDir,
} from "./unit.js";

function declare(overrides: Record<string, unknown> = {}): ProcessDeclaration {
	const catalog = parseProcessCatalog({
		processes: {
			"web-serve": {
				description: "the mesh distribution server the phone bootstraps from",
				command: ["/usr/local/bin/refarm", "web", "serve", ".refarm/dist/farm-client"],
				workingDirectory: "/home/op/github/refarm",
				restart: "always",
				stopTimeoutSeconds: 20,
				restartDelaySeconds: 5,
				...overrides,
			},
		},
	});
	return catalog.get("web-serve")!;
}

describe("where a unit goes", () => {
	it("names the unit with the refarm prefix, so refarm's units are identifiable", () => {
		expect(systemdUnitName("web-serve")).toBe("refarm-web-serve.service");
	});

	it("honours XDG_CONFIG_HOME — which is what makes this testable without touching ~/.config", () => {
		expect(systemdUserUnitDir({ XDG_CONFIG_HOME: "/tmp/throwaway/config", HOME: "/home/op" })).toBe(
			"/tmp/throwaway/config/systemd/user",
		);
		expect(systemdUnitPath("web-serve", { XDG_CONFIG_HOME: "/tmp/throwaway/config" })).toBe(
			"/tmp/throwaway/config/systemd/user/refarm-web-serve.service",
		);
	});

	it("falls back to ~/.config, and refuses honestly when it has neither", () => {
		expect(systemdUserUnitDir({ HOME: "/home/op" })).toBe("/home/op/.config/systemd/user");
		expect(() => systemdUserUnitDir({})).toThrow(ProcessDeclarationError);
	});
});

describe("the generated unit is well-formed and says what it does", () => {
	const unit = renderSystemdUnit(declare());

	it("has the three sections systemd requires, in order", () => {
		expect(unit.indexOf("[Unit]")).toBeGreaterThanOrEqual(0);
		expect(unit.indexOf("[Service]")).toBeGreaterThan(unit.indexOf("[Unit]"));
		expect(unit.indexOf("[Install]")).toBeGreaterThan(unit.indexOf("[Service]"));
		expect(unit).toContain("WantedBy=default.target");
		expect(unit.endsWith("\n")).toBe(true);
	});

	it("every non-comment, non-blank line is a section header or a KEY=value pair", () => {
		for (const line of unit.split("\n")) {
			if (!line.trim() || line.startsWith("#")) continue;
			expect(line).toMatch(/^(\[[A-Za-z]+\]|[A-Za-z][A-Za-z0-9]*=.*)$/);
		}
	});

	it("carries the declared command as an absolute ExecStart", () => {
		expect(unit).toContain("ExecStart=/usr/local/bin/refarm web serve .refarm/dist/farm-client");
		expect(unit).toContain("WorkingDirectory=/home/op/github/refarm");
		expect(unit).toContain("Type=simple");
	});

	it("carries the declared RESTART POLICY and its cooldown", () => {
		expect(unit).toContain("Restart=always");
		expect(unit).toContain("RestartSec=5");
		expect(unit).toContain("StartLimitIntervalSec=60");
		expect(unit).toContain("StartLimitBurst=5");
	});

	it("carries the STOP TIMEOUT — the ordered termination refarm gets for free here", () => {
		expect(unit).toContain("TimeoutStopSec=20");
		expect(unit).toContain("KillMode=mixed");
		expect(unit).toMatch(/handle no SIGTERM today/);
	});

	it("spells the restart policies in systemd's own vocabulary", () => {
		expect(systemdRestartValue("always")).toBe("always");
		expect(systemdRestartValue("on-failure")).toBe("on-failure");
		expect(systemdRestartValue("never")).toBe("no");
		expect(renderSystemdUnit(declare({ restart: "never" }))).toContain("Restart=no");
		expect(renderSystemdUnit(declare({ restart: "on-failure" }))).toContain("Restart=on-failure");
	});

	// The header names WHOEVER the caller said generated it, not a brand this package spells
	// (ADR-087, ISS-114). Both halves are pinned: what a caller supplies, and what an unsupplied
	// caller gets — a truthful comment that names no tool rather than the wrong one.
	it("explains itself in a header, so the file is legible a year later", () => {
		const named = renderSystemdUnit(declare(), {
			generator: "my-app",
			rewriteCommand: "my-app process install web-serve",
		});
		expect(named).toContain('# Generated by my-app from the "processes" declaration');
		expect(named).toContain("# Process: web-serve");
		expect(named).toContain("my-app process install web-serve");

		expect(unit).toContain('# Generated by the process supervisor from the "processes" declaration');
		expect(unit).toContain("`re-running the installer` rewrites this file");
	});

	it("renders declared environment, and the parser has already refused secrets", () => {
		const withEnv = renderSystemdUnit(declare({ environment: { NODE_ENV: "production" } }));
		expect(withEnv).toContain('Environment="NODE_ENV=production"');
	});
});

describe("what would silently become a different command", () => {
	it("escapes % so systemd does not expand a specifier inside a path or argument", () => {
		const unit = renderSystemdUnit(
			declare({ command: ["/usr/local/bin/refarm", "web", "serve", "/srv/100%-done"] }),
		);
		expect(unit).toContain("/srv/100%%-done");
		expect(unit).not.toContain("/srv/100%-done");
	});

	it("quotes an argument holding whitespace or a quote, and leaves plain ones bare", () => {
		expect(quoteExecArgument("serve")).toBe("serve");
		expect(quoteExecArgument("two words")).toBe('"two words"');
		expect(quoteExecArgument('say "hi"')).toBe('"say \\"hi\\""');
		expect(quoteExecArgument("back\\slash")).toBe('"back\\\\slash"');
		expect(renderSystemdUnit(declare({ command: ["/bin/echo", "two words"] }))).toContain(
			'ExecStart=/bin/echo "two words"',
		);
	});

	it("refuses a relative executable — systemd does not search PATH", () => {
		expect(() => renderSystemdUnit(declare({ command: ["refarm", "web", "serve"] }))).toThrow(
			/command\[0\] must be an ABSOLUTE path/,
		);
		expect(() => renderSystemdUnit(declare({ command: ["refarm"] }))).toThrow(/command -v refarm/);
	});
});
