name: "Upload Pages Artifact"
description: "Secure wrapper for actions/upload-pages-artifact with pinned hash."

inputs:
  path:
    description: "Directory containing the static assets"
    required: true
    default: "dist"

runs:
  using: "composite"
  steps:
    - name: Upload artifact
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
      with:
        path: ${{ inputs.path }}
