//! TractorNativeBindings — host-side implementation of `tractor-bridge` WIT interface.
//!
//! Mirrors `WasiImports` from packages/tractor/src/lib/wasi-imports.ts.
//!
//! Implements two traits generated by `wasmtime::component::bindgen!` in `plugin_host.rs`:
//!   - `refarm::plugin::types::Host`         — empty (shared types interface, no methods)
//!   - `refarm::plugin::tractor_bridge::Host` — 7 host functions called by plugins
//!
//! Return types use the WIT `result<T, plugin-error>` directly — no outer wasmtime::Result.

use crate::host::plugin_host::refarm::plugin::{
    tractor_bridge::Host as TractorBridgeHost,
    types::{Host as TypesHost, IdentityInfo, PluginError},
};
use crate::sync::NativeSync;
use crate::telemetry::TelemetryBus;

/// Host-side implementation of the `tractor-bridge` WIT interface.
///
/// Holds references to NativeSync (storage) and TelemetryBus so plugin
/// calls are forwarded to the actual Tractor infrastructure.
pub struct TractorNativeBindings {
    pub plugin_id: String,
    pub sync: NativeSync,
    pub telemetry: TelemetryBus,
}

impl TractorNativeBindings {
    pub fn new(plugin_id: impl Into<String>, sync: NativeSync, telemetry: TelemetryBus) -> Self {
        Self {
            plugin_id: plugin_id.into(),
            sync,
            telemetry,
        }
    }
}

// ── types::Host ───────────────────────────────────────────────────────────────
//
// The `types` interface defines shared types (plugin-error, identity-info, etc.)
// but contains no functions. The generated `Host` trait has no methods.
impl TypesHost for TractorNativeBindings {}

// ── tractor_bridge::Host ──────────────────────────────────────────────────────
//
// Each method corresponds to one WIT function in `tractor-bridge`.
// Return type is `Result<T, PluginError>` — the WIT result directly.

#[wasmtime::component::__internal::async_trait]
impl TractorBridgeHost for TractorNativeBindings {
    /// Store (upsert) a JSON-LD node into the sovereign graph.
    async fn store_node(&mut self, node_json: String) -> Result<String, PluginError> {
        let value: serde_json::Value = match serde_json::from_str(&node_json) {
            Ok(v) => v,
            Err(e) => return Err(PluginError::InvalidSchema(e.to_string())),
        };

        let id = value["@id"]
            .as_str()
            .or_else(|| value["id"].as_str())
            .unwrap_or("urn:unknown")
            .to_string();

        let type_ = value["@type"]
            .as_str()
            .or_else(|| value["type"].as_str())
            .unwrap_or("Unknown")
            .to_string();

        self.sync
            .store_node(&id, &type_, None, &node_json, Some(&self.plugin_id))
            .map_err(|e| PluginError::Internal(e.to_string()))?;

        self.telemetry.emit_named(
            "plugin:store_node",
            Some(self.plugin_id.clone()),
            Some(serde_json::json!({ "nodeId": id, "type": type_ })),
        );

        Ok(id)
    }

    /// Retrieve a previously stored node by ID.
    async fn get_node(&mut self, id: String) -> Result<String, PluginError> {
        match self.sync.get_node(&id) {
            Ok(Some(payload)) => Ok(payload),
            Ok(None) => Err(PluginError::NotFound(id)),
            Err(e) => Err(PluginError::Internal(e.to_string())),
        }
    }

    /// Query nodes by @type, returning up to `limit` results.
    async fn query_nodes(
        &mut self,
        node_type: String,
        limit: u32,
    ) -> Result<Vec<String>, PluginError> {
        self.sync
            .query_nodes(&node_type)
            .map_err(|e| PluginError::Internal(e.to_string()))
            .map(|rows| {
                rows.into_iter()
                    .take(limit as usize)
                    .map(|r| r.payload)
                    .collect()
            })
    }

    /// Request a user-facing permission prompt. Always grants in Phase 4 (stub).
    async fn request_permission(&mut self, _capability: String, _reason: String) -> bool {
        true
    }

    /// Return the current user's identity information.
    async fn get_identity(&mut self) -> Result<IdentityInfo, PluginError> {
        Ok(IdentityInfo {
            identity_type: "guest".to_string(),
            storage_tier: "ephemeral".to_string(),
            identifier: "".to_string(),
        })
    }

    /// Discover a plugin that provides a named API (SPI pattern).
    async fn get_plugin_api(&mut self, api_name: String) -> Result<String, PluginError> {
        Err(PluginError::NotFound(format!(
            "no plugin provides api: {api_name}"
        )))
    }

    /// Emit a telemetry event from the plugin.
    async fn emit_telemetry(&mut self, event: String, payload: Option<String>) {
        let payload_val = payload.and_then(|p| serde_json::from_str(&p).ok());
        self.telemetry
            .emit_named(event, Some(self.plugin_id.clone()), payload_val);
    }
}
