//! TractorNativeBindings — host-side implementation of `tractor-bridge` WIT interface.
//!
//! Mirrors `WasiImports` from packages/tractor/src/lib/wasi-imports.ts.
//!
//! This struct will implement the `RefarmPluginImports` trait generated by
//! `wasmtime::component::bindgen!` (Phase 4). Each method corresponds to a
//! function in the `tractor-bridge` interface in wit/refarm-sdk.wit.
//!
//! # WIT → Rust mapping
//!
//! ```text
//! store-node(node: json-ld-node) → store_node(node: String) -> Result<String, PluginError>
//! get-node(id: node-id)          → get_node(id: String) -> Result<String, PluginError>
//! query-nodes(type, limit)       → query_nodes(t: String, l: u32) -> Result<Vec<String>, PluginError>
//! request-permission(cap, reason) → request_permission(...) -> bool
//! get-identity()                 → get_identity() -> Result<IdentityInfo, PluginError>
//! get-plugin-api(name)           → get_plugin_api(name: String) -> Result<String, PluginError>
//! emit-telemetry(event, payload) → emit_telemetry(event: String, payload: Option<String>)
//! ```
//!
//! # Phase 4 — TODO
//! Implement the actual `RefarmPluginImports` trait (generated by bindgen!).

use crate::sync::NativeSync;
use crate::telemetry::TelemetryBus;

/// Host-side implementation of the `tractor-bridge` WIT interface.
///
/// Holds references to storage/sync and telemetry so plugin calls can be
/// forwarded to the actual Tractor infrastructure.
pub struct TractorNativeBindings {
    pub plugin_id: String,
    pub sync: NativeSync,
    pub telemetry: TelemetryBus,
}

impl TractorNativeBindings {
    pub fn new(plugin_id: impl Into<String>, sync: NativeSync, telemetry: TelemetryBus) -> Self {
        Self {
            plugin_id: plugin_id.into(),
            sync,
            telemetry,
        }
    }

    // ── tractor-bridge implementations ───────────────────────────────────────

    /// Phase 4: called by wasmtime when plugin invokes `store-node`.
    pub fn store_node(&self, node_json: String) -> Result<String, String> {
        let value: serde_json::Value =
            serde_json::from_str(&node_json).map_err(|e| e.to_string())?;

        let id = value["@id"]
            .as_str()
            .or_else(|| value["id"].as_str())
            .unwrap_or("urn:unknown")
            .to_string();

        let type_ = value["@type"]
            .as_str()
            .or_else(|| value["type"].as_str())
            .unwrap_or("Unknown")
            .to_string();

        self.sync
            .store_node(&id, &type_, None, &node_json, Some(&self.plugin_id))
            .map_err(|e| e.to_string())?;

        self.telemetry.emit_named(
            "plugin:store_node",
            Some(self.plugin_id.clone()),
            Some(serde_json::json!({ "nodeId": id, "type": type_ })),
        );

        Ok(id)
    }

    /// Phase 4: called by wasmtime when plugin invokes `get-node`.
    pub fn get_node(&self, _id: String) -> Result<String, String> {
        // Phase 4: query storage and return JSON-LD
        Err("get_node: Phase 4 stub".into())
    }

    /// Phase 4: called by wasmtime when plugin invokes `query-nodes`.
    pub fn query_nodes(&self, node_type: String, limit: u32) -> Result<Vec<String>, String> {
        let rows = self.sync.query_nodes(&node_type).map_err(|e: anyhow::Error| e.to_string())?;
        Ok(rows
            .into_iter()
            .take(limit as usize)
            .map(|r| r.payload)
            .collect())
    }

    /// Phase 4: always grants permission (stub — future: user prompt).
    pub fn request_permission(&self, _capability: String, _reason: String) -> bool {
        true
    }

    /// Phase 4: returns guest identity stub.
    pub fn get_identity(&self) -> Result<String, String> {
        Ok(r#"{"identity_type":"guest","storage_tier":"ephemeral","identifier":""}"#.into())
    }

    /// Phase 4: emit telemetry event from plugin.
    pub fn emit_telemetry(&self, event: String, payload: Option<String>) {
        let payload_val = payload.and_then(|p| serde_json::from_str(&p).ok());
        self.telemetry
            .emit_named(event, Some(self.plugin_id.clone()), payload_val);
    }
}
